### ISSUE TITLE
As an admin, I want subtitle and sort title populated from HathiTrust MARCXML so that the records can be displayed and sorted better.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#100]
## Notes for testing
-  Title and subtitle should both display in admin list view
-  Items should be sorted by *sort title* by default in admin list view but show actual title (i.e., leading definite articles will be displayed but ignored for sorting purpopes)
- Title, subtitle, and sort title should all be editable on the edit form; subtitle and sort title should both be optional
- Hathi record id should be visible but not editable in admin edit view

## Notes for development
- [x] sort titles
- [x] main/sub titles
- [x] page number
- [x] page label
- [x] page tags

~also check if there is a way to pull "cleaner" author, etc. without attached punctuation~

marc records should include information on how many characters to ignore when sorting by title; see http://www.loc.gov/marc/bibliographic/bd222.html 

Adjust the import script to get the sort title; probably should store it in the db to allow review/edit if necessary.  Index in Solr as a separate field rather than copying the display title.

**Comment by rlskoeser** [comment]
@mnaydan FYI, the two records currently sorting first in the admin site look wrong for sort title - I checked and I am interpreting the MARC record correctly, I think it's just coded wrong. I think we could add logic to strip spaces from the sort title to handle those errors, because I can't imagine a title should ever be sorted on a space.  Let me know if you find other errors or things that look wrong.

**Comment by mnaydan** [comment]
Good catch, Rebecca, I see the errant space. The only other thing I caught was my reply to Nick above about items with blank sort titles sorting first.

**Comment by rlskoeser** [comment]
@mnaydan I'm not sure what would be best for the sort title. It feels weird to me to code a default when we expect (and want) it to be populated from hathi metadata; but I'm willing to do that if you and Meredith prefer that.  Would it be better if we make the field required, so you can't accidentally clear it?

**Comment by rlskoeser** [comment]
@mnaydan I'm going to mark this as tested needs attention so I can fix the extra whitespace issue. Let me know if you want anything changed with the edit interface for sort titles.

**Comment by mnaydan** [comment]
@rlskoeser I think making the sort title field required would solve the issue. The edit interface seemed perfectly fine to me!

**Comment by rlskoeser** [comment]
@mnaydan updated to make sort title required in the admin edit interface and automatically remove whitespace from sort titles.

**Comment by mnaydan** [comment]
@rlskoeser cool! The items with the errant spaces aren't at the top anymore. It's sorting quotation marks first, then numbers, then ABC. I tried to delete a sort title and save, and it correctly gave me an error message and told me the field was required. I also tried adding a white space to the sort title and saving it, and it successfully cleaned it out. Everything seems fine to me!
