### ISSUE TITLE
As a user, I want to be able to view a page in Hathitrust by clicking its thumbnail or page number in a search result so that I can quickly and easily see my search result in its full context.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#101]
## dev notes
- [x] thumbnail is a link
- [x] page number is a link
<s>note: still need the "why" here</s>

## testing notes
- [x] After a search that returns results, preview images should link to HathiTrust, as should page numbers, which are displayed above snippets.
- [x] After a search within a book ( a search on the book detail view page), results should appear with a thumbnail of the page and page number that are both links

**Comment by bwhicks** [comment]
Leaving this off awaiting test, as I discovered a subset of hathitrust volumes that have order not as an integer (as it ought to be), but as a string i.e.:
```
https://babel.hathitrust.org/cgi/imgsrv/image?id=uc1.$b14645;seq=UCAL_$B14645_00000036;width=450
```

Will have to re-add handling for this possibility that I thought had been rendered redundant.

**Comment by rlskoeser** [comment]
@bwhicks it's possible I'm indexing the wrong value from the METS xml file. Either way, I think it probably makes sense to correct it at index time rather than display time.

**Comment by rlskoeser** [comment]
@bwhicks I think I figured out what's going on. I changed the structure of the page ids slightly, so the old records are not getting updated/overwritten in the Solr index.  Not sure the best way to handle it. Maybe we add a flag to the index script to clear the index first (or just clear pages)?

**Comment by bwhicks** [comment]
@rlskoeser So that's why some have the old style with extra text? Either way, I think the flag is the way to go.

**Comment by mnaydan** [comment]
Thumbnails and page numbers both link correctly on initial search result page (list view), item detail/"view all x pages" page, and after conducting a new "search within the volume" from the item detail page. Yay!

It opens in a new tab, which is great. @rlskoeser the Hathi page does "flash" an image of the cover before loading the correct page, but this happens on the old site too, and is probably just Hathi cycling through the book as it loads? It doesn't bother me that much, I just thought I'd note it.

**Comment by rlskoeser** [comment]
@mnaydan I think that is just how the Hathi viewer loads, and not something we can control. Doesn't hurt to note it, though.
