### ISSUE TITLE
As a content editor, I want to add edition notes so that I can document the copy of an item that's in the archive.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#102]
## testing notes
- [x] notes should be enterable in the "public notes" and "notes" (private fields) via the admin's change form
- [x] admin search should pull up results based on note contents (consider creating a note with a distinctive phrase and searching on it)
- [x] CSV admin exports should contain the two new note fields and their contents

## dev notes
- [x] add a "public notes" field to digitized work model
- [x] enable editing in admin interface
- [x] make the field searchable in admin interface

**Comment by bwhicks** [comment]
@mnaydan A quick question, for the public and private notes fields, we've included the following help text respectively:
```
Notes on edition or other details to be displayed on the site.
```
```
Internal curation notes (not displayed on public site)
```

Do those make the two sufficiently clear, or do you have wording that you think would help the project team more? (Thanks for your input in advance!)

**Comment by mnaydan** [comment]
@bwhicks I think that's perfect. I would just tweak the first one to "displayed on public site" for consistency.

**Comment by mnaydan** [comment]
Tested all of the above on mdp.39015030724804 and hvd.hwssft. CSV looks good.
