### ISSUE TITLE
As a user, I want to see notes on a digitized work's edition so that I'm aware of the specifics of the copy in PPA.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#103]
## testing notes 
- [x] Add public notes to a work, and they should be visible on the work's detail page as "Note on edition"
- [x] If logged in through the admin, private notes (the "notes" field) should be visible also.
- [x] If logged out (can do so via username in upper right of admin interface), the private notes should not be visible.
- [x] Text searches should include results based on the public notes field (but never private). To test this, add some distinctive text to the public notes field that won't match anything in other field, and then search in the main archive search for it. The appropriate work should appear.

## dev notes
- [x] display the public notes field on the detail view of the item
- [x] include in solr text search field

**Comment by mnaydan** [comment]
@thatbudakguy My sense was that the notes are going to be pretty idiosyncratic and discursive. So unless making them indexed and searchable is super duper easy, I don't think it's necessary?

**Comment by rlskoeser** [comment]
@mnaydan we can pretty easily include the in the main full text keyword searchable field (along with everything else). We just weren't sure if it would be useful or unhelpful.

**Comment by mnaydan** [comment]
@rlskoeser Ah on second thought, if it is easy enough, let's do it! I remember Jeff Strabone saying he wanted to search by editor, which we can only do if we provide that info in the edition notes and make that a part of the main full text keyword search. Thanks for thinking through this with me!

**Comment by mnaydan** [comment]
This works great! I used the text that I input for #102 on mdp.39015030724804 and hvd.hwssft to test. Notes display correctly on item detail page according to admin/user permissions. Keyword search works correctly according to public/private category (i.e., though "nazgul" appears in both a private note for mdp.39015030724804 and a public note for hvd.hwssft the search only returns hvd.hwssft.)
(And thanks for the supremely clear testing guidelines--way helpful.)
