### ISSUE TITLE
Sort options should use cursor:pointer

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#104]
## testing notes
(these are the SORT BY options on the main archive search page).
- when you hover over the sorting options you should the see the "mickey mouse hand" (`cursor:pointer;`). see @mnaydan comment on #65 .
- you _shouldn't_ get the pointer if you are hovering over a disabled option (keyword) or over the "SORT BY" text.

**Comment by mnaydan** [comment]
Yes, you get the pointer now when hovering over active sort options, but not when hovering over disabled options or the "Sort By" text. The girth for getting the pointer seems a lot wider than the other clickable things though? See picture.
![img_3391](https://user-images.githubusercontent.com/22945600/47453004-9421a080-d799-11e8-9ab5-485efc7b6d39.jpg)

The other thing I noticed, which probably belongs to a different story, is that when the browser window is skinnier, the sort options collapse into a dropdown menu but that dropdown menu isn't functional; I can't find a way to scroll through the options.
<img width="892" alt="screen shot 2018-10-24 at 2 34 41 pm" src="https://user-images.githubusercontent.com/22945600/47453209-2f1a7a80-d79a-11e8-8956-c4fd5b6ea085.png">

**Comment by thatbudakguy** [comment]
@mnaydan thanks for catching the broken dropdown thing; I made that #123 .

do you think the clickable area for the sort options in the desktop version is too big? iirc it should be basically a box like this:
<img width="407" alt="screen shot 2018-10-25 at 11 48 23 am" src="https://user-images.githubusercontent.com/4924494/47513287-ec18df80-d84b-11e8-9f72-33818ed27c22.png">
I realize that's a little less predictable because they aren't technically buttons, but it seems OK to me from an accessibility perspective since some people struggle to click things when the clickable area is small.

**Comment by mnaydan** [comment]
@thatbudakguy I agree with the you that for accessibility the clickable area should be bigger than the text! It felt a little too big though, especially since other clickable things on the page don't function that way; you basically had a pointer the whole time and it felt like they melded into one another. Is it possible to shrink it a bit?

**Comment by thatbudakguy** [comment]
OK; I've reduced the clickable area for these.

**Comment by mnaydan** [comment]
That feels way more natural, and still easy to click!
