### ISSUE TITLE
As a user, I want my search input for publication year to be validated in the browser so that I can't enter invalid dates.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#105]
## testing notes
colors will probably change on this.

- on the search page, if you enter a number in either of the publication date boxes that is outside the min/max date range for the archive, you should get a red halo around the input box
- you should also see a "please enter a 4-digit year between XXXX and YYYY" validation message below the inputs
- the form should *not* submit and nothing should happen when the inputs are invalid.

## dev notes
[semantic ui validation docs](https://semantic-ui.com/behaviors/form.html)
Broke this issue off of @mnaydan comment on #65 .

**Comment by thatbudakguy** [comment]
We probably need more input from designer (or from @mnaydan or project team) on how best to do this. Do we want it to look like a popup, like this one?
![screen shot 2018-10-16 at 3 43 46 pm](https://user-images.githubusercontent.com/4924494/47042884-5057e700-d15a-11e8-895e-e508857a93ca.png)
Currently the fields will turn red, like this:
![screen shot 2018-10-16 at 3 44 26 pm](https://user-images.githubusercontent.com/4924494/47042932-68c80180-d15a-11e8-92bf-74337ef0aff2.png)
What else is necessary?

**Comment by mnaydan** [comment]
@thatbudakguy right now the min range works well (when you try to press the down arrow it does nothing, the up arrow increases the numbers) but the max range is wonky. It goes from 1922 to 1559 when you press the up OR down arrow. The up arrow should do nothing and the down arrow should make the numbers descend from 1922.

I think having them turn red and not submitting the form upon invalid entry is good. We could have a popup to the right of the field that says "Please enter a year between 1559 and 1922". I'm happy to get @rlskoeser or designer input on this...

**Comment by thatbudakguy** [comment]
marking this "question" while we talk about design options for it.

**Comment by mnaydan** [comment]
Going to change to "tested needs attention." Feel free to close it out if you're fine with that pop up. I think there's bigger fish to fry unless it's an easy fix.

**Comment by thatbudakguy** [comment]
@mnaydan what browser/device?

**Comment by mnaydan** [comment]
@thatbudakguy Chrome/Macbook for the popup. Haven't tried to see if I can get it to pop up on tablet/mobile or in firefox. I did find this design issue on iPad though, which is prolly a separate issue.
![img_0004](https://user-images.githubusercontent.com/22945600/48577090-443f8080-e8e4-11e8-9dd0-f585f36ec122.png)

**Comment by thatbudakguy** [comment]
hmm, I can't replicate the popup in chrome on my macbook. I think I'm OK with the redundant messaging, but thanks for catching the text wrapping bug. I'll try to fix it as part of #112 .
