### ISSUE TITLE
Style updates: footer

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#108]
## testing notes
**designs**
[desktop](https://zpl.io/b6M87oj) / [tablet](https://zpl.io/2jw1XOr) / [mobile](https://zpl.io/VYBj4nJ)

there are some slight differences in how things stack on mobile/tablet vs the design, but it should look right.

**Comment by mnaydan** [comment]
Looks beautiful on desktop! It restacks well too when you make the window skinnier. 

Also looks beautiful on tablet and mobile. Different than on Zeplin but the way you did it looks cleaner and more standardized across devices. I'll close this one out?
