### ISSUE TITLE
Footer background color in Chrome

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#109]
footer is transparent in chrome:
![Screen Shot 2018-10-11 at 2.25.00 PM.png](https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/bb3f2122-b746-4350-a29d-e5d9f3e0331c)

## testing notes
**(design will be updated as part of #108).**
should be filled, as in Firefox:
![Screen Shot 2018-10-11 at 2.28.11 PM.png](https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/249615a1-1836-493a-a612-27e326476739)

**Comment by mnaydan** [comment]
It looks correctly opaque across chrome, safari, and firefox. So, close out?
