### ISSUE TITLE
As an admin, I want to suppress items from the site so that I can pull content that should not be included or was wrongly added as I am going through and assigning collections to archive volumes. 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#11]
## Notes for testing
- [x] digitized works now have a status field; default is public, you can set manually to suppressed
- [x] should see an indicator on the list view if something is public or suppressed
- [x] should be able to filter the list view on status
- [x] status should be included in CSV export
- when you set a record to suppressed the data should be deleted from the hathitrust pairtree data so we don't actually import and index it again (not sure how you can test this; you could ask us to run the hathi import script on the source id?)
- [x] if you try to switch a suppressed record back to public, you should get a validation error because it's not yet supported

## Notes for development
We don't want to actually delete the record from the database; we'll want to keep a stub at least, to indicate the record was removed and track the history.  
- [x] add a status field; options public/suppressed, default to public
- [x] make editable in admin
- [x] display status in the admin list view so removed items are obvious; also configure as a filter.
- [x] Include status field in CSV export 
- [x] when status is changed to suppressed, delete rsync data so it won't be re-added/indexed on a full import
- [x] don't allow un-suppressing items (validation? pre-save hook?)

### out of scope
- We may eventually want a bulk removal option, but consider that out of scope for now.
- Supporting "un-suppress" logic is out of scope for now.

**Comment by mnaydan** [comment]
I tested the checklist above and it all works as it should! Five items (nyp.33433082311741, mdp.39015019158776, wu.89099903650, mdp.39015003633594 and njp.32101066874502) were all suppressed and successfully removed from the pairtree data.
