### ISSUE TITLE
Style updates: collections page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#115]
## testing notes
**designs**
[desktop](https://zpl.io/bW48p41) / [tablet](https://zpl.io/a3vLveW) / [mobile](https://zpl.io/a8Zg4kK)

**Comment by mnaydan** [comment]
-**Tile size:** In the Zeplin designs, the tiles are all the same size: they seem to conform to the size of the largest tile (the one with the most text), and the tiles with less text on them have more white space at the bottom to fill out the size. On the test site, Grammar and History are smaller and Original Bib and Poetry are bigger based on the amount of text. I think it looks better to standardize the size? 

- **iPhone text margins:** On iPhone the margins for the blurb ("The Archive builds...") don't line up with the left edge of the tiles like they do on Zeplin or on iPad. It looks kinda weird but not terrible--is it an easy fix to line it up?
![img_3390](https://user-images.githubusercontent.com/22945600/47451458-d8ab3d00-d795-11e8-986d-9de4a2eb3c29.PNG)

- **Touch interaction:** You'll see on the screenshot too that the tile highlight is melon. On iPad and iPhone if you touch one of the active tiles to scroll, it turns melon and stays melon even after you lift your finger. It doesn't bother me that much, but you tell me whether it's behaving how you want it to.

**Comment by mnaydan** [comment]
Page description text margins line up great with the card edges on tablet and mobile.

Re: touch interaction - the tiles still "stay clicked" (melon) until you touch something else on the page (it doesn't change when you lift your finger). This behavior is fine for me, if you're ok with it.

This is super nit-picky-- for mobile, the white space margins on the verbosest tile (Poetry) isn't equal on the bottom and top like it is on iPad and desktop for some reason; the margin is twice as big on the bottom. But no one would notice that but me--it's a difference of .5cm. It's fine.
