### ISSUE TITLE
Style updates: search within work page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#116]
## testing notes
**designs**
[desktop](https://zpl.io/brlZloW) / [tablet](https://zpl.io/bPvjvrM) / [mobile](https://zpl.io/2vNZW0r)

**Comment by thatbudakguy** [comment]
marking this "question" while we talk about potentially redesigning it.

**Comment by mnaydan** [comment]
1. We are changing the language from "HathiTrust Volumes" to "View on HathiTrust" (as shown in the design).
2. The labels in GD's design are unbolded; the labels on the test site are bolded. But I actually think the bold helps with readability (esp on mobile)

**Comment by thatbudakguy** [comment]
language has been updated. agree about the bold; fine with keeping it that way if y'all are.

**Comment by mnaydan** [comment]
Looks good!
