### ISSUE TITLE
As a content editor, I want unneeded punctuation removed when importing or updating records from HathiTrust metadata, so that records are easier to search and browse.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#118]
## notes for testing
Recommend using the CSV export (now updated to include sort title and subtitle) and check a variety of these records. Clean up is not intended to be exhaustive, but to catch a large number of items across the corpus to reduce the amount of manual clean up needed.

Cleaning that should happen on import:
- [x] remove trailing slash and space at the end of title, subtitle
- [x] remove leading punctuation from beginning of sort title: quote, bracket
- [x] remove brackets around inferred titles, publishers, place of publication
- [x] remove trailing punctuation marks from publishers: comma, semicolon
- [x] remove trailing punctuation marks from publication place: comma, colon
- [x] remove 'printed for' and other variants from publisher
- [x] remove `[S.l.]`  and `[s.n.]` for unknown place of publication and publisher
- [x] remove trailing period on author names

Can we get cleaner versions of author, publisher on import? (e.g., can we automatically clean trailing punctuation?) Should we include translator, editor information from MARC? How much of that should be in scope for the current release?

**Comment by mnaydan** [comment]
Continuing our conversation on #56, what about relabeling this issue as something like "Investigate options for bulk cleaning punctuation and excess text in HathiTrust metadata." Then we can add a list of specific things in a comment (slash after title; trailing punctuation; brackets on inferred titles; "printed for" in publisher; enumcron stuff goes in here too I think). I think we should split out the question of whether we want additional MARC info (translator, editor)--that's a different question. I'll have to add to this next week, I'm running out of time this week.

**Comment by rlskoeser** [comment]
Thanks @mnaydan - it will be helpful to split those out into different questions. Next week is fine!

**Comment by mnaydan** [comment]
@rlskoeser Meredith said we will definitely need editor and translator from the MARC record. Are there other things on the MARC record besides those two? I remember Meredith saying at the Board Meeting that searching by editor posed a problem because it was a HT metadata problem. Not intimate enough with the metadata to know what this means. We'll also have to decide whether to put these on the initial search result tiles or just the item detail record (I think just item detail record would be fine?)

**Comment by rlskoeser** [comment]
Occurred to me I could re-write as a story, since this is user testable.

**Comment by rlskoeser** [comment]
From quick experimentation and clustering in open refine, preliminary cleanup for publishers:
`value.replace('[etc.]', '').strip(' ,[]') `

And variant phrases at the beginning of publisher names:
```
Printed by
Printed for
Printed for the
Pub. for
Pub. for the
Published at the
Published by
Published for the
Publisht for the
```

**Comment by mnaydan** [comment]
Generally, looks good.
- Quote and bracket removed from sort title.
- Trailing period removed from author.
- Comma, semicolon removed from publisher.
- Comma, colon removed from pub place (a couple rogue colons, but generally fine).

Here's a list of things that the net didn't catch.
- Slash is generally gone in title/subtitle (still present in sort title); still present in a handful of titles/subtitles with author name ("Principles of English grammar / By A. S. Worrell" is entirely under title). Ellipses with a space after the title also still present. Many records have an extra space between the last letter and the colon.
- Brackets still present in inferred fields if only unclosed "[Ann Arbor, Mich." or if only around part of city "Hartford, [Conn.]"
- Ellipses (preceded by space) and [etc] or [etc., etc.] still present in publisher field. [etc] and variants present in pub place.
- "Printed for" seems to be removed but other variants still present: "printed by", "printed and are to be sold" 
- "[S.l" and "s. n." still present if unclosed bracket or if no bracket
