### ISSUE TITLE
As a user, I should not see suppressed items in search results or item display so that my results are not cluttered by items not meant to be part of the archive.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#12]
## Notes for testing
- [x] suppressed items should not be included in the public archive search
- [x] suppressed items should not be included in collection counts
- [x] suppressed items should not be included in sitemap.xml (maybe check by looking at the xml and then suppressing the first item listed?)
- [x] detail page for a suppressed item should return a 410 Gone page and should not show any item details

## Notes for development
- when a record is suppressed by an admin, delete from solr index (on save, when status has changed)
- when reindexing, do not index suppressed/removed records (maybe index data returns nothing for suppressed items?)
- detail view should return a 410 Gone status for items that have been suppressed
- check behavior for changing a collection name that includes removed items 
- collection counts should ignore suppressed items
-  xml sitemaps should exclude suppressed items

**Comment by rlskoeser** [comment]
@mnaydan a thought: it wouldn't be hard to display the public notes on the 410 Gone page, if you wanted the option of documenting why something had been removed. I don't know how often people will see these, might only come up if someone had bookmarked a particular record on PPA. (Mainly the 410 is for search engines reindexing site contents.)

**Comment by mnaydan** [comment]
All good: suppressed items do not appear in public search, are not included in collection counts, and do not appear in sitemap. Detail page is 410 Gone. @rlskoeser I don't know about the public notes--I added it to today's agenda to ask MM, but will close this issue and open up a new one for the error page if necessary.
