### ISSUE TITLE
Scrollbar should be hidden on mobile

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#122]
## testing notes
Right now the scrollbar for the main content never goes away on mobile (test chrome and FF on android). It should probably either only appear when scrolling, or not appear at all.

**Comment by thatbudakguy** [comment]
update: this seems to have gone away for me, but would love to get @mnaydan or someone else to verify (esp. on iOS / safari).

**Comment by mnaydan** [comment]
@thatbudakguy yup, tested on my phone (iOS safari) and it's hidden now! Kudos!!
