### ISSUE TITLE
Style updates: search sorting and pagination

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#123]
## testing notes
- styles and colors should be correct
- sort dropdown should wrap underneath pagination on tablet and mobile
- relevance sorting behavior should be correct: disabled if you haven't entered a keyword search; enabled once you do

## dev notes
- all javascript used to keep the old sorting section intact should be removed; just one sort menu now.

## original comment
The other thing I noticed, which probably belongs to a different story, is that when the browser window is skinnier, the sort options collapse into a dropdown menu but that dropdown menu isn't functional; I can't find a way to scroll through the options.
<img width="892" alt="screen shot 2018-10-24 at 2 34 41 pm" src="https://user-images.githubusercontent.com/22945600/47453209-2f1a7a80-d79a-11e8-8956-c4fd5b6ea085.png">

_Originally posted by @mnaydan in https://github.com/Princeton-CDH/ppa-django/issues/104#issuecomment-432778141_

**Comment by mnaydan** [comment]
@thatbudakguy it looks right, but "Relevance" is greyed out and not clickable when it becomes a dropdown even when I'm doing a keyword search. When I expand the window and the sort options expand, Relevance becomes clickable again and resorts the options according to relevance.

**Comment by thatbudakguy** [comment]
waiting on new design which will unify the sort menus.

**Comment by mnaydan** [comment]
I noted this on #112 but probably should note it here instead: GD has the default sort option (and I'm guessing, whichever one is selected) as bold ("Title A-Z") on the initial display (not just when you select the dropdown); right now it's regular on the initial display.

Other than that, colors, wrapping looks good across devices.

**Comment by thatbudakguy** [comment]
@mnaydan the reason I didn't bold the currently selected option is because it also shows up as bold in the list of options when you click the dropdown, which would mean it would be listed in bold twice in the same list, which seemed a little weird to me. if it makes more sense to you to just have it be bold in both places, I can totally do that.

**Comment by mnaydan** [comment]
@thatbudakguy I thought that was kind of weird too. Let's leave it, then, and everything else looks good on this ticket so it can be closed.
