### ISSUE TITLE
Pub date display and histogram are broken on Chrome

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#124]
## testing notes
in Chrome, the publication date histogram is indenting itself where it shouldn't:
<img width="1038" alt="screen shot 2018-10-31 at 11 59 36 am" src="https://user-images.githubusercontent.com/4924494/47801376-78237f00-dd04-11e8-9752-f2cfd76d7b27.png">
in Firefox, for comparison:
![screen shot 2018-11-14 at 5 03 33 pm](https://user-images.githubusercontent.com/4924494/48515645-4562a600-e82f-11e8-8cc7-933825d89395.png)
it should look the same (not overflow) on all browsers.

**Comment by thatbudakguy** [comment]
this was an issue with `<fieldset>` elements not being allowed to be flex containers in Chrome. resolved by making them `<div role="group">` as a compromise.

**Comment by mnaydan** [comment]
Good catch. Looks the same (not indented) across Chrome, FF, and Safari.
