### ISSUE TITLE
As a user, I want item titles to be case-insensitive when sorting, so that I can find content alphabetically.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#127]
## testing notes
- when sorting by title, results should now sort upper and lower case together (e.g. see the various 'abridgement / an abridgement' titles, some upper and some lower)
- this update includes a change that will let you search for accented characters with and without the accent (either way will work); e.g. try searching `wörterbuche` and `worterbuche`

See @mnaydan  comment on #56 

## dev notes
- [x] add logic to define new solr field types
- [x] implement case and unicode folding for title string field (we have done this on winthrop)
- [x] configure title sort field to use the new sorted field type

**Comment by rlskoeser** [comment]
See the solr schema field type definitions and methods in winthrop: https://github.com/Princeton-CDH/winthrop-django/blob/develop/winthrop/common/solr.py

**Comment by mnaydan** [comment]
Order of results on user archive now matches order on django admin. Titles are now sorting alphabetically, regardless of case.

Searching with and without an accented ö for worterbuche yields the same number of results (which is what we want, I think).
