### ISSUE TITLE
As an admin, I want the site to provide XML sitemaps for content pages, collection and archive pages, and digitized works so that site content will be findable by search engines.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#129]
## notes for testing
- url to xml sitemap should be included in `/robots.txt`
- `/sitemap.xml` should have sections for content pages, digitized works, and the archive page
- each sitemap subsection should have full urls and last modified dates for the content

## dev notes
this is required to get pa11y to work

**Comment by rlskoeser** [comment]
Rewritten as a user story.

**Comment by mnaydan** [comment]
Looks good! For the content pages, last modified line only appears on the ones I edited in Wagtail (I guess the others have been "created" only). But it does appear if I edit the page, so I think it's functional.
