### ISSUE TITLE
improve author handling on hathi import

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#132]
Would like to move authors (or possibly all creators, if we add editors & translators) out of a text field into a related table so we can group and manage records better. 

Peter Green suggests using the 'known label retrieval' from LOC - https://id.loc.gov/techcenter/searching.html . I checked, if we remove the trailing period  this is working for the sample records we tried. 

This means:
- add a new person model (name, uri; notes?) and replace author text field with a many-to-many
- update hathi import to find existing or add new author record
- use LOC known label retrieval to look for LOC URI and add to the database
- update Solr indexing to handle change to author field
- update CSV export to handle change to include author name and URI

**Comment by mnaydan** [comment]
We decided to do this outside of the database.
