### ISSUE TITLE
Use subresource integrity for external js

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#136]
All external js resources (i.e. from CDNs) should utilize SRI; as per [Mozilla security docs](https://infosec.mozilla.org/guidelines/web_security#subresource-integrity):
```
<script src="https://code.jquery.com/jquery-2.1.4.min.js"
  integrity="sha384-R4/ztc4ZlRqWjqIuvf6RX5yb/v90qNGx6fS48N0tRxiGkqveZETq72KgDVJCp2TC"
  crossorigin="anonymous"></script>
```
[SRI hash generator](https://www.srihash.org/) can be used for resources without a provided hash.

**Comment by bwhicks** [comment]
This looks great. I see `sri` hashes presented.
