### ISSUE TITLE
Up/down arrows broken on max pub field

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#138]
The year changes from 1922 to 1559 whether you press the up or down arrow. Up arrow should do nothing, down arrow should descend from 1922

**Comment by thatbudakguy** [comment]
I can't replicate this in any browser on OSX. Can you post versions of the browsers you're using?

**Comment by rlskoeser** [comment]
@thatbudakguy I can duplicate it. Chrome 70.0.3538.77, Safari 12.0. Firefox 63.0

**Comment by mnaydan** [comment]
@thatbudakguy I'm in Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by thatbudakguy** [comment]
big 🌮 @rlskoeser for suggesting to just populate the fields instead of using a placeholder; I think this is resolved now.

**Comment by mnaydan** [comment]
This is fixed now! The only issue is that if you empty out the max pub field, and then press the arrows, it defaults to 1559 instead of 1922. But if we can build earlier->later sequential validation on the front end to keep the histogram from blanking, I don't think this will be a problem, since we can't control the arrow behavior.
