### ISSUE TITLE
As an admin, I want to add individual digitized items to one or more collections so that I can manage which items are included in which collections.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#15]
## Notes for testing
- Add a Collection using the admin.
- There should be a new field on the admin edit for DigitizedWork labeled collections.
- From the DigitizedWork, you should be able to add it to a collection.

## Notes for development
- Make collection field editable in the individual record view

**Comment by meagan1019** [comment]
Assigned category Brogan; used HathiID from Brogan List (https://docs.google.com/spreadsheets/d/1LefUUauY9yFAZ6vwanLtqBjlTZktKVFaQGxOoag46LA/edit#gid=1457756706) to assign HathiID mdp.39015010807975 to the Brogan collection. I can filter by collection I just created. 

It would be nice to be able to see the "collection" on the Django admin user interface as a visible field column. 

One thing to think about: As @mm4CDH begins to create the new collections, what will be the best way to assign those collections to an individual Hathi volume? Will we be able to download a CSV of the entire Archive and then re-upload it with the category designations or will we have to go into every single individual Hathi volume on the admin site assign the collection by hand to each individual entry?

**Comment by meagan1019** [comment]
Oh, I see that this milestone addresses that: https://github.com/Princeton-CDH/ppa-django/issues/16. Yes, let's prioritize this over the last two milestones (as said on Slack) so that MM can start assigning collection values.

**Comment by rlskoeser** [comment]
@meagan1019 FYI, we did turn on an option to filter digitized works by collection - see the filter drop-down on the top right when you're looking at the list of items.  Is that sufficient for now?
