### ISSUE TITLE
As a content editor, I want to be able to add and order multiple authors to an editorial so I can correctly attribute work.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#150]
## notes for development
- create a new `person` [snippet model](https://docs.wagtail.io/en/v2.3/topics/snippets.html) 
  - I think for now, we should just include a name field and an optional URL (we can add more fields later if we determine we need them or want to adapt/reuse the same snippet for the contributor page)
- add a new [streamfield](https://docs.wagtail.io/en/v2.3/topics/streamfield.html) to EditorialPage - it should have one snippet chooser block, which only allows selecting person snippets; streamfield should handle single or multiple and ordering for us
- update editorial list and detail display to show author names in the order they are listed, with links if they are present

## notes for testing

- You can now add authors to an editorial page in the Wagtail CMS. From the editorial page, there is now an Authors field, and it allows you to create People snippets with a display name and a url associated with them (if desired, i.e. their social media profile, ORCID id, etc.).
- To test, create two. 
They should be:
- [x] displayed on the editorial index page and on the byline of the editorial -
- [x] separated by commas, 
- [x] in the order you have moved them. (You can use arrows in the upper right of each block to order them in the CMS admin)
- [x] If you add a url, the name should be a link ONLY on the editorial page itself, not the index page.

**Comment by mnaydan** [comment]
Tested with one, two, and three authors! Commas, order, and links all good!
