### ISSUE TITLE
As a content editor, I want to control how the description of my editorial content is displayed when on PPA, when shared, and when searched.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#159]
## notes for testing
- content and editorial pages now have an optional formatted description field
- if the description is not entered, the body text should be truncated for display as preview text
- if description is used, it will be used for preview; if it's too long it will be truncated

- if no action is taken, should use the first part of the content as description
- should be able to optionally specify a formatted description
- meta/search description should be a deformatted version of the formatted description, if present

**Comment by mnaydan** [comment]
Description field is present on content and editorial pages.
It is optional and supports formatting.
If a description is present, the description displays as preview text. If the description is too long, it truncates with an ellipses.
Search description is not populated in Wagtail but is in the html (RSK says this is correct).
If description is not present, the preview text is the first part of the body text BUT as Nick discovered ONLY if there is a single text block. Having multiple text blocks seems to mess this up, regardless of whether or not there is a list. Right now, if you have a second text block, the description is simply blank.

**Comment by rlskoeser** [comment]
Wow, you found two different problems here!  

Empty paragraph content (`<p></p>`) in the description wasn't being recognized as empty, and faulty logic meant I was grabbing the *last* paragraph block rather than the first.

I'll have a fix on the test site soon.

**Comment by mnaydan** [comment]
I added blank spaces to the description and the preview ignored them and is correctly drawing from the body text.

It's grabbing the first paragraph block now (rather than the last, and it correctly ignores images).
