### ISSUE TITLE
As an admin, I want a way to search and select digitized items for bulk addition to a collection so that I can efficiently organize large groups of items.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#16]
## Notes for testing
- [x] Select a few digitized works in the admin interface and then select (lower left) from the dropdown to add them to a collection. This will take you to an intermediate page where you can select collections and then finalize the add. 
- [x] On successful add you should be returned to the digitzed works listing with a success message and the collections should be set.
- [x] Try doing this by selecting all items on the page (check box in the top row) and then using the `select all 5007` option in lower left and add everything to a collection. This will take several seconds, but should work.
- [x] Try searching the digitized works for something that returns more than 100 items (e.g. "elocution" returns 259) and add all items from the search to a collection.

## Notes for development
- Implement as a custom django admin action - see https://docs.djangoproject.com/en/2.0/ref/contrib/admin/actions/
- Should provide an intermediate page for user to select the collection - https://docs.djangoproject.com/en/2.0/ref/contrib/admin/actions/#actions-that-provide-intermediate-pages 
- The action shoud be specific to/available for DigitizedWorks only

**Comment by mnaydan** [comment]
I was able to add selected works to one collection, and to multiple collections. I was able to add all 5007 items to a collection. I searched by the keyword "elocution" and was able to add all 259 items to a collection. The bulk addition is therefore functional, but @meagan1019 and I don't know if it's the most useful for our purposes. We will be assigning items to collections primarily by volume ID. Meredith will be going through the admin site or a CSV and assigning collections (sometimes 2-3 per volume) by hand.

**Comment by rlskoeser** [comment]
If you're assigning one or more collections to individual items by hand then doesn't the collection editing provided by #15 meet your needs?

**Comment by mnaydan** [comment]
Yes, that is true. @meagan1019 explained that MM likes to identify collections in an excel file quickly in a column via a shorthand, like [P, H]. Then Meagan and I would have to go in to each item in the admin and assign collections to individual items by hand, which we could do with #15, but it would be time consuming. If we could use Ben's interface to search multiple volume IDs at once, both as a list and as boolean OR [hathiid OR hathiid OR hathiid], even for 100 IDs at a time, that would cut down the time significantly.

**Comment by rlskoeser** [comment]
@mnaydan thanks for explaining.  Let's ask MM to try the collection editing options we've implemented and then find a time to discuss in person.

**Comment by mnaydan** [comment]
@rlskoeser sounds like a good plan. I'll close this issue then, since the bulk addition works (and since adding a multiple volume search would probably be a new feature)?

**Comment by rlskoeser** [comment]
@mnaydan yes, let's do that because it will allow us to get existing collection functionality out to the production site so you all can start using the collection management features we've built so far.
