### ISSUE TITLE
Adding an image in wagtail breaks page design

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#165]
See Milton postcard on "What is Prosody" page and homepage. 

Seems to have to do with size. But wagtail should (hopefully) constrain the image proportions so that you don't have to resize the image manually?

**Comment by thatbudakguy** [comment]
Just a note that I added a super basic fix for this in https://github.com/Princeton-CDH/ppa-django/commit/bd78ade3adb4fa17b24436fccdeeda8a3ea754c7:

https://github.com/Princeton-CDH/ppa-django/blob/d40c6728668ee42805ca5d7b091cba5b3b2d6734/sitemedia/scss/pages/_content-page.scss#L41-L46

this will probably make tall images too large, but it at least keeps them within the margins for now.

**Comment by rlskoeser** [comment]
@thatbudakguy is this fixed? Do we need something more or is it going to be handled in a different issue?

**Comment by thatbudakguy** [comment]
I think this particular issue is fixed, so I'll mark ready for testing. If we decide there are more problems with how images are handled and want to control them, I think that can go in #45.

**Comment by rlskoeser** [comment]
I asked Gissoo to provide desired images for the different screen sizes so we can take advantage of wagtail resizing, but I think that's separate from this. Is it part of #45 or should we create new tasks for the design & dev work?

**Comment by thatbudakguy** [comment]
I'm fine with the implementation/dev part of it being part of #45, but if we want to track extra image-related design by Gissoo on a new issue that #45 can be dependent on that makes sense to me too.

**Comment by mnaydan** [comment]
This is fixed! The images are successfully suppressed for the preview on the cards on the homepage (it's correctly drawing from the body text instead) and Wagtail seems to be constraining the image size on the landing page.
