### ISSUE TITLE
As a user, I want to browse the list of collections so I can find out more about important groupings of items in the archive.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#17]
## Notes for testing
- Add a collection or two (if you haven't done so already)
- Go to 'View Collections' on the main site.
- They should be there!

## Notes for development
- Public facing collection list view.  Propose `/collections/` for url.
- Display collection name, description; number of items?

**Comment by meagan1019** [comment]
Added two Hathi volumes to four placeholder collections. Was able to filter and search through the works assigned.
