### ISSUE TITLE
Style updates: fonts

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#173]
## testing notes

<s>As per meeting discussion on 11/27 we're going to evaluate using Open Sans exclusively vs. a combination of Gentium and Open Sans as before.</s>

Gentium should now be used in these places:
- headers (top of pages)
- collection and homepage card titles
- digitized work titles

**Comment by mnaydan** [comment]
@thatbudakguy Meredith and I prefer the mix of Gentium and Open Sans (see screenshot). However, we don't like how the numbers don't line up as well as when everything is Open Sans. Would it be possible to make the numbers line up better? (Maybe by either by making them smaller in Open Sans or changing them to Gentium too?)  

<img width="1137" alt="screen shot 2018-11-27 at 6 28 20 pm" src="https://user-images.githubusercontent.com/22945600/49541503-eed21000-f8a0-11e8-8841-315496717c98.png">

**Comment by thatbudakguy** [comment]
@mnaydan do you mean the result numbers on the left side? I can definitely play with it to try to get them to line up, but if all else fails making them gentium should do it too. I'll see what I can do.

**Comment by thatbudakguy** [comment]
Changed book titles back to Gentium on the search page and individual work pages, and tried to line up the result numbers a bit more. If there's more places we want Gentium back (card titles? editorial headings?) feel free to kick it back to "needs attention" with a list of places to change and I'll re-add them.

**Comment by mnaydan** [comment]
I added the font question to today's agenda and won't close until we consult MM. 

@thatbudakguy the numbers still seem off? It's small but noticeable--it's the difference b/w this and this:

<img width="1136" alt="screen shot 2018-12-10 at 2 40 21 pm" src="https://user-images.githubusercontent.com/22945600/49757456-77c6be00-fc8a-11e8-8c5b-5bf5121565db.png">
<img width="1136" alt="screen shot 2018-12-10 at 2 40 21 pm copy" src="https://user-images.githubusercontent.com/22945600/49757468-801ef900-fc8a-11e8-868b-a6c12b9bf512.png">

**Comment by mnaydan** [comment]
The numbers look better.
Gentium is now used on headers, collection/homepage cards, and digitized work titles and subtitles (on list view and detail page).
MM and MN changed our minds about adding Gentium to editorial card titles for consistency; we'd like to see how it looks or whether it makes them too long.

**Comment by thatbudakguy** [comment]
@mnaydan let's track the use of gentium for editorial cards specifically on #44 so this can be closed, yeah?
