### ISSUE TITLE
Search in-progress UX

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#178]
## testing notes
**designs** [desktop](https://zpl.io/2jvjK7r)

de-prioritizing mobile/tablet for now because they involve adding the animated icon to the actual text fields so that it's visible higher up on the page; will come back to that later.

the animation and "Results are loading" text should appear when a search is in progress, fading back to the total results/zotero link when the results have loaded.

## dev notes
I'd like to use animation, text, or some form of visual feedback to make it more clear to users when a search is in progress vs. when results have been loaded on the main archive search.

Maybe we can design something relatively low-impact that can make it into MVP.

**Comment by rlskoeser** [comment]
I agree-- sometimes I can't tell that my results have updated. Some visual indicator would be helpful.

**Comment by mnaydan** [comment]
This is a wonderful idea! It's really helpful to the UX and clear. It actually works already on tablet too. 

This is really granular, but on Firefox only it's a little more glitchy. On some keyword searches it'll flash, then go away and show the total number (4,946), then flash again, then go away and show the new number. Also when you clear a text field to "reset" the search, it flashes twice. On Chrome it works really smoothly.

**Comment by thatbudakguy** [comment]
this behavior is tricky to replicate for me, but I changed some simple things that I think might have resolved it. if not, we probably want to push it to icebox for awhile.

**Comment by mnaydan** [comment]
Keyword search and field clearing in FF are working a lot better now. Author is still a little flashy but it's fine.
