### ISSUE TITLE
As a user, I want to filter search results by collection so that I can include or exclude groups of materials based on my interests. 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#18]
## Suggestions for Testing
- add a collection
- add a digitized work (on its edit screen) to that collection 
- the collection should appear on the main search form and allow you to use a checkbox to filter by collection

## Notes for Development
- add a solr collection field to use as a facet (consider text `collection` field and string `collection_exact` copy field)
- add logic to reindex digitized works when they are updated (i.e. when associated with a collection)
- modify the search form to provide a collection facet select field

**Comment by mnaydan** [comment]
We were able to search a keyword and filter search by collection.
