### ISSUE TITLE
Image sizes for editorial and other content pages

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#181]
Provide desired/recommended image sizes for small/medium/large content pages (including editorial essays) so we can take advantage of wagtail resizing and image `srcset` attribute to provide appropriate files for different devices.

You may want to look at the [Wagtail image template tag documentation](https://docs.wagtail.io/en/v2.3/topics/images.html). I'm guessing we'll probably want to use the `max` option to handle both landscape and portrait images well.

**Comment by gissoo** [comment]
Sorry, since I just saw this, thought to reply as you might need this soon. I have put the sizes on Zeplin in the notes section of the editorial detail pages right after you asked. They are written on the desktop, tablet, and mobile designs. Please let me know if they make sense.

**Comment by rlskoeser** [comment]
Wonderful, thank you @gissoo ! I see it now - I did look in Zeplin, but I don't think we've used the notes field before.
