### ISSUE TITLE
As an admin, I want to correct basic item-level metadata errors and preserve those corrections so that I can override discrepancies in source materials for display on the site.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#183]
## Testing notes

To test this, please: 

- edit one of the following fields (or better yet several) in a record or two in the admin: `title, subtitle, sort_title, enumcron, author, pub_place, publisher, pub_date` for a digitized work and save it.
- the fields should be listed under `protected_fields` in the detail view in the admin
- Let the development team  know the source ids of the items that you have updated. The team will run the `hathi_import` and you can then verify that the fields that were modified were not updated or overwritten.

**Comment by rlskoeser** [comment]
@mnaydan have you and your team made any edits in the database that we will need to preserve? If so, this becomes a 5 instead of a 3 so we can account for those.

**Comment by mnaydan** [comment]
@rlskoeser we haven't--we just have a list of the things that need to be corrected.

**Comment by rlskoeser** [comment]
@mnaydan great, thank you for confirming.

**Comment by mnaydan** [comment]
Made edits (various combinations of deletions, additions, and edits) to title, subtitle, sort_title, enumcron, author, publisher, pub_date fields for hvd.hwg11q and to pub_place and enumcron for hvd.32044015547375. The correct fields were listed under protected fields and all edits were preserved after @bwhicks ran import script. Yay!
