### ISSUE TITLE
Non-sequential publication dates break search

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#186]
## testing notes
- min and max dates should be back to placeholders, not "real" values (i.e. nothing is automatically typed into the box for you).
- if you replace _one_ of the dates with a valid date but leave the other as a placeholder, the form should submit.
- the up/down arrows should be gone; date inputs should just look like regular boxes.
- you should see a validation error message if the date is incorrect in any way, including if the publication dates are not sequential.
- the form should not submit and the histogram should not change if the publication date range is not valid.

## dev notes

We need to validate that the min. pub. date occurs before (or the same as) the max. pub. date and not submit the form if it's invalid.

_Originally posted by @mnaydan in https://github.com/Princeton-CDH/ppa-django/issues/131#issuecomment-442972826_:

But you still have a problem if you manually input a bigger value in the min field and a smaller value in the max field, and then try to make the values valid: the form will submit and the histogram labels change but the histogram stays blank, even though the new values are valid. If you refresh the page with an invalid range and then try to make them valid it gets even wackier (see screenshot).
<img width="1011" alt="screen shot 2018-11-29 at 2 44 16 pm" src="https://user-images.githubusercontent.com/22945600/49247762-12e7aa00-f3e6-11e8-9d73-b172d61f512b.png">

**Comment by thatbudakguy** [comment]
- arrows (I learned these are called "spinners"!) should be hidden in chrome/safari now
- padding should be correct since the spinners are gone
- error message should now display if the dates aren't sequential also

**Comment by mnaydan** [comment]
Arrows are suppressed in chrome/safari! 
Padding is good! 
Error message displays for non-sequential dates!
