### ISSUE TITLE
Using actual numbers for date range causes works without a date to go missing when form is submitted

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#196]
Figured out what's going on with the 5,007 vs 5,004. There are three items with no publication date (uc1.c2608792, uc1.b3011277, uc1.b2900825), and the change to use actual numbers in the date range part of the form instead of placeholders means that dates are now submitted any time the form is changed. Not sure what the best solution is; I wonder if we should go back to placeholders? (Maybe add logic to not submit them, but that doesn't seem ideal).

I do think the placeholders set as well as default values (if we stick with them), so anyone who clears them gets a reminder to how it was set.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/ppa-django/issues/148#issuecomment-443910762_

**Comment by mnaydan** [comment]
RSK also said: Adding the missing pub dates is good, but it's still possible this will happen from time to time; we should address the issue.

Maybe we can go back to the placeholder and hide the arrows - seems like it may be possible to do with CSS for at least some browsers: https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box

@thatbudakguy what do you think?

**Comment by thatbudakguy** [comment]
#186 should fix this; I've set them back to placeholders and hidden the arrows.

**Comment by mnaydan** [comment]
Waiting for fixes on #186 to test

**Comment by mnaydan** [comment]
Placeholders fixed this (there are 5,002 works displayed, 5 of which are suppressed = 5,007 total)
