### ISSUE TITLE
As an admin, I want to edit user and group permissions so I can manage project team member access within the system.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#2]
## Notes for testing
- I've customized the user list display to show more information that I hope will make it easier to manage accounts
- There are now two groups preloaded for you: archive manager and content editor (please let me know if you want different names).  An archive manager can edit digitized works; content editor can use the content management functionality (create site pages).
- To test the group permissions and get comfortable with managing user accounts, I recommend the following:
   - Login to the admin site with your own account (should have superuser permissions)
   - Create two new test users.  They should have *staff* permissions (allows login to the admin site) and be *active* but should not have *superuser* (allows everything).  Assign one group to each user.
    - In a different browser or in an incognito window in the same browser, login as your test user and check what that user sees and is able to do in the admin site.
- FYI: I have also set the app to create a `script` user account so that the import script can create log entries for when records are created and updated.  This account should _not_ be removed.  If you have ideas for a better name please let me know!

**Comment by meagan1019** [comment]
Works perfectly! I created TestUser1 (archive manager) and TestUser2 (content editor), edited work and added a page with each account. I didn't see that page reflected on the dev. site -- should that have happened to accept this story? Otherwise everything else worked perfectly.

**Comment by rlskoeser** [comment]
@meagan1019 we have user stories about actual content management functionality that we planned to implement later, so I say you can accept without being to actually view the page.
