### ISSUE TITLE
Styles: footnotes

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#208]
## testing notes
**designs**
[desktop](https://zpl.io/aXkRDrx) / [tablet](https://zpl.io/aXkRZkM) / [mobile](https://zpl.io/bA4397P)

like #209, these can be tested by adding the special "footnotes" block to an editorial in wagtail and writing some content in it.

**Comment by mnaydan** [comment]
If just text is entered in the footnote block, there needs to be more padding in between the line and the first line of text. The padding is correct if you use the list style (compare below)

<img width="941" alt="screen shot 2018-12-14 at 1 09 07 pm" src="https://user-images.githubusercontent.com/22945600/50019786-eca73a00-ffa1-11e8-80b9-98b132b3d585.png">

<img width="539" alt="screen shot 2018-12-14 at 1 13 16 pm" src="https://user-images.githubusercontent.com/22945600/50019839-1e200580-ffa2-11e8-81ea-eff570670b10.png">

**Comment by mnaydan** [comment]
Padding fixed. Looks good!
