### ISSUE TITLE
As a user, I want the advanced search pulldown state that I have selected to be preserved when I reload the page so that my view of the search form is stable and consistent without having to continually modify my selection.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#215]
## dev notes
check storage on page load and use the value there to decide if the search is open. when it's toggled, commit the new value to storage.

**Comment by mnaydan** [comment]
What about something like this? (Feel free to revise, hard one to write.)
As a user, I want the advanced search pulldown state that I have selected to be preserved when I reload the page so that my view of the search form is stable and consistent without having to continually modify my selection.

**Comment by thatbudakguy** [comment]
@mnaydan quick question on this - there are actually two similar but slightly different options; wondering which you think would be more useful.

`sessionStorage`: state of the advanced search pulldown is remembered for the duration of your "session", i.e. as long as your browser window is open. you can make new tabs, close tabs, and refresh and it'll still be remembered. state resets when you quit/close the browser.

`localStorage`: state is remembered "always", including closing/opening the browser, unless you manually clear the storage.

**Comment by mnaydan** [comment]
@thatbudakguy ooh, interesting question... My impulse is sessionStorage--I *think* that's what I'd expect as a user. 

I could see cases where a basic user might work briefly in Advanced Search, but not manually close it at the end of their session and not necessarily want all the power features upon opening their browser again. What do you think?

**Comment by thatbudakguy** [comment]
@mnaydan correction: with `sessionStorage`, new tabs won't remember the state of the pulldown. it does still persist across reloads, however. does that change your answer?

**Comment by mnaydan** [comment]
@thatbudakguy I asked MM and it's actually better that new tabs won't remember the state of the pulldown--users generally create/use new tabs to view multiple results, not do multiple searches.  sessionStorage sounds like it'll be perfect for our needs.

**Comment by mnaydan** [comment]
It's preserving the state after reload across browsers and devices. But on all 3 browsers, the initial load of the Archive is jumpy--it shows the advanced search and then immediately collapses. On Chrome only it is also jumpy whenever you toggle away and then back--regardless of which option you choose. If you choose collapsed, toggle away and back, it shows the expanded before immediately collapsing. If you choose expanded, toggle away and back, it shows the collapsed before immediately expanding. Don't know if you have control over that.

**Comment by thatbudakguy** [comment]
OK, it should be slightly less jumpy now? still seems to jump just a bit if you keep it closed and reload the page, but keeping it open looks OK to me.

**Comment by mnaydan** [comment]
Yes, still jumps in Chrome a bit (especially if it starts closed) but is better. (When it's open it seems to be jumping from the collections bar instead of the whole field, so it's somewhat better.) I think it's fine.
