### ISSUE TITLE
Advanced search pulldown styles

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#217]
## testing notes
- the text "advanced search" should have a chevron next to it indicating which way the search will pull down
- there should be a red dot next to the "advanced search" text indicating when advanced search fields have active values in them

**Comment by mnaydan** [comment]
Looks good! (And is helpful!) Arrow and dot appear across browsers and devices. Arrow changes orientation indicating which way dropdown will open.
