### ISSUE TITLE
Clean up <head> metadata

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#218]
## notes for testing
You can use the [twitter card validator](https://cards-dev.twitter.com/validator) to check twitter display. Check the home page, archive page, and a detail record; should use public notes as the summary if there are any. Feel free to check other content pages to see that search title and description come through properly.

## dev notes

from slack discussion:
> `twitter:description` and `og:description` are commented out because we can’t use a repeated block to fill them all in the same way. There is supposed to be some order of fall-back display but I can’t remember if twitter uses them (Slack does for unfurling)

we can explore setting properties in the view instead of the template/using snippet. we also need to set them for pages that wagtail doesn't know about:

- [x] archive page title and description
- [x] digitized work detail page?

**Comment by mnaydan** [comment]
What a nifty tool! These look good. I added search descriptions into the promote pages for collections and editorial and then they appeared in the card. Detail record is using public notes.
