### ISSUE TITLE
Not excluding Word Lists and Dictionaries on initial load

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#222]
Correctly excludes after conducting a search.

**Comment by rlskoeser** [comment]
Dumb mistake on my part. I added logic to not filter by collection when all collections are selected (because the Solr query should be equivalent but faster without the filter), but the way I was checking for that case was wrong. Should be fixed now.

**Comment by mnaydan** [comment]
This is working now across browsers! I'm so glad it was an easy fix.
