### ISSUE TITLE
Space after colon in fielded keyword searches are leading to strange results

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#223]
Tried with subtitle and it generated empty records; number of digitized works is off (it returns 4,999 records and only 4,948 are shown with dictionaries and word lists excluded).  Tried with author and returned irrelevant records.

**Comment by rlskoeser** [comment]
@mnaydan the team discussed this one when we estimated last week, and we couldn't think of anything that could be done. What you're seeing is the default behavior of the `edismax` query parser, and as we've learned it's pretty error tolerant. We're concerned that by trying to work around this problem we're more likely to introduce errors. 

I'd like to close this with a "won't fix" tag but wanted to give you a chance to respond.

**Comment by mnaydan** [comment]
@rlskoeser trust you guys, sounds fine to me. The correct syntax is included on the how to search section ("Enter the lower-case field type, a colon, and your search term without any spaces after the colon") so if people get weird results they'll hopefully look there.
