### ISSUE TITLE
Remove <h4> from wagtail editing interface or add styles for <h4>

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#225]
currently we allow the user to level-4 (`<h4>`) headings. there's no design for this, however, so they look awkward:
<img width="382" alt="screen shot 2018-12-19 at 2 34 26 pm" src="https://user-images.githubusercontent.com/4924494/50243435-35dcfc80-039b-11e9-8b79-e137e35309e5.png">
we need to disallow the `<h4>` tag type or add a style.

**Comment by thatbudakguy** [comment]
Changed h4 to be a smaller version of h2 - let me know what you think.

**Comment by mnaydan** [comment]
@thatbudakguy yes I like this, thank you, looks good!
