### ISSUE TITLE
Hyperlink styles not showing up everywhere on site

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#226]
Places where hyperlinks are unstyled:
- Homepage body text
- Editorial landing page body text
- Should be supported in Collections landing page body text, too.

**Comment by thatbudakguy** [comment]
I've added styles to hyperlinks globally, but that caused underlines to show up in some places we didn't want them. Hopefully I've handled all those cases.

**Comment by mnaydan** [comment]
Styles are appearing now in the places I commented above but:
@thatbudakguy underline is appearing on the following items and shouldn't be:
1. About dropdown menu items
2. "About" submenu and "Accessibility" links in the footer
3. "View and Search the Archive" button on homepage and collections page
4. Hathi ID on item detail page has a double underline now--it should only have 1 underline.
5. page numbers after you "search within volume" on item detail page.

**Comment by mnaydan** [comment]
1-5 are all corrected now, thank you!
