### ISSUE TITLE
Implement HTTP strict transport security (HSTS)

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#229]
Relevant [django documentation](https://docs.djangoproject.com/en/1.11/ref/middleware/#http-strict-transport-security), although @bwhicks is probably right that we should just do this in apache.

This has no effect in dev since we don't use https or apache.

In QA maybe we could use something like:
`Strict-Transport-Security: max-age=3600;`
-> force HTTPS for one hour at a time

And for production:
`Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`
-> force HTTPS for one year at a time (minimum recommended), include subdomains, and submit for inclusion in the [preload list](https://hstspreload.org/)

**Comment by bwhicks** [comment]
Had a brainwave. No sysadmins needed (though will have them Puppet it). This is done for both.
