### ISSUE TITLE
Add error handling for collection id on archive search form

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#232]
## notes for testing
This error was triggered by someone scanning our site for vulnerabilities, but to check manually, go to the archive search page and add a non-numeric collections option. If you compare with production, you should see a 500 error in production but not in test. It doesn't currently display a validation error - which it probably should - but at least not erroring should be sufficient for now, especially since this is an unlikely case to be triggered by someone not trying to hack the site.

## dev notes
Bad input on the request (sql injection attempt) causes a 500 error instead of an invalid form error. Example input: 
```
form_opts | {'collections': '1" or (1,2)=(select*from(select '                 'name_const(CHAR(111,108,111,108,111,115,104,101,114),1),name_const(CHAR(111,108,111,108,111,115,104,101,114),1))a) '                 '-- "x"="x',  'sort': 'title_asc'}
-- | --
key | 'collections'
kwargs | {}
searchform_defaults | {'collections': [0, 9, 10, 3, 4], 'sort': 'title_asc'}
self | <ppa.archive.views.DigitizedWorkListView object at 0x7f86c28a2b00>
val | [0, 9, 10, 3, 4]
```

Causes an error on ppa/archive/forms.py line 146 because of the `int()`:
```
pk_values = [val for val in value if val and int(val) != self.EMPTY_ID]
```

**Comment by mnaydan** [comment]
No 500 error on test anymore with url <https://test-ppa.cdh.princeton.edu/archive/?collections=foo>, but there's no validation error either--it just returns 0 results. It also breaks the histogram--modifications to the form from this page (selecting a collection, doing an author search) yield results but histogram stays blank. @thatbudakguy was going to investigate to see if there's an easy fix.

**Comment by thatbudakguy** [comment]
@mnaydan histogram breaking should be fixed now. I think we're probably OK with there not being a validation error because you have to manually type an incorrect value in the URL bar to get this result, which 99% of people would never do

**Comment by mnaydan** [comment]
Histogram is fixed now after changes are made to the form. Agreed about this being a fringe case.
