### ISSUE TITLE
Search loading animation layout is broken in Firefox

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#233]
When it appears, the search loading animation is giant and appears in the lower right corner of the page in Firefox.

<img width="590" alt="screen shot 2019-01-22 at 1 19 37 pm" src="https://user-images.githubusercontent.com/4924494/51556519-69062600-1e48-11e9-99ec-cf5a5227bc3f.png">

**Comment by thatbudakguy** [comment]
fixed in test?

**Comment by wafaisfahany** [comment]
Fixed!
