### ISSUE TITLE
Homepage logo placement is broken without javascript

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#239]
When the homepage is loaded without javascript, the logo image layers are placed incorrectly. This layout may sometimes be visible to users with javascript, if the js does not load or loads slowly.

Can we set default placement with CSS without interfering with the js layout?

<img width="1353" alt="screen shot 2019-01-23 at 3 45 36 pm" src="https://user-images.githubusercontent.com/691231/51635934-f8353b80-1f25-11e9-8562-5b530bdb6a0f.png">

**Comment by thatbudakguy** [comment]
I was wrong and this mercifully just needed the right `position:` values in the right place. Hooray!

**Comment by wafaisfahany** [comment]
Not sure if this still needs to be tested w/o Js?

**Comment by rlskoeser** [comment]
I think we can test the no-js features ourselves. I just checked this one with javascript turned off and it looks good!
