### ISSUE TITLE
As an admin, I want to add one or several new items from HathiTrust with a script so that I can add content to the site if I identify something that should be included in the archive.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#240]
## Notes for testing
Testing the script requires asking a developer to run it for you. Provide test ids to run it two ways:
- list of HathiTrust ids
- text file with a list of ids, one per line

Include a few existing ids and bad ids to check errors.

Expected results:
- ids already in the system should be reported and skipped
- reports if the record can't be found in hathi (i.e. invalid id)
- reports if there wasn't permission to get the data package from hathi (currently will happen for Google Books content)
- if everything works, should create a new record and index work and pages in Solr
   - record will be available in Django Admin and public site
   - history in Django Admin will document creation via hathi_add script

## dev notes
- ~new admin view with text box to input ids - needs validation & permission checking~
- [x] use data api to grab data package and add to pairtree filesystem
- [x] kick off indexing
- [x] manage command wrapper around same functionality (handle larger batches)
- [x] ignore duplicates and bad ids; either ignore or un-suppress suppressed ids, whichever is easier

Conversation from Google Doc:
Adding content using the existing code and hathi apis shouldn't be too hard (I think); dev team could investigate enough to estimate. We should discuss how you want it to work...How about a plain text list of ids, one per line? We can give you a text box you can paste them into from your spreadsheet.

**Comment by rlskoeser** [comment]
@mnaydan are you fine with the proposed approach of a text box where you add ids one per line?  What should happen if you include an id that is already in the database?

There will be a practical limit of how many you can do at once for time reasons, but not sure what it is yet.

**Comment by mnaydan** [comment]
@rlskoeser yes that sounds best. Can it run against the IDs already in the database and flag duplicates? I guess I'd expect it to add all the non-duplicates, flag the duplicates, and ask me if I'm sure I want to add them? 

Just to clarify, this issue is on the bottom of our rung for March milestone, and we are fine with adding the Hathi items via RSYNC for now if you guys have too much on your plates.

**Comment by rlskoeser** [comment]
@mnaydan thanks for clarifying priority - that was my sense as well, but thought I could clear up some specifics now in case we get to it.

We can't actually add a record twice, so duplicates should be flagged and skipped maybe - but probably not error, and process all the others? We could potentially use this to un-suppress a record that has been suppressed, but I'm not sure if that adds complexity - if so, I'm inclined to leave it out for this version.

**Comment by mnaydan** [comment]
@rlskoeser oh good that we won't have duplicates running amok--yes, not an error--skip the duplicates and process the others. 

Using this to un-suppress sounds more complex than we have time for now (it'd act as an override of a suppressed record I guess?) I defer to your judgment.

**Comment by mnaydan** [comment]
The functionality (skipping, reporting) works as expected. 2 new items were successfully added and appear in the admin interface (documented as having been added via script) and appear on the public test site, searchable by metadata and full-text.

@rlskoeser and I discussed that it would be a good idea to add the added IDs to the script output. So I'll wait for that before I close? 

We tested with the following IDs:
njp.32101064464694 (new/Google Books)
iau.31858035187297 (new/Google Books)
hvd.32044074313453 (existing)
hvd.3204$407431345 (bogus)
uc2.ark:/13960/t4vh5jf24 (new/non-Google)
bog.83920139888479 (bogus)
loc.ark:/13960/t13n3f13z (new/non-Google)
njp.32101065410316 (existing)

This is the output:
./manage.py hathi_add -f /tmp/addfromHathi.txt
Skipping ids already present: njp.32101065410316, hvd.32044074313453
bog.83920139888479 - Error loading record; check that id is valid.
njp.32101064464694 - Permission denied to download data.
hvd.3204$407431345 - Error loading record; check that id is valid.
iau.31858035187297 - Permission denied to download data.

Processed 8 items.
Added 2; skipped 2; 4 errors; imported 312 pages.

**Comment by mnaydan** [comment]
Output includes successfully added items and functions as expected:

$ ./manage.py hathi_add -f /tmp/hathiIDS2.txt
Skipping ids already present: hvd.32044074313453
loc.ark:/13960/t9b57vm81 - successfully added
loc.ark:/13960/t8hd8qw5k - successfully added
iau.31858035187297 - Permission denied to download data.
njp.32101064464694 - Permission denied to download data.
bog.83920139888479 - Error loading record; check that id is valid.

Processed 6 items.
Added 2; skipped 1; 3 errors; imported 390 pages.
