### ISSUE TITLE
Style issues with archive tiles on mobile

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#254]
Compare the Test and Zepplin below
1. title should be below number 
2. publication date shouldn't wrap
3. more cushion space between end of title and author/publication headings

![mobile2](https://user-images.githubusercontent.com/22945600/53108035-50029a80-3504-11e9-990f-6d30a362bcb1.png)
<img width="279" alt="screen shot 2019-02-20 at 11 40 06 am" src="https://user-images.githubusercontent.com/22945600/53108041-51cc5e00-3504-11e9-925f-63e4b66128b4.png">

**Comment by wafaisfahany** [comment]
![img_5415](https://user-images.githubusercontent.com/47332262/53527753-cfb8d800-3ab5-11e9-95d5-3c29ca3c58ac.PNG)

Tested on iPhone - looks good 
except "Reset" option not available on mobile size or desktop?

**Comment by thatbudakguy** [comment]
hmmm...good point @wafaisfahany ! we actually don't have the "reset" option on _any_ screen, although it is in the design. I can't remember if we decided that, or I just never implemented it for some reason...?? @rlskoeser @mnaydan any ideas?

**Comment by rlskoeser** [comment]
I don't remember any discussion of it. Looking at the specs in Zeplin it doesn't actually look familiar to me; @gissoo was it a later addition? The placement in the designs makes it look like it is specific to the collections, but I don't know if that's the intention.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy No, my intention was and is for the "reset" to be available on all screens, the feature existed in the old designs and I did not change that, I never had the intention of not having it and don't remember any discussions about that in our process, it's been always in all the updated designs on Zeplin as far as I remember. The only place that I'm seeing now that I have not been showing it is on the **collapsed search on Desktop versions** where only the collections are the visible filters. Should I fix that to also show on the collapsed search? I can't remember if there was any discussion or not on that for the collapsed search actually

**Comment by mnaydan** [comment]
@rlskoeser @thatbudakguy @gissoo I don't remember any discussion of it. It seems like one of those things where the design suggests a certain functionality but we never actually discussed having dev team implement that functionality? I'm wary of having you guys implement a new feature this late in the game. What do you thinK?

**Comment by thatbudakguy** [comment]
I think it's unclear to me what it would do. Does it remove all of your selected collections? If so, you'd get zero results. Does it reset the selected collections to the default ones you get when you visit the search page? That might make more sense and is doable, but it'd definitely take work to implement and/or test (more likely a 2 than a 1).

**Comment by gissoo** [comment]
I’m unsure what the original design intent was, however my understanding of this feature is that it would reset all of the user’s selections back to what their default states were, same with the collections.

**Comment by rlskoeser** [comment]
@mnaydan I agree, I don't think we should implement it now. It seems to me that the form is perfectly usable without that feature, and also that it might require more conversation and revision before implementing anyway (e.g. the way it looks specific to the collections, and the fact that the publication date filter already has a separate 'clear selection' option). 

If it's a feature you think PPA should have at some point, please create an issue to document it.

**Comment by gissoo** [comment]
I'm so sorry, so the "Reset" was the revised version of the "Clear Selection", but somehow I forgot to erase the "Clear Selection" after I added the "Reset", so it conveys as if I added a new feature (which I kind of did because in my revision the collection filters would be reset too, unlike the old design), sincere apologies for missing this :(

**Comment by mnaydan** [comment]
As all the squishy-ness of the text is fixed on mobile, I am going to close this issue. We/I can circle back to the Reset feature if need be, but as @rlskoeser says the form works fine without it and we definitely won't add it in this iteration.
