### ISSUE TITLE
Pagination is off on search the archive page on mobile

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#256]
I think we need an ellipses tile? Compare test and zepplin:
![mobile3](https://user-images.githubusercontent.com/22945600/53108538-34e45a80-3505-11e9-92fd-bb10a3acb9b3.png)
<img width="279" alt="screen shot 2019-02-20 at 11 40 06 am" src="https://user-images.githubusercontent.com/22945600/53108543-3746b480-3505-11e9-9e24-240532a7e024.png">

**Comment by thatbudakguy** [comment]
checked on this again - I think I removed the ellipse tile on mobile because:

1. it doesn't do anything
2. when the page numbers are 3 digits long, there isn't enough space to include an ellipse tile without wrapping everything onto a new line.

are we ok with this?

**Comment by mnaydan** [comment]
@thatbudakguy good point. I am. The way it is now it allows users to go to the last page if they want, and the page number tiles adjust as I would expect them to. Also I don't think people would be paging through results on their iPhone...

**Comment by wafaisfahany** [comment]
Tested on safari*

Pagination still off (even with last page is a double digit number) on both **mobile and tablet** sizes i.e no ellipses tile

**Comment by thatbudakguy** [comment]
@mnaydan how do we feel about this one? worth trying to find some way to show the ellipsis, or alter it on small screens?

**Comment by mnaydan** [comment]
@thatbudakguy I don't think it's worth changing. If a user is paginating through results on their iPhone they need to think about their life choices. Close it?
