### ISSUE TITLE
Remove character limit from publisher field

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#258]
- Work got added through an import tool, which skipped the character limit for publisher field, but edits (to an unrelated field) triggered the limit because they called a save hook
- Should we make sure character limits are removed for all text fields?

**Comment by rlskoeser** [comment]
I checked but didn't see any other text fields with a character limit.

**Comment by mnaydan** [comment]
Tested with source id [hvd.hxkcgn] which was the one causing problems on production. It doesn't call the save hook anymore when I add it to a collection--I tried editing other parts of the form too and everything looks good.
