### ISSUE TITLE
Archive collection buttons are displaying at full width in Chrome

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#259]
## testing notes
the buttons should look the way they do in [the design](https://zpl.io/aXwE6lK), not like below:

![Screen Shot 2019-02-22 at 1.04.48 PM.png](https://images.zenhubusercontent.com/5931d36351aa2c3057804a51/493ab89a-1901-4973-a233-080e767a1c5c)

**Comment by thatbudakguy** [comment]
99% certain it's [this chrome bug from 2013](https://bugs.chromium.org/p/chromium/issues/detail?id=262679). will need to wrap the inside of the fieldset in a `<div>` or something.

**Comment by wafaisfahany** [comment]
Tested - looks good.

**Comment by wafaisfahany** [comment]
Tested in Chrome 
Version 72.0.3626.119 (Official Build) (64-bit)

Looks like the design copy - all good.
