### ISSUE TITLE
Bulk add-to collections tool is clearing items that were previously added to collections individually

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#26]
There must be a "replace" rather than "add" logic bug in the code

**Comment by rlskoeser** [comment]
@bwhicks this is a good candidate for writing the unit test first to confirm you can duplicate the bug in tests before correcting the logic.

**Comment by bwhicks** [comment]
## Testing notes (since I'm reluctant to edit a non team members issue post)

Suggested work flow:
- [ ] individually add a digitized work to a collection (or bulk add several)
- [ ] then bulk add some other works to the collection 
- [ ] both the works added in the first step and the works in the second step should remain set (in admin and front end)

**Comment by mnaydan** [comment]
I searched "dictionary" and added a few results individually, then bulk added a few. All of the works added in both steps remained in the set on the admin and front end. I also successfully added works to multiple collections individually and in bulk. Bug fixed! One thing would be nice if it wouldn't take too much time--after individually adding via the change form, it takes me back to the table view and retains my keyword search (showing me 126 results)--great! When I bulk add, it refreshes, clears my search, and shows me all (5007) results. It would be nice if the bulk add would refresh back to the initial keyword search--useful but not essential.

**Comment by bwhicks** [comment]
@mnaydan Normally this would be a separate issue and development cycle, but that feature happens to be something we have the code for. I'll put it together and push it to QA this afternoon after discussing it with @rlskoeser.

**Comment by bwhicks** [comment]
@mnaydan This is back at you when you have a moment with the change you requested, with an extra testing task. Last issue before the release can be finalized!

**Comment by mnaydan** [comment]
Tested by searching "dictionary," bulk added 5 works, it successfully redirected to same search page. Perfect! Thank you @bwhicks !
