### ISSUE TITLE
Add social media links to footer

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#264]
# testing notes
the social media icons (facebook, twitter, instagram) should be visible & clicking them should go to the correct pages.

I centered the icons on mobile since it seemed to align better with the rest of the content, and otherwise at sizes close to tablet (but not quite tablet) they would be awkwardly stuck out to the right

## designs
[desktop](https://zpl.io/VD4QRel) / [tablet](https://zpl.io/29PMJxY) / [mobile](https://zpl.io/b63wOLW)

**Comment by wafaisfahany** [comment]
*Tested on Mac
Testing notes: 
All social media links functional!

Desktop: 
- Difference: **bolder** in the Zeplin copy -  font looks better on test site
- Items (especially social media links) a bit disproportionately spread out on the test site
Mobile: 
- Difference: More space between "View the archive" and "contributors and board members" in the Zeplin copy - more packed together on the test site -

**Comment by thatbudakguy** [comment]
bolded the links as per spec so we can see how it looks; @mnaydan lmk what you think. I didn't bold the copyright or version number since they aren't clickable links.

i think the spacing of items probably doesn't matter too much since it's bound to differ anyway (the alignment is done by css algorithms rather than by hand, so things rarely match up exactly).

**Comment by mnaydan** [comment]
@thatbudakguy I like how you bolded everything that is a link. The spacing doesn't much bother me.
The tablet footer is weird though:
Linked elements are not bolded. Technical is wrapping weirdly.
![img_42d149c2bc2c-1](https://user-images.githubusercontent.com/22945600/53593054-ad7e9300-3b65-11e9-90e5-0960d9bbd355.jpg)

**Comment by thatbudakguy** [comment]
Hmm, testing on tablet size for me - things are bolded and technical looks right (it's at the end of the line). Same thing in the Safari device emulator. Might need to test on @rlskoeser iPad to get it on a real device.

The bold thing is super weird, maybe refresh a bunch or clear safari's cache? No reason that shouldn't show up if it does on other platforms.

**Comment by thatbudakguy** [comment]
Just tested on a real iPad and it looked right - bold and no weird spacing. Wanna give it another shot?

**Comment by mnaydan** [comment]
Sigh it was the cache. Sorry.
