### ISSUE TITLE
Keyword box disappears in Chrome after initial search

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#268]
Steps to replicate:
-Input search term
-Scroll down to view results
-Scroll up
-Click outside of keyword box to defocus form
Outline of keyword box should disappear.

Testing confirms that this bug is isolated to Chrome version 72. It is not present in version 71 or other browsers.

**Comment by rlskoeser** [comment]
@mnaydan I just tested this (Chrome version 79) and can't duplicate the bug anymore. Could you test to confirm and close it if it's no longer an issue?

**Comment by mnaydan** [comment]
I also can't replicate it (Chrome version 79). Guess Google fixed whatever was interfering.
