### ISSUE TITLE
As an admin, I want a link from the digitized work list view to HathiTrust so that I can check the contents as I curate the archive.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#27]
## Notes for testing
- [x] View the listing of all digitized works. There should now be a second column labeled `Source id` as before, but that is now clickable and links to the HathiTrust url in a new tab/window depending on your browser's defaults.
- [x] View the change form for a particular digitized work. It should also have a similar uneditable link at the top of the form with the same functionality. (The `source_url` field has been suppressed since it is no longer needed and isn't intended to be editable from the admin).
- [x] All other fields appear as they did before (both editable and uneditable)

## Notes for development
- add a property to generate a link to Hathi using `source_url` and display the `source_id`
- link should open in a new window (`target="_blank"`)
- adjust list field to make title the edit link, display source id second
- display on the edit page as well (clickable version)

**Comment by rlskoeser** [comment]
@mnaydan wrote this up based on our conversation. I think we can add this quickly and include in the current work.  I'm planning to switch list order of the digitized work so that the title will be the field you click to take you to the django admin edit form and the hathi id will link you to the hathi page for that record in a new window.  Let us know how this sounds!

**Comment by mnaydan** [comment]
Thanks @rlskoeser this looks perfect and will be super helpful.

**Comment by bwhicks** [comment]
Some quick notes: implemented as a method on admin since the reuse value is limited (rather than property as originally draft) after consultation with @rlskoeser in Slack. 

Re-ordered admin fields to make clickable link higher in field order:

<img width="1076" alt="screen shot 2018-04-24 at 1 40 37 pm" src="https://user-images.githubusercontent.com/17815297/39204189-1cfe1254-47c5-11e8-984b-7e32ab51f2ca.png">

**Comment by mnaydan** [comment]
Source ID field appears in admin table and is clickable--the link takes me directly to the view page on Hathi and opens in a new tab. The link also appears at the top of the change form, is clickable, and takes me directly to Hathi in a new tab. All of the old fields on the change form appear as before (source ID and URL are now collapsed into one I presume) except for page count? Is there a reason this one went away?

**Comment by bwhicks** [comment]
Drat. I looked at the list wrong and missed a field because I had to specify them manually to get the order. I will push a fix  for retesting with page count included

**Comment by bwhicks** [comment]
@mnaydan I have pushed a config to fix that bug (and went through the field list very carefully once more just to be sure). Feel free to retest on this one. (And in the future, also feel free to tag an issue that has a problem with the 'tested needs attention' label under labels in the upper right. That way if there are more than in this case it's easily spotted by you and the dev team.)

**Comment by mnaydan** [comment]
Page count now appears on table and change form. Retested and links to Hathi work fine in change form and table.
