### ISSUE TITLE
keyword search stemming is too aggressive

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#274]
We should index page content in both stemmed and unstemmed versions, with boosting on the unstemmed version so that unstemmed matches will be prioritized.

Notes from @mm4CDH :
> Type the word "decadence" and you get results for "decade." That's the tricky one. It's only keyword search where it's a problem.
> It's mostly a problem for reverse stemming, shorter words that live inside big words but you want to search for the short word.

From @mnaydan:
> I remember running into this when I was testing--and might be my fault for not thinking about keyword search implications at the time. Title search seems to be working the best (but still isn't 100% perfect--"pronunciation" returns mostly "pronunciation" for the first ~50 results but we get some "pronunciations" too after that, before more "pronunciation"). "iamb" in keyword search returns "iambe" "iamb" "iambs" all mixed.

When I checked with PUL devs, they said:
> We usually index in both “ssim” (stands for string/stored/indexed/multiple) and “tesim” (tokenized/english/string/indexed/multiple) for that reason
> Although I guess if you’re searching within you probably want it tokenized. :disappointed:

For the unstemmed version, we should consider using a very simple regex tokenization (maybe [Simplified Regular Expression Pattern Tokenizer](https://lucene.apache.org/solr/guide/6_6/tokenizers.html#Tokenizers-SimplifiedRegularExpressionPatternTokenizer) that doesn't throw away all punctuation (which the default tokenization does), because it would be valuable to search on punctuation like `/` or `|` that is used to mark meter. This version of the index may also better support searching for things like AB rhyme scheme notation (since A normally gets thrown out as a stop word).

**Comment by mnaydan** [comment]
The weirdest thing is that some words yield blank results! (e.g., the first 9 results are blank for "decadence" and the first 78 results are blank for "grass"). 

<img width="866" alt="Screen Shot 2020-04-27 at 7 15 15 AM" src="https://user-images.githubusercontent.com/22945600/80368691-1ee5ce80-885b-11ea-8d25-2c993c4aa129.png">

The boosting for the unstemmed words seems to be way better (yay!) but still isn't perfect? (e.g., result 9 for search term "iamb" is "iambe" even though there are more results that are just "iamb"; and when dictionaries and wordlists are included the first result is actually "lambs" (like a baby sheep - OCR error but still, the plural appears first); result 2 for "wheel" is "wheels" and "wheeling"). This might just be as good as it gets, which is pretty good and definitely better than what it was!

I also tested the other search boxes and filters to make sure nothing was broken, and everything else seems to be working fine. Tested in Chrome, Safari, FF.

**Comment by mnaydan** [comment]
To clarify: I'd like to try boosting a little more to see if it fixes the quirks I noted above in the "iamb" and "wheel" examples. @kmcelwee found the blank results bug on production, so I'm opening up a separate issue for that.

**Comment by kmcelwee** [comment]
We undid `content_nostem` configuration because it returned empty results in some, not all, cases. Changes are on the branch `solr-stem-punc`.

**Comment by kmcelwee** [comment]
It seems like the issue was addressed, but we undid our fix because we thought it caused the blank results. We then realized it was a separate issue. I believe all code to address this issue is written, just commented out. However, we may need to add something to the join command in `archive/views.py`

**Comment by kmcelwee** [comment]
(this is a bit tricky so far)
Main unstemmed words that have been discussed so far:
- [ ] iambic
- [ ] decadence
- [ ] pronunciation
- [ ] lovingly

In your opinion, are exact matches appropriately privileged over their stemmed matches?

**Comment by mnaydan** [comment]
Searches for iambic, pronunciation, lovingly, iamb all seem to be pretty good (I'd say they're about the same as I noted on 4/27). The biggest problem continues to be "decadence," which often ranks matches with "decade" or "decades" higher than "decadence." Is this something we can fix? I did notice when testing that if Dictionaries and/or Word Lists are included, that the relevance scores for ALL results go down to 1.0. Not sure if that's related.

**Comment by rlskoeser** [comment]
@mnaydan I noticed that sometimes I was getting 1.0 relevance for everything too (although I hadn't flagged what caused it); I'm not sure what that means either.

It _just_ occurred to me when reading your testing notes that there is a different Solr filter I can use — I think I can configure   it so that decadence is a protected word that shouldn't be stemmed. Do you want to try this? Would it be acceptable for decadence to never match stemmed versions of the word?

**Comment by mnaydan** [comment]
@rlskoeser, yes, that would be great to make decadence a protected word. The ideal would be to do some version of "match all exact matches first and then all stemmed matches after that"--because there might be other words like "decadence" that we are just not thinking of, or maybe there is a hit for "decadences" plural. But if that's not possible, I think it would be acceptable for decadence to never match stemmed versions of the word.

**Comment by rlskoeser** [comment]
@mnaydan I have added a configuration to protect decadence/decadent/decadents from stemming. Please test again at your convenience.

**Comment by mnaydan** [comment]
@rlskoeser it's still stemming to decades for me.

**Comment by rlskoeser** [comment]
😬  sorry — I thought I had the new configuration in place! The files are there, but when I just tested the analysis it does report it as still being stemmed. Apologies for wasting your time.

**Comment by rlskoeser** [comment]
@mnaydan new approach with the Solr stemming override filter factory that I just discovered (can't believe I didn't know about or find this before). Customized for decadence, but now that it's set up it will be easier to add other custom stems if we find other problem cases.

 Please take another look when you get a chance.

**Comment by mnaydan** [comment]
@rlskoeser yay! This seems like a great fix. I think it makes sense for "decadence" and "decadent" to be custom stems of one another. Searches for "decadence" and "decadent" no longer yield "decade" as a result. And it is very good to know that we can add other custom stems for future problem cases we haven't thought of yet! Since the stemming seems pretty good and we've fixed the decadence problem, I'll close out!
