### ISSUE TITLE
Integrate reactive search with google analytics

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#280]
we need to find the best way to inform google analytics that the user is manipulating the form and requesting new results, since the reactive search uses `history.pushState()` which doesn't currently count as a "pageview".

it looks like the simplest way might be:
```js
ga('set', 'page', '/new-page-url');
ga('send', 'pageview');
```
but maybe there are other best practices in use for SPAs, etc.

**Comment by thatbudakguy** [comment]
it would be nice to also configure a [global exception handler](https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions)!

**Comment by mnaydan** [comment]
We want to check if this issue can be solved by the newest version of Google Analytics -- we prefer it to be a configuration in Google rather than a change in our code if possible.

**Comment by thatbudakguy** [comment]
It should be if you turn on ["enhanced measurement"](https://support.google.com/analytics/answer/9216061?hl=en):
> page_view
> each time the page loads or the browser history state is changed by the active site
> This event is collected automatically. You cannot turn off collection.
> An advanced setting on this option controls whether the event is sent based on browser-history events. This measurement option listens for pushState, popState, and replaceState.

**Comment by mnaydan** [comment]
We turned it on!
