### ISSUE TITLE
As a content editor, I want to control how my images are positioned relative to other content so that I can flow text around images and position images side-by-side.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#288]
## testing notes
for clarity, i'm gonna use "floating" to refer to making a piece of content move to one side (left or right) and have other content flow around it
- you now have the option to specify the image style: full-width, floated left, or floated right. new images will default to full-width
![Screen Shot 2019-04-09 at 2 33 53 PM](https://user-images.githubusercontent.com/4924494/55825708-8906c680-5ad4-11e9-8497-c2c018ddb8b5.png)
- note that this is **only applicable to captioned images**. in the future we'd like to have just one "image" block, but for right now you need to choose captioned image if you want a caption _or_ to position the image
- if you add two floated images one after another, they should appear side-by-side
- when images are floated, you'll only see a difference on desktop & larger screens. on all other devices, they will still be full-width and stack, since the image would be too small otherwise
- @gissoo has helpfully added boxes to the zeplin screens so that you can check that the padding between content is correct ✨ 
### zeplin links
[desktop](https://zpl.io/VxLg3d3) / [tablet](https://zpl.io/bLPR9GQ) / [mobile](https://zpl.io/bPPQEpA)
## dev notes

**Comment by mnaydan** [comment]
@thatbudakguy some comments:
1. Gifs are static.
2. If two side-by-side images are immediately followed by a full-width image, the full-width image and caption wrap incorrectly:
<img width="464" alt="Screen Shot 2019-04-10 at 9 35 20 AM" src="https://user-images.githubusercontent.com/22945600/55884261-c3747000-5b75-11e9-9277-084568f294be.png">
3. Text is wrapping if side-by-side images are not the same size. Acc to Gissoo's design, it looks like the text should not begin until after the longest caption, and it should be left aligned:
<img width="482" alt="Screen Shot 2019-04-10 at 9 36 13 AM" src="https://user-images.githubusercontent.com/22945600/55884270-c7a08d80-5b75-11e9-8014-24cbd6cd14f9.png">
4. In this screenshot you can also see that there is not enough padding between Wagtail paragraph blocks ("Type" and "Content Hierarchy/Organization"). I suppose I could make it one text block but I still think abutting paragraph blocks should format correctly.
5. Bottom padding after images looks to be slightly too wide on desktop and on mobile--I'm not sure how to check this precisely, but it looks about 1/3 wider than in Gissoo's design and doesn't match the top padding.

**Comment by thatbudakguy** [comment]
@mnaydan ok, these should be addressed now:
1. @bwhicks added a fix for animated gifs; might need to reupload images for it to take effect.
2 & 3. these should be solved by the same fix; i added it
4. added padding between paragraph blocks
5. adjusted this padding

**Comment by mnaydan** [comment]
@thatbudakguy also fixed the bottom padding of the full-width images so that it's the same as the side-by-side images. Top and bottom padding appear equal now on all image types. Gifs are working and all of the other padding issues are fixed.

Images are stacking properly on tablet/mobile. They look too big, but I believe we just have to size the images outside of Wagtail to fix this.
