### ISSUE TITLE
As a content editor, I want to insert block quotes into the page so that I can use a special style to highlighted quoted material.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#289]
## testing notes
- you can now insert a blockquote when editing a "paragraph" block on any content page (editorial, about, etc). the button looks like a quote:
<img width="360" alt="bq" src="https://user-images.githubusercontent.com/4924494/55819908-d6c90200-5ac7-11e9-9d3c-c5a6bcc3f4ec.png">

- you can either highlight some text you've already written and click the quote button, or click it and then start typing
- when published, the color of the border line on the left should match the color of the section you're in (editorial, about, etc).
### designs
[desktop](https://zpl.io/bJ73DNK)

**Comment by thatbudakguy** [comment]
bumping to a 2 because we didn't have the actual blockquote functionality implemented; i copied the wagtail editor extension code from s&co.

**Comment by thatbudakguy** [comment]
moving back to a 1 since I didn't actually _write_ any new code, just copy it over

**Comment by mnaydan** [comment]
Block quote button works by highlighting or typing.
Color matches page section (tested in editorial and about).

Nick stripped the color side bar if block quote previews on tile on editorial list view; it'll just show up as italics now.
