### ISSUE TITLE
Unify wagtail image block types

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#293]
## dev notes
- [x] make caption an optional property of images
- [x] only render a `<figcaption>` if the caption is not blank
- [x] disable the non-captioned generic image type (try this _after_ changing everything to use captioned image since @mnaydan can potentially do this)
- [x] (if possible) change the captioned image block type to just be called "image"

**Comment by mnaydan** [comment]
I think this works! There's 1 "Image" button in Wagtail now and I was able to add images with a caption and without a caption. Images/captions/no captions appear how I would expect on the public site. I could also float side-by-side images with all of the combinations of captionness.
