### ISSUE TITLE
Editorial content should have an optional field to associate and display one or more editors who contributed to the piece

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#306]
## testing notes
- [x] confirm you can add editors to editorial pieces now; should work like authors
- [x] confirm editor field is optional
- [x] confirm editor displays on editorial page when set
- [x] confirm editor does not display on editorial list

**Comment by mnaydan** [comment]
Looks good! Thank you for the testing notes. Multiple editors are separated by a comma, which makes sense to me.
