### ISSUE TITLE
As a user viewing keyword search results, I want to see a few text snippets from the full text of a work so that I can get an idea how my search terms are used in the work.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#31]
## Notes for testing
- you should not see page images or text highlighting if you don't enter search terms
- you should see one or two page images with text highlighting when you enter search terms; most relevant pages are displayed first; for now, matching terms will be italicized (styles will be added later based on Xinyi's design)
- you should see a link "view all N pages" only if there are more than two matches; link goes to the item detail view for now (actual functionality will be implemented and tested under #32)

**Comment by meagan1019** [comment]
Searched keyword "saintsbury" with book title "poetry" and returned 575 works. (Note: book title and author search seem disabled currently. Searching keyword "saintsbury" alone also returned 575 works. See my slack comment.) Keyword returned in italics, first two images were displayed, and a link for additional page images/results per work was populated (linked to bib entry of work currently). Did the same for searching "saintsbury AND meter" and it worked perfectly!
