### ISSUE TITLE
As a content editor, I want to add SVG images to content pages so that I can include data visualizations and other scalable images.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#319]
## testing notes
Adapted from functionality mep-django. Basic functionality has been tested and accepted, see notes on https://github.com/Princeton-CDH/mep-django/issues/393 
Additional accessibility enhancements have been added to mep-django but are not yet fully tested; see https://github.com/Princeton-CDH/mep-django/issues/404

Don't worry about testing the screen reader behavior, Nick will review that on S&co. But do try adding an SVG image to content and check that it displays properly.

**Comment by mnaydan** [comment]
Added an SVG (ppa-collections.svg from Editorial folder) with and without caption and it looks good across browsers and devices.
