### ISSUE TITLE
As a content editor, I want to create linkable anchors in documents so that I can reference specific sections of my content on other pages.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#321]
## testing notes

This feature was adapted from mep-django, where it has already been tested and accepted. See testing notes and comments on https://github.com/Princeton-CDH/mep-django/issues/464 
Probably useful to run through similar testing steps to make sure you're comfortable with it, and also check that the display for PPA looks ok (link styles are slightly different).

Feel free to compare with the mep-django version of the feature in production; it's currently in use for the FAQ sections: https://shakespeareandco.princeton.edu/about/faq/

I thought this feature would be valuable to bring over to use with the most/least collected items listed in my essay, so that we can link directly to them and make them easier to refer to.

**Comment by mnaydan** [comment]
Works great! Ran through all of Nick's steps on Princeton-CDH/mep-django#464 and it jumps correctly, changes the URL, URL works when pasted in a new window. I added a linkable section to the test version of RSK's editorial page, then I added hyperlinked text on the Collections page and it successfully linked to the Most Collected Items section of the editorial.
