### ISSUE TITLE
Horizontal line wagtail style broken

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#327]
Second horizontal line in the same paragraph block appears white on public site, and lines will disappear in WYSIWYG editor after publishing.

**Comment by rlskoeser** [comment]
@mnaydan can you provide an example where this is happening? Is it currently broken somewhere, or can we duplicate the problem on the test site?

**Comment by mnaydan** [comment]
@rlskoeser kicking myself for not documenting this better! I can't remember how I discovered this. Just tried to duplicate it on test site and it appears to be working properly: 
https://test-ppa.cdh.princeton.edu/cms/pages/28/edit/
https://test-ppa.cdh.princeton.edu/editorial/2021/06/horizontal-line-test/
I'm fine with closing it.

**Comment by rlskoeser** [comment]
Thanks for checking @mnaydan ! I'm glad to hear it isn't a problem anymore.
