### ISSUE TITLE
As a user, I want to see numbered results so I can keep track of results as I’m scrolling and paging through.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#33]
## Notes for testing
- [ ] search results should be in a numbered list instead of a bulleted list
- [ ] numbering should continue on subsequent pages of results (rather than starting from 1 again)

**Comment by meagan1019** [comment]
Searched "amphibra*" in keyword, returned 611 works. Numbers look great, but page 1 runs 1-51 works, then page 2 repeats result 51 at the top (same with 101, 151, etc.)

**Comment by meagan1019** [comment]
Retested looks great!
