### ISSUE TITLE
keyword search yields blank results

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#334]
Happens with search terms "decadence" and "grass." @mnaydan discovered on test site while testing #274 and @kmcelwee reproduced behavior in production.

@rlskoeser: 
> I get the empty results when I add dictionaries to the list of collections, I don’t get them otherwise. When I click on one of the records I get a 410 Gone result, which means that record has been deleted. I think that means our deletion logic isn’t right - looks like we’re deleting metadata but not page content

**Comment by kmcelwee** [comment]
duplicate of #337
