### ISSUE TITLE
suppressed works are appearing as empty results because page indexed data is not being removed

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/ppa-django#337]
## testing notes
1. Use the archive search to find work you can search for based on page content (maybe an exact phrase or something)
2. Login to the admin and suppress that work 
3. Run the archive search you used before to try to find this specific work by page content; confirm you do not see any blank results 
-----
- [x]  update index command to skip suppressed content
- [x] backtrack and clean up already-existing suppressed content
- [x] modify DigitizedWorks save method to clear pages when a record is suppressed

**Comment by kmcelwee** [comment]
Required to remove all suppressed content in index. Need to figure out how to do this continually.

```python
from ppa.archive.models import DigitizedWork
from ppa.archive.solr import get_solr_connection

works = DigitizedWork.objects.filter(status='S')
solr, solr_collection = get_solr_connection()
for work in works:
    solr.delete_doc_by_query(solr_collection, f'source_id:"{work.source_id}"')

solr.commit(solr_collection, openSearcher=True)
```

**Comment by kmcelwee** [comment]
Combining info from @mnaydan's issue #334

@mnaydan wrote:
---
Happens with search terms "decadence" and "grass." @mnaydan discovered on test site while testing #274 and @kmcelwee reproduced behavior in production.

@rlskoeser:

> I get the empty results when I add dictionaries to the list of collections, I don’t get them otherwise. When I click on one of the records I get a 410 Gone result, which means that record has been deleted. I think that means our deletion logic isn’t right - looks like we’re deleting metadata but not page content

**Comment by kmcelwee** [comment]
Testing checklist:
- [ ] The following link led to blank results in the past. Is that still the case? https://prosody.princeton.edu/archive/?query=grass&collections=2&collections=9&collections=10&collections=11&collections=3&collections=4&collections=1&sort=relevance
- [ ] Go into admin, find a suppressed work, directly search for that work and ensure that no blank results appear.

**Comment by mnaydan** [comment]
The blank results seem to be fixed.
I tested with "Aelfric's Lives of saints," which is the only item to come up when searching for exact phrase "bloodthirsty Hingwar." After suppressing work in backend, my search of the phrase correctly yielded no matching items. Tested also with "bad reader," which has 100+ hits, to look for title "Amelia, Tamerton church-tower, etc.," after suppressing it. No blank results in the bunch (3 pages), and "Amelia" correctly doesn't show up. Tested with and without dictionaries/word lists.

Tested other general search functionality, filters, sorts. Mostly fine, but I found some functionality that may have been impacted? @rlskoeser do you think these are related to the changes you made "under the hood"?

- I can no longer see the collections labels on search results at any time (unless I click on the item and go to detail view). I can still filter by collections, though.
- If I keyword search and set date parameters that should yield no results, it briefly goes to 0 matching works, but then shows all of the keyword-matched works through 1922. The end date I've entered isn't registering on the histogram. I can't make this happen consistently, but I've made it happen a handful of times. Search "decadence" or "lady of shalott" and set date parameters as 1600 and 1700.
<img width="1192" alt="Screen Shot 2020-09-17 at 4 10 19 PM" src="https://user-images.githubusercontent.com/22945600/93524568-b202cc00-f902-11ea-94ee-c63626f6b8d8.png">

**Comment by rlskoeser** [comment]
Good catch on the collections! I did indeed break that with my changes, will remedy.

I can't get the date filter problem you describe to happen — it's going to zero results for me every time.

**Comment by mnaydan** [comment]
@rlskoeser I figured that might happen - I can't get it to happen consistently. I guess we can just chock it up to a fluke! 

Glad I could catch the collections, labels at least.

**Comment by mnaydan** [comment]
The collections labels appear to be fixed now, so I'll close out!
