### ISSUE TITLE
As a user, I want to see a simple timeline visualization of works by publication year so that I can get a sense of how the materials are distributed by time.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#34]
### design links
search results: [L](https://zpl.io/adM1x65) / [M](https://zpl.io/V0E1J3E) / [S](https://zpl.io/29DQDky)
### notes
- is it responsive?
- test with a small publication date range (e.g. 1700-1707)
- test with a large range
- test with only supplying one end of the range and leaving the other blank
- does it seem to match up with your results?

**Comment by mnaydan** [comment]
I'm just testing the functionality for the desktop. The up and down arrows work really well! They don't let you go past the limits. Gives me an error message if I try to search with reversed years (e.g., 1915-1560). Works with large ranges. Small ranges work too, boxes are taller/bigger. The whole space is shadowed if I enter the same year in both boxes (e.g., 1900-1900). Visualization seems to correspond with search results. If you fill in the first box and leave the second limit blank, search defaults to 1922 on the other end. Vice versa with 1559. Looks good!

**Comment by thatbudakguy** [comment]
given resolution of #78 I think basic functionality is done for this, so closing. will probably open a new issue to add interactivity, e.g. hover states, in another release.
