### ISSUE TITLE
Propose styles for keyboard navigation and revise the current click and hover styles

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/ppa-django#344]
@rlskoeser I have narrowed down options to 3 versions [here](https://zpl.io/ampmBMe). Please let me know what you think. 
The version on the left may be the simplest one. One of the things that I have been thinking about for some time is how currently the hover style and the select styles in the nav bar and the body of the page are not logical. In the 3 versions you see I have tried to address this problem as well to make the nav indicators more consistent throughout the site. I think the "View and Search the Archive" button on the homepage can stay blue/as is in any of these versions.

**Comment by rlskoeser** [comment]
@gissoo thanks for working on this. I like the first option the best — I like the solid blue buttons and feel like they much more clearly convey the difference between selected and unselected, and the selection indicator looks quite visible to me.  

Why does this revision require changing the nav bar hover style, could you explain how that makes things more consistent?

Would the dashed outline focus style be for buttons only, and not for links? (I'm trying to think through the logic of how we differentiate other focus styles; currently we have a blue outline everywhere.)

I was checking the site to compare nav styles and noticed we don't have a hover styles for the items in the about menu. 😞  Maybe we can fix that at the same time. It seems to me that the blue underline would work better than the corner triangle.

I'm not sure we can differentiate keyboard nav focus from click focus (I feel like this has come up before on other projects...). I did a quick look and found that there is a `:focus-visible` property, but it looks like support for it isn't good enough yet. https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible    
(Hmm, but the blue outline for results shows up when I tab through the page but not if I click... )

@thatbudakguy could you take a quick look at these designs and weigh in? Anything I'm not thinking about in terms of accessibility or implementation?

**Comment by thatbudakguy** [comment]
I also like the first option the best; the dashed outline is a reliable and simple focus indicator that works almost everywhere (including on startwords). If we use it, we probably want to use it for links as well as buttons.

As @rlskoeser noted, we currently can't differentiate between keyboard focus and click, unfortunately...@gissoo you might remember this conversation where I tried it, but didn't succeed: https://github.com/Princeton-CDH/startwords/issues/85#issuecomment-655741572

on the issue of the navbar having different focus/active styles, I'm fine with it. to me, the navbar is a visually distinct entity from the entire rest of the site, and it's OK for it to have unique visual styling with a little more flair. initially I was confused by the triangles, but I've grown to like them 🙂 the gray triangle on focus looks good to me. that said, if we changed the navbar to have focus/active styles consistent with elsewhere on the site, it's probably not a bad thing.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy thank you for your comments. Before I respond to your points and questions, I want to ask you about this: Thank you for reminding me about the differentiation problem between keyboard nav and click – can you tell me, so if we can't differentiate between keyboard nav and click, what would it mean for the collections and the page number buttons? If we go with the first revision, it would mean that the black dashed border will always appear on the _last_ selected button till another button is selected and then it will appear on that button?

**Comment by rlskoeser** [comment]
@gissoo for mouse users, the focus style is only displayed briefly _while_ you click, it doesn't stay focused.

**Comment by gissoo** [comment]
@rlskoeser The reason I ask is because on the Startwords site, the focus doesn't stay briefly while you click, it stays till you click on something else. You can see it on [this page](https://startwords.cdh.princeton.edu/issues/1/) once you click on the purple arrow and scroll up to see the arrow again the the outline is still there till you click out of it or click on another button. 

@rlskoeser @thatbudakguy 
- That being said, I would agree with the first version as well – however I don't like how intrusive the thick dashed outline would look, but I think it's fine – Let's go with this one, let's apply it to the entire site. I've made it thicker here because for the blue buttons the thinner version (currently seen on the site) will not be visible. I agree with Nick that this style works almost everywhere. If we find that it's too thick for other parts of the site, could we keep it black but thinner? 

- Regarding the hover style for the About page, I agree let's apply it there as well – The current hover style has really been bothering me because the visual language for select vs hover should be different, it's very confusing to have the selected buttons on the "Archive" be blue and have the same blue as the hover indicator – I think it's best if we go with the grey triangle for the hover language of the nav bar now that we are revising the visual indicators. I can make sure it's more visible/ a little bit darker if it needs to be.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy I have revised the designs based on my comments [here](zpl.io/a7MzQEp), please let me know what you think.

**Comment by thatbudakguy** [comment]
looks good to me! I like that you found a way to keep the triangle style but make it more visible. Just to clarify - you say:
> I think it's best if we go with the grey triangle for the hover language

I thought we were just talking about focus. Are we going to change the hover interaction for the navbar to also use the grey triangle? If so, I think that's fine, just wanted to check.

**Comment by gissoo** [comment]
@thatbudakguy yes, I would also like to change the hover interaction for the nav bar so we don't use the blue lines there anymore. Thank you, Nick!!

**Comment by mnaydan** [comment]
The design looks good to me! My only question is whether adding a hover style to the "About" will be complicated because it's a dropdown menu? Right now "About" isn't actually clickable - it doesn't take you to a page. Only the dropdown links ("History," "How to Search", etc) are clickable. Do we need hover styles for those too?

**Comment by gissoo** [comment]
@mnaydan thank you for writing!! I suspect we will add the hover styles to the items in the drop-down. @thatbudakguy said he will need to look again at the styles to confirm, but he think that should be no problem. I think this issue can be closed once Nick confirms.

**Comment by thatbudakguy** [comment]
just looked at the design again; shouldn't be a problem. up to you @gissoo if you want to show the hover triangle on the "About" itself, since it's not clickable (but the menu items are).

**Comment by gissoo** [comment]
@thatbudakguy thank you!! 
@rlskoeser do you have any opinions on this? Technically since the response to hovering on "About" is a drop-down there is no utility for a visual indicator – so just having an indicator for each drop-down item is sufficient to me, what do you think about this?

**Comment by rlskoeser** [comment]
This makes sense to me! No indicator on "About" necessary since the drop-down menu gives you the active indicator, but add indicators to the individual menu items.

**Comment by gissoo** [comment]
Great! Thank you @rlskoeser. I think we can close this issue now.

**Comment by thatbudakguy** [comment]
@gissoo sorry to revive this, just a question: what should happen when the big PPA logo in the middle of the navbar is focused? right now it's just applying the same grey triangle to the middle, which looks a little awkward:

<img width="337" alt="Screen Shot 2021-05-18 at 5 52 01 PM" src="https://user-images.githubusercontent.com/4924494/118728260-e0260c00-b801-11eb-8251-13446065599b.png">

also, as you can see, the grey color is really hard to distinguish. I think we might want to make it at least one shade darker.
