### ISSUE TITLE
Long project role title creates misalignment on contributor page

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#355]
<img width="459" alt="Screen Shot 2020-12-11 at 3 18 53 PM" src="https://user-images.githubusercontent.com/22945600/101951146-853e1800-3bc4-11eb-8197-9fc2ea4c6d19.png">

## testing notes
I have updated this to use CSS subgrid, which is supported in some browsers but not all. When I tested it worked on Firefox and Safari, but not Chrome because I don't have a new enough version (I have 116, it's supported in 117).

I tweaked some of the margins because when subgrid works, we get the grid gutter between elements and it was too much space; it might look a little tight on browsers that don't support subgrid.  I didn't test on mobile; if the margins look strange, I could make the subgrid logic desktop only, since it isn't relevant for mobile.

**Comment by mnaydan** [comment]
@rlskoeser I'm getting the same as you -- working on Safari & FF but not Chrome. It looks good on mobile Safari!

Though, when you resize browser window to make it narrow, there are some padding issues. See test versus production.
<img width="445" alt="Screenshot 2023-09-01 at 1 34 32 PM" src="https://github.com/Princeton-CDH/ppa-django/assets/22945600/dbdb6011-97a2-4fae-9146-bbf27b1441fa">
<img width="444" alt="Screenshot 2023-09-01 at 1 34 45 PM" src="https://github.com/Princeton-CDH/ppa-django/assets/22945600/de1accf8-0ddc-4092-9d71-17438d2116d3">

**Comment by rlskoeser** [comment]
@mnaydan revised so I only apply subgrid and adjust margins for template and up

**Comment by mnaydan** [comment]
@rlskoeser looks good! No more padding issue when resizing browser window. Retested on mobile & FF & Safari.
