### ISSUE TITLE
As a user, I want to add a work to my Zotero library from the individual item page so that I can save it for research without having to go back to the list of results.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#36]
## Notes for testing

You need to have Zotero installed and running, and use a browser with the Zotero plugin installed.  On the list archive page, you should see a folder icon (indicating multiple items available).  Click on the folder and after a delay (while it loads the metadata) you should see a dialog box that will let you select all or some of the items on the page for harvest into your Zotero library.

**Comment by meagan1019** [comment]
Searched "elephant AND temper AND surgeon" -- returned 2 results (I don't want to fill up my zotero lol). Both works imported seamlessly into my zotero!
