### ISSUE TITLE
Design an additional field for "Edition" on the work's detail view to communicate a work's edition information

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/ppa-django#367]
[Here are the revised designs](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60bb105e57a91b137f12285c) with the "Edition" field

**Comment by gissoo** [comment]
@rlskoeser I was looking at the multi-edition work that Mary had shared on Hathitrust and the field on their site looks like "5th ed" – I am proposing "5" – will there be different variations for this? Would the edition number not be enough?

**Comment by mnaydan** [comment]
@gissoo I'm sorry if I made this confusing! In response to Q10 in the Google Doc Meredith decided that she does not want a separate edition field because the metadata is too inconsistent and messy. What she wants is a filter on the initial search page to "show only earliest or latest edition in the PPA" for multi-edition works. She wants some way of indicating that we have more than one copy of a work (e.g., [see Bysshe example here](https://prosody.princeton.edu/archive/?title=art%20of%20english%20poetry&author=%22bysshe%2C%20edward%22&collections=9&collections=10&collections=11&collections=3&collections=4&collections=0&sort=relevance)), and the ability for the user to choose whether or not they want to see all of the copies/editions of that work. This is most important for keyword searching when the search yields hundreds of results. 

Here is Meredith's comment for reference: Some baseline feature where we could say 'see only earliest or latest edition in the PPA' would likely be okay for display. The edition metadata is only really important in terms of accuracy for what we have -- we are not going to get accurate edition metadata on these reprinted 18th & 19thC texts, even OCLC / worldcat has a lot of question marks. But if there are 3+ editions of a work with the same title, it would be great to be able to choose not to see all of them in results at first glance.

**Comment by gissoo** [comment]
@mnaydan thank you for writing!! I have revised based on your comment and our conversation on slack [here are the designs](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60b006e5d262497e1e5f9fe6)

I'm proposing that if we have a filter to display "latest edition" and "earliest edition", then on the detail view it would be great to see links to the additional editions along with the titles of those editions if possible. I am showing this in the "view more editions" field.

**Comment by gissoo** [comment]
@mnaydan I'm proposing another solution [shown here](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60b17459be55837a6619d758)

Please start by looking at the pages in order of 1-4 and by following the cursor on each page. I'll schedule for a design review meeting next week so we can discuss these options. I have created more variations but not showing them yet as it might become overwhelming at this point.

**Comment by mnaydan** [comment]
@gissoo thanks, these are so helpful to see. Discussing them would be great. One question I have is how numbering would work for the nested results. If you do a keyword search, there may be hundreds of results, some with multiple editions, some standalone. So would the main numbering skip the nested numbers? Would that be confusing to the user?

**Comment by gissoo** [comment]
@mnaydan That is also one question I have, I'm not sure what the best way to number would be here – but it makes more sense to me that the additional editions would have a different numbering system like "e2, e3 ..." because in this scenario the nested editions are not on the same level as the one we have decided to be the parent.

**Comment by mnaydan** [comment]
@gissoo agreed. We have to be careful with numbers though because editions are often numbered "second edition, third edition, etc" so "e2" might inaccurately imply "second edition" to the user. And the metadata we have for editions is too messy to be useful to the user. An alphanumerical system might work? (Parent result = 1, nested = 1a, 1b, 1c). Or just a bulleted list beneath the parent?

**Comment by gissoo** [comment]
@mnaydan I actually meant it as "second edition" – but I understand that it's not the best way since we don't have the data so never mind.

**Comment by gissoo** [comment]
@mnaydan @mm4CDH @rlskoeser The new designs based on our design review meeting is above in the description section of the issue – please let me know what you think – I had proposed an icon for multi edition but we didn't discuss this so I'm not sure how appropriate or practical it is.

**Comment by mnaydan** [comment]
Thank you, @gissoo! I think they look great - clean, clear. Curious what @mm4CDH thinks of the icon. I think it is cute and I like it but I'm wondering how it might fit with the designs for the excerpts (were you planning on using an icon as well to signal whether it is an "article" or an "excerpt"?) @mm4CDH, having an excerpt/article that is ALSO in multiedition would be pretty rare, right?

**Comment by rlskoeser** [comment]
I'm not sure "view other copies" is quite the right language (to me that sounds like library catalog language for multiple copies of the same item), but defer to @mm4CDH and @mnaydan on preferred wording.

I like the idea of an icon; this one to me looks like a stack of papers more than a stack of books, but maybe my imagination is too literal. I agree with @mnaydan that if we probably want to see how they look together.

If we do use an icon, shouldn't it be displayed on the work detail view as well?

I think in the previous conversation we decided that a multi-edition excerpt would be out of scope for now (if I remember correctly, MM said they were infrequent enough not to worry about it).

On the prefiltered search, there needs to be some indication of how the search is filtered so the user knows what they're seeing and can remove the filter. I don't know yet if an exact title + author search will be sufficient/accurate or if we'll need an edition id field + filter. (If the latter, it would probably not be user-editable but would need to be displayed and clearable.)

@gissoo this is how I'm understanding the flow, please confirm/clarify:
- clicking on "view other copies" from the search results would take you straight to the filtered search results with your current search terms and filters applied
- clicking "see more details" would take you to the detail record for the edition displayed in the search results
- clicking "view other copies" from the detail view would take you to the filtered search results with no filters or search terms

**Comment by mnaydan** [comment]
I agree with @rlskoeser that "view other copies" is not quite the right language -- I don't think MM and I have settled on the language yet. WorldCat says "Search for versions with same title and author." @mm4CDH what do you think of that? I kind of like that the verb "Search" is more accurate for how we're building the flow. And "versions" seems to encompass reprints and editions. Or "Search for more versions" or "Search for more versions of this item." 

Thank you @rlskoeser for reminding me that multi-edition excerpt is out of scope. I still think I'd like to see how all the icons work together (i.e., having a multiedition return and an excerpt return on the same keyword search page), if we're going the icon route for excerpts/articles. It would be helpful to see how they'd look on the search results page and on the detail views.

**Comment by gissoo** [comment]
@rlskoeser @mnaydan Thank you! your comments are super helpful! I have revised the icon that I was proposing here. What do you think about these instead? I'll be testing them on the interface but wanted to get your opinion on them first. ![item versions-v1.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/20b89357-bdb2-4cb0-97a8-4bfeed81e6b3)![item versions-v2.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/a7616f81-9863-4ed9-bffa-2b6100b2541a)![item versions-v3.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/aaab5222-623c-40f4-9ca4-4231af73156a)

**Comment by mnaydan** [comment]
@gissoo I think these communicate "versions of books" better! I like them! It's really hard to say which one works best in isolation like this - I feel like I'd have stronger opinions about them seeing them on the site. I think the 3 stack options might look cleaner? I'm also wondering what the third one would look like without the right side curves being outlined, like how it is with the others -- or does that not work because of how neatly they're stacked?

**Comment by rlskoeser** [comment]
@gissoo I like these a lot too! I like the ones that are a bit staggered better than the one that is lined up (I feel like out of context it might be less obvious that it's books), but not sure about the book flipped backwards. Could you add another variant for testing that has the stack staggered but without a book flipped?

**Comment by rlskoeser** [comment]
I like the first one best!

**Comment by mnaydan** [comment]
I think I'd like to see 1 and 3 in context if possible?

**Comment by gissoo** [comment]
> I'm not sure "view other copies" is quite the right language (to me that sounds like library catalog language for multiple copies of the same item), but defer to @mm4CDH and @mnaydan on preferred wording.
> 
> I like the idea of an icon; this one to me looks like a stack of papers more than a stack of books, but maybe my imagination is too literal. I agree with @mnaydan that if we probably want to see how they look together.
> 
> If we do use an icon, shouldn't it be displayed on the work detail view as well?
> 
> I think in the previous conversation we decided that a multi-edition excerpt would be out of scope for now (if I remember correctly, MM said they were infrequent enough not to worry about it).
> 
> On the prefiltered search, there needs to be some indication of how the search is filtered so the user knows what they're seeing and can remove the filter. I don't know yet if an exact title + author search will be sufficient/accurate or if we'll need an edition id field + filter. (If the latter, it would probably not be user-editable but would need to be displayed and clearable.)
> 
> @gissoo this is how I'm understanding the flow, please confirm/clarify:
> 
>     * clicking on "view other copies" from the search results would take you straight to the filtered search results with your current search terms and filters applied
> 
>     * clicking "see more details" would take you to the detail record for the edition displayed in the search results
> 
>     * clicking "view other copies" from the detail view would take you to the filtered search results with no filters or search terms
>

- @rlskoeser Confirmed, exactly what my intention was in the designs.

**Comment by gissoo** [comment]
@mnaydan @mm4CDH @rlskoeser please review the two "multiple version" icons in context in the designs as well as how they would work with the other icons on the keyword search page – 
- [here](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60c2870f04285568b0f89320) you can view one version of the icon 
- and [here](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60c2868a195812bd6fdc13f2) you can view the other version of the icon

Note: because the "multiple version" icon is conceptually and in terms of its purpose different from the other two icons (excerpt and article) I would strongly suggest that its position on the page would be different from them, like how I have proposed. 

Please let me know if the mock ups don't make sense or if something is missing and I'll be happy to meet quickly and/or revise.

**Comment by rlskoeser** [comment]
I like the staggered stack of books a lot. The other version isn't as recognizable as books to me.

I agree with you on placing it differently from the item type icons.

I'm not sure about the alignment of text and icon on the search results — something feels a little off to me there but I'm not exactly sure what (icon and left margin alignment? icon and "search in more versions" text vertical alignment?). I don't feel strongly about this, just something I noticed.

I like how the text and icon look together on the detail view  — but why is the icon in the margin. Is that important?

**Comment by gissoo** [comment]
@rlskoeser thanks for commenting, please review below. 

@mnaydan @mm4CDH Please look at [the revised designs here](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60c3cf153c78290f4a1fc24d) to see the icon that I have created for the "multiple version" use case (the staggered books).

1. I have revised this icon a bit – looking at it again after yesterday there was something visually wrong – I have staggered them a bit differently and also added some tiny line details to the white portion (the book pages)

2. I have revised the alignment – the alignment you see now on desktop, tablet, and mobile are what I prefer and believe is what more practical from the dev aspect. I prefer that the bottom of the staggered books are aligned with the link because visually it gives more of a "piled books" effect, otherwise it can look a bit awkward.

3. revised the language to one of the options that Meredith had written on Slack last night, [this one](https://cdhprinceton.slack.com/archives/C7G1ACKGB/p1623374947003100?thread_ts=1623358887.030300&cid=C7G1ACKGB).

4. added a more comprehensive view since I added the tablet and mobile – note: in PPA, originally, the tablet view looked more like the desktop view so I have kept that consistent – I prefer for this icon to be placed next to the link rather than above it 

Please let me know what you think and if anything is missing or if there are issues, otherwise please close the issue.

**Comment by gissoo** [comment]
Also, [here is the version with the prefiltered search results](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60c3e0a8929ba112f9f6ee0f) if you find this combo helpful

**Comment by mnaydan** [comment]
@gissoo I think it looks terrific! I love the revised staggered (the alignment feels right now) and placement. One tiny thing - should the v in "view" be capitalized? So that it's consistent with other sentences on the site (e.g., "Search within Volume," "See more details"?

**Comment by mm4CDH** [comment]
I think this looks fantastic! I also love that the letters are all lower-case, actually.

**Comment by mnaydan** [comment]
@gissoo if you don't think consistency with capitalization is an issue and MM likes it then I'll close out!

**Comment by rlskoeser** [comment]
Agree, this looks great! Alignment and placement is better, whatever it was that seemed off has been addressed by your changes.

**Comment by gissoo** [comment]
@mnaydan I think it doesn't bother me that they are not consistent because we wanted to draw less attention to this link as well, capitalizing the "v" looks a bit odd to me, especially since the text is not very short.
