### ISSUE TITLE
Design a variant for the label on the source field on the work's detail view so the language would include ECCO sources

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/ppa-django#368]
I have just added the variant labels on the left of the screens [here](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60bb0f9e3de1ad12762a1520)

**Comment by gissoo** [comment]
@rlskoeser what will the link look like for Gale sources? I did look on the Gale links that Mary had shared but couldn't find something clean like the HathiTrust ones.

**Comment by mnaydan** [comment]
@gissoo two notes:
1) The MOU suggests the language "View on Gale Primary Sources" so perhaps we should use that?
2) Do you mean a clean and unique record ID? ECCO has unique Record IDs for each work that are strings of numbers preceded by a CB or CW: (e.g., CW0118347262).

**Comment by gissoo** [comment]
@mnaydan I have revised the designs, the new link is above in the description section of the issue – what do you think?

**Comment by mnaydan** [comment]
@gissoo yup that looks right to me!!

**Comment by gissoo** [comment]
@mnaydan Great!! @rlskoeser please review the designs as well – the link is above in the description section of the issue

**Comment by rlskoeser** [comment]
This looks great to me too.

**Comment by rlskoeser** [comment]
@gissoo if you want your list to be comprehensive, the other variant we have in the code is "view external record" (These are for records of source type "other", which are bibliographic only and look to be currently unused).
