### ISSUE TITLE
As a user browsing the list of collections, I want to see brief summary statistics so I can decide which collections of materials I want to browse.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#37]
## Notes for testing

On the collection list page, you should see a count and date range for each collection.  Feel free to add new test collections on the test site to play with this - you can add lots of items or a few.  Hopefully the Solr indexing will keep up, but let us know if you have problems!

**Comment by meagan1019** [comment]
Added yale.39002004911344 to new group https://test-ppa.cdh.princeton.edu/archive/?collections=37%20Test. Worked perfectly and automatically!
