### ISSUE TITLE
As an admin, I want to add one or several new items from Gale/ECCO via the admin interface so that I can add content to the site after initial bulk import without developer assistance.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#370]
## testing notes

Note: Gale API requests for larger volumes can take 20-30 seconds to return, so this could be a bit slow.

- [x] on the digitized work list in the admin site, the "add from hathi" button should be renamed to import 
- [x] the import form should require you to choose whether you are importing from HathiTrust or Gale
- [x] hathitrust import should work as it did before (test a variety of things including expected errors — invalid ids, etc)
- [x] gale import should work similarly to hathitrust import; test you can successfully import a work
- [x] newly imported work should have a log entry documenting when and how it was created
- [x] if you try to import an invalid gale id, it should be reported in the results list

## dev notes
Should work similarly to what we implemented for #278 and use gale api & import code from #369

- [x] populate gale digitized work record id and volume from api field instead of local lookup
- [x] remove local lookup code and data
- [x] add required source choice to form for sources that support import
- [x] revise view to use appropriate input according to the selected source
- [x] rename add button link on digitized work list view
- [x] extend/generalize hathi importer utility class for equivalent gale import functionality & reporting
- [x] adapt logic from gale import script as needed

**Comment by rlskoeser** [comment]
Removing this feature from the milestone and moving to the icebox, since this is dependent on Gale adding ESTC id and volume information to their API, which won't be complete during the currently scheduled development time.

**Comment by mnaydan** [comment]
Generalized form looks great. 

All my tests for adding works from HathiTrust passed. Tested adding a single ID, multiple IDs, including ark:/ IDs, invalid IDs, and already in PPA IDs. All returned expected results. 

My test for adding a new work from Gale as you anticipated returned a MARC record not found error. I also tried adding an invalid ID from Gale and it generated a 500 error - not sure if that's because of the MARC record issue or something else. 

I believe that's all I can test for now but LMK if I missed something.

**Comment by rlskoeser** [comment]
@mnaydan this is super helpful, thank you. I'm relieved to hear I haven't broken any of the HathiTrust import functionality with my refactor! It sounds like maybe there's a Gale API error I'm not catching properly; I'll check that when I fix the missing marc data.

**Comment by mnaydan** [comment]
Retested interface and various IDs from Hathi as documented above and all passed. For reference here are IDs I used:
- hvd.32044106426927
- coo.31924003216052
- uiug.30112009769222
- uc1.31210001538667
- uc2.ark:/13960/t9959dk18
- loc.ark:/13960/t7qn66x71

Invalid IDs: 
- hvd.32044106426927999
- uc2.ark:/13960/t9959dk18ft
- loc.ark:/13960/t7qn66x710o

Already in PPA
- mdp.39015003633594
- loc.ark:/13960/t0jt08550

Adding a Gale ID initially generated a 500 error but RSK fixed this by moving the marc records to the right place and resetting the permissions. 

Second attempt at adding new Gale works succeeded. I tested adding one ID (CW0106164956), multiple IDs (including CW and CB) (CW0100716186, CW0101863745, CB0131069855) and an invalid ID (0131069855). Invalid ID generated the message "Item forbidden (could be invalid id)." 

Log entries for newly added items are available via history button on item detail page. 

Metadata correctly populated admin pages and item contents was keyword searchable on frontend.
