### ISSUE TITLE
As an admin, I want a way to suppress items in bulk from the admin digitized works list so that I can manage the content if an agreement for content expires.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#371]
## testing notes
In django admin, on the digitized works list view, select multiple records and choose the 'suppress' action, and then hit 'go'. 
- [x] You should see a message indicating how many records were suppressed
- [x] record status for each should be changed from public to suppress (can check either the list view or edit view)
- [x] the items you suppressed should be removed from the public search

Test a second time, selecting a mix of public and suppressed works:
- [x] The message should report that it skipped the records that were already suppressed.

## dev notes
[custom admin action](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/actions/#adding-actions-to-the-modeladmin) for `DigitizedWork` to set status to suppressed — our use case is very close to the example in the documentation

**Comment by mnaydan** [comment]
Tested with Bysshe - 30 total combined records, suppressed 18 records (all ECCO) successfully. I can confirm I received suppress message with number, and status changed on both list and detail views.

Took a few moments but records appear removed from public search (tried searching in keyword, title, and author fields, and only 9 HT records appeared as expected (remaining 3 are Shelley)).

Tested again with a mix of new and suppressed works (tried once with all ECCO, once with mix of ECCO and HT). Functionality and message accurate both times. I can confirm newly suppressed items from both attempts also removed from public search.
