### ISSUE TITLE
As a user, I want to search and browse digitized volumes across all sources so that I can find any materials in the archive, whether from HathiTrust or Gale/ECCO.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#372]
## dev notes
Once Gale/ECCO import and indexing is implemented, this should work with no additional effort. Creating to track and test explicitly.

**Comment by mnaydan** [comment]
Tested keyword search with a variety of search terms (e.g., "pindarick ode," "epithalamiums," "harp," "heroic couplet," "reliques of ancient english poetry") and some Boolean searching (pyrrhic AND iambick, Milton AND sonnet). Yields both ECCO and HT works, which seem accurately organized by relevancy as far as I can tell. 

Some trouble with ECCO results appearing for title/author searches ("art" and "Bysshe" worked, but "reliques" and "Percy" didn't)--but I'm assuming this has to do with the missing MARC records? @rlskoeser if you can confirm, I can close.

**Comment by rlskoeser** [comment]
@mnaydan probably related, but I'm ok with keeping it open so you can test again once we're pulling metadata from MARC records.

**Comment by rlskoeser** [comment]
@mnaydan is this one resolved now that we have MARC records?

**Comment by mnaydan** [comment]
@rlskoeser yes, thank you for reminding me. Tested again with Percy.
