### ISSUE TITLE
As a user viewing keyword search results, I want to see a few text snippets from the full text of a works from Gale/ECCO so that I can see how my search terms are used in context.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#373]
## dev notes
Once Gale/ECCO import and indexing is implemented, this should work with no additional effort. Creating to track and test explicitly.

**Comment by mnaydan** [comment]
@rlskoeser it looks like for both ECCO and HT content for items with 2+ hits, it's only showing one thumbnail and the text snippet extends across where the other thumbnail/snippet should be. I'm not sure if this is related to the fix you did on #375.

**Comment by rlskoeser** [comment]
@mnaydan could you share some example search terms that I can use on both test and production?

**Comment by mnaydan** [comment]
@rlskoeser omg it was my window size (facepalm). Ignore me. But I guess I discovered a weird bug, that if your window is small and you come across a search result with only two hits, you won't see that there's a second hit.

**Comment by mnaydan** [comment]
That's unrelated to this issue though and text snippets look great, function as expected. Tested with variety of search terms across CB/CW items.

**Comment by rlskoeser** [comment]
@mnaydan wow, good catch! It's switching to the mobile view (single thumbnail) but not displaying the number of total matches. Should we just always display the total number of matches, even if there are only 1 or 2? I don't remember why we decided not to show the total for 1-2 results.  Do you want to open a bug to track it?

**Comment by mnaydan** [comment]
@rlskoeser sure, will do. It makes sense to me to always display total number, and that seems like an easier fix?

**Comment by rlskoeser** [comment]
@mnaydan yes, that sounds straightforward to me. Thanks
