### ISSUE TITLE
As a user, I want to view a page for content from ECCO in Gale Primary Sources by clicking its thumbnail or page number in a search result so that I can quickly and easily see my search result in its full context.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#374]
## testing notes
Use keyword search and to get page matches and test clicking on both thumbnail image and page number (they should work the same). Test that it works correctly for both Gale and HathiTrust content, and test on both the main archive search and the search within a single document.

## dev notes
equivalent to #101 for HathiTrust materials; not sure if we know yet how to construct this link, but the Gale folks are eager to help us and will likely respond quickly if we need more information

May require revision to `page_url` template tag, which is currently specific to HathiTrust. If we don't revise, the template tag should be renamed for clarity.

**Comment by rlskoeser** [comment]
Decreasing points from 2 to 1 — this was simple to implement once we get some help from Gale on how to construct the link.

**Comment by mnaydan** [comment]
Tested on main page and search within volume detail page with CW0110416515 and CB0130649164. Thumbnail and page number links work!

Majority of HT items I tested work as expected on main and detail pages. Of course I stumbled upon a needle in the haystack: for wu.89003553799, the displayed snippet and page number are correct, but displayed thumbnail and links are not. Search "bruce and the spider" and it displays/links to reader page 19 (actual page 17). It should display/go to reader page 17 (actual page 15). 

But I can't find the same problem in any other volume I've tested. @rlskoeser perhaps you could quickly investigate before I close, but it could just be a fluke of the volume, I guess? I'll keep an eye on whether it could be related to the page range changes for excerpts, too...

**Comment by mnaydan** [comment]
Also just a note that frontmatter and backmatter is still not searchable. Bill had said that we could expect the API update possibly by July 25 or "near" July 2, so I'm not sure whether they are behind or we need to update something on our end.

**Comment by rlskoeser** [comment]
@mnaydan regarding front matter & back matter: we will have to re-import to get the front and back matter OCR. We should check the API first to see if the ocr text is available yet, and then we can do a test import of one of the volumes to confirm. Are you able to check the API or should I ?

**Comment by rlskoeser** [comment]
> Majority of HT items I tested work as expected on main and detail pages. Of course I stumbled upon a needle in the haystack: for wu.89003553799, the displayed snippet and page number are correct, but displayed thumbnail and links are not. Search "bruce and the spider" and it displays/links to reader page 19 (actual page 17). It should display/go to reader page 17 (actual page 15).

Probably something specific to that volume if the others are working! Does the same error happen in production? We could try re-importing it to see if that fixes anything (maybe the volume has changed since we imported it).

**Comment by mnaydan** [comment]
@rlskoeser oh okay, thanks! I know you're busy so I can probably figure out how to check the API, if you don't need it done right away.

**Comment by mnaydan** [comment]
@rlskoeser ah, good call to check production. The same thing is happening there too! Must be volume specific then. I'll close this then, because the frontmatter/backmatter is a separate thing.

**Comment by rlskoeser** [comment]
> @rlskoeser oh okay, thanks! I know you're busy so I can probably figure out how to check the API, if you don't need it done right away.

Not urgent! I think we just want to make sure it's fixed before we run the import in production.
