### ISSUE TITLE
As a user viewing an item from ECCO in keyword search results, I want to see page image thumbnails and text snippets that match my search terms so I can see how many and what kind of pages match my search terms.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#375]
## testing notes
Test with keyword search that will match on Gale/ECCO imported content. Check image and text snippet display.  (ignore the image thumbnail links — that still goes to HathiTrust because #374 has not been done yet)

## dev notes
Equivalent to #32 for HathiTrust materials.

Gale image server setup is a little different — we may need to index page image urls in Solr when we import content, if they can't be generated from other index data in a way similar to what we do for HathiTrust. We do have documentation from the Gale folks about how to request a 138x192 thumbnail image.

Template tags `page_image_url` and `page_url` are specific to HathiTrust; if they remain that way, rename for clarity. Otherwise, if it makes sense, add any needed Gale image server logic there.

This may require tweaking to image lazy loading and our local javascript that deals with HathiTrust throttling images by scaling back to lower quality versions — perhaps just a class property so that logic will only apply to images from HathiTrust.

**Comment by mnaydan** [comment]
Tested with "melopea" (only ECCO results), "Pindarick poem" (mix ECCO & HT results). Snippet and Thumbnail display for ECCO content looks and functions as expected. 

But in [mixed ECCO & HT results](https://test-ppa.cdh.princeton.edu/archive/?query=%22pindarick%20poem%22&collections=9&collections=10&collections=11&collections=3&collections=12&collections=4&collections=0&sort=relevance), HT thumbnails are broken. See screenshot. Not happening with ECCO results, only and all HT results across browsers. I hard refreshed and still broken. 
<img width="860" alt="Screen Shot 2021-06-15 at 1 34 21 PM" src="https://user-images.githubusercontent.com/22945600/122098285-a9321e80-cdde-11eb-8dbf-293050f4dff9.png">

@rlskoeser do you want me to create a separate issue to fix?

**Comment by rlskoeser** [comment]
@mnaydan no, reject this one and I'll fix as part of this issue. Sorry I messed up the HT thumbnails!

**Comment by rlskoeser** [comment]
oh wait! I might know what it is — I think I need to reindex the Hathi texts in solr

**Comment by rlskoeser** [comment]
@mnaydan ok, I reindexed all works. Would you check if that fixes the problem? If it does, I'll document it in the deploy notes.

**Comment by mnaydan** [comment]
@rlskoeser yes!  That appears to have fixed it. Thank you!

**Comment by rlskoeser** [comment]
Great. I documented the indexing step in deploy notes. Is this ready to close?
