### ISSUE TITLE
As a user, when I'm viewing an item from Gale/ECCO, I want to see the Gale identifier and link to view the item on Gale Primary Sources so that I can get to the Gale version of the document 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#376]
## testing notes
Access the detail page for a Gale/ECCO item (either from admin 'view on site' or from search results)
- [x] confirm that the external link label is "View on Gale Primary Sources"
- [x] confirm that the Gale identifier is displayed
- [x] confirm that the link takes you to the item on Gale

## dev notes
Update source link in `digitizedwork_detail.html` template with language from the MOU and login required warning as determined by designs. Existing source url and source id logic should otherwise work as expected.

**Comment by mnaydan** [comment]
Correct label, Gale ID display, and functional external link confirmed. Tested with CB and CW links, via admin "view on site" button and via search results.
