### ISSUE TITLE
As a user, I want to add a Gale/ECCO work to my Zotero library from the item page or the search results page, so that I can save references for later research or citation.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#379]
## testing notes

Test importing a gale item from list view or from detail view — it should work the same as for HathiTrust materials. Metadata will be coming from the marc records (you can confirm based on the sid in the view url).

The only exception should be the records that don't have marc records in the set we were given.

## dev notes
Builds on #36 and #35

If `DigitizedWork.get_metadata` has already been updated as part of #369, then this will likely work for the current implementation (MARC only) without further effort.

**Comment by mnaydan** [comment]
Tested with Holmes (CW0110145213) on detail view and it imported successfully. URL confirms metadata coming from MARC record:
(https://link.gale.com/apps/doc/CW0110145213/ECCO?sid=gale_marc&u=prin77918). 

Also tested importing multiple items from list view (Bysshe) and it was successful. 

Works without MARC records save as webpage (as expected).

One weird thing is that page count in Zotero doesn't match page count on our site or in ECCO? For example, the Zotero record for Holmes shows 18 pages, whereas [on our site it says 189](https://test-ppa.cdh.princeton.edu/archive/CW0110145213/). This is happening with the Bysshe too, for instance [this record is 523 pages](https://test-ppa.cdh.princeton.edu/archive/CW0115898745/) but in Zotero it says 2. @rlskoeser thoughts?

**Comment by rlskoeser** [comment]
@mnaydan good testing as always, catching the page number discrepancy! I looked at the MARC record for the Bysshe document you linked with 523 pages to check this. If I'm reading the MARC documentation correctly, page numbers would be included in the [extent subfield](https://www.loc.gov/marc/bibliographic/bd300.html) (300 a), but that can include other extent information. For the Bysshe marc record, the contents of that field is "2v", presumably indicating 2 volumes — but I guess Zotero is just taking the numeric portion.  (We could check or ask on the zotero forums if you think this is important to track down.)

This raises an interesting possibility — and also gave me an idea about how to solve #399! We've always just served out the MARC records from HathiTrust as-is when offering metadata for Zotero harvesting. Now that I've worked with the pymarc more for the Gale import, I can see that it might not be too hard to tweak the original MARC records before we serve them out. In this case, we could put in the correct number of pages (and maybe we could add the volume number, too, where that's relevant).  A potentially more important improvement is that we could set the PPA item url in the MARC record, in addition to or instead of the source url that's there now.  If we want to pursue this we should track it as a new feature. I'm not sure what the impact is since I don't know how often people use the Zotero harvesting feature; but just updating the URL before serving out the MARC record is probably not too difficult.

**Comment by mnaydan** [comment]
@rlskoeser good sleuthing! How odd. I don't know if correcting the number of pages is worth our time (the other bib info is much more important to me in Zotero) -- but adding PPA URL would be a nice feature. I don't view it as "essential" though, and I'm not sure where this ranks to you in terms of our remaining dev time. I can open up a new feature for us so we don't forget, but deprioritize it? Or do you think it would be quick enough you'd rather just do it during this cycle? 

In any case I can close out this feature since the functionality works (and I'm glad that testing this feature helped you solve the other one!)

**Comment by rlskoeser** [comment]
@mnaydan I agree it's not essential. I think tracking it on a new feature would be good, because it would be good to add down the line. Maybe we can include it in the later round of work whenever I circle back to PPA development.
