### ISSUE TITLE
Design icons that represent “excerpt” for items contained within a book, and “article” for items contained within a periodical, so that users can easily distinguish the types of items they are viewing.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/ppa-django#380]

**Comment by gissoo** [comment]
@rlskoeser @mnaydan what do you think about these two icons?

this is for the excerpt:
![excerpt-icon-v1.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/693db99b-56ab-414e-b3f7-1717c3d21103) 

-------------------------------------------------------
-------------------------------------------------------

this is for the article:
![article-icon-v1.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/28590db2-1d68-4b71-bd41-bfdc276be3a5)

**Comment by mnaydan** [comment]
@gissoo I love these! I like that they look like they are siblings and that the lines are subtle and not too bold. I think the article one is perfect. In the excerpt one I like the idea of the highlighted text, but I wonder if the yellow will be _too_ attention grabbing since the site is so cool toned and grayscale? Do you think if we made the highlight grayscale it would look redacted, not highlighted?

**Comment by rlskoeser** [comment]
These are nice! I see Mary's point about the yellow, though. Is there a color used elsewhere in PPA you could use, or would that not make any difference? (This would still be the only icon with color, right?) Other ideas: could you outline instead of highlighting, or do a use a single  vertical line in the margin instead? Or if sticking with grays, could you blur out or redact the part that is _not_ selected?

**Comment by gissoo** [comment]
@mnaydan @rlskoeser thank you for writing!! I like the idea to use grayscale! I think icons actually have to be designed that way! Thank you for your eyes, I don't know why I always like to use colors too much  :D 

I love the idea for blurring! 
I think outlining or using a single vertical line in the margin adds to the number of lines on the icon which ends up adding more detail to the icon and yet won't have as much of a visually explicit point.

But last night I remembered that I had also thought of this one, below, and then as I read your comments on grayscale and blurring I created more versions of it and revised – what do you think of these instead for the excerpt? Any of them? 


![excerpt-icon-v2a.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/f727d697-a0c1-4a22-b30f-e0f5b0feb4dd)

----------------------------------------------------

![excerpt-icon-v2b.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/b12a78df-fdad-4031-99ce-9c2f838a3c62)

----------------------------------------------------

![excerpt-icon-v2c.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/e2d71bbc-7193-431b-af95-35c749679afc)

----------------------------------------------------

![excerpt-icon-v2d.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/1fe968f9-5d8e-4030-8a93-9f3a69e3478e)

**Comment by gissoo** [comment]
@mnaydan @rlskoeser here are what they look like when blurred

![excerpt-icon-v2a blurred.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/0eb1db8a-b53a-41ae-a525-866769a4cb63)

----------------------------------------------------

![excerpt-icon-v2b blurred.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/6f95cf26-91bc-46b9-ae74-57ab432a4238)

----------------------------------------------------

![excerpt-icon-v2d blurred.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/d4b0f827-7ba3-46a4-bd8f-73d09e7deb0a)

**Comment by mnaydan** [comment]
@gissoo wow you are speedy!! I think I like the first one, not blurred? (Visually I like the last one too but I think the first one communicates "excerpt" best IMO). Curious to hear what RSK thinks.

**Comment by rlskoeser** [comment]
@gissoo the magnifying glass is too associated with search to me... I would love to see the last one (blurred) and the first one without the magnifying glass, I think those are the strongest.

**Comment by mnaydan** [comment]
@rlskoeser good point re: search! Now that you say it I agree.

**Comment by gissoo** [comment]
@mnaydan @rlskoeser you're so fast!! there was an issue with the blurred versions I uploaded, they should be correct now. 

in context, I agree that it looks like search, sigh!!! I wish it that wasn't true!!

**Comment by gissoo** [comment]
@mnaydan @rlskoeser here is what you said you would love to see, RSK – I don't know how I feel about the second one here, below, also I'm doing these in Figma, but there are some limitations on Figma that prevents me from making a better version of the second one even with using a plugin. 

![excerpt-icon-v2-original-grayscale.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/3d67b514-a0e9-4eab-b859-42254d6f1d5a)

---------------------------------------------------------------

![excerpt-icon-v2d-revised.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/ad1bebde-49c0-4d66-b30d-c8d45bd8af07)

---------------------------------------------------------------
here is the first one but with a bit of a blur on everything except the excerpt
![excerpt-icon-v2-original-grayscale-blurred.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/3d131537-7999-4032-a610-9300e0d18634)

**Comment by rlskoeser** [comment]
@gissoo I see what you mean about the second one... the sizing makes it look strange, but it might not work smaller. I think like the first one best.

**Comment by mnaydan** [comment]
@mm4CDH I like the first or last one. I like that the blur is more subtle on the last one. Do you prefer one?

**Comment by mm4CDH** [comment]
I'm fine with either first or last of these. The blur is a little confusing to me since there is already a highlighted portion, plus the blur AND squiggly lines make it a little hard for me to look at. I think one question is how small will these actually be? Will the blur / squiggle bother me on the page or will it all be too small so what really will stand out is the book & highlighted passage. I *love* the article one. Makes perfect sense to me. I agree w/Mary that they look related in a great way.

**Comment by mnaydan** [comment]
@gissoo I agree with MM that the blur may not stand out enough to be meaningful when it's sized down. Let's go with the first one! The other option MM seems to be suggesting is just the outline of the book with some highlighted lines inside but no squiggles. 

And article one approved, great!

**Comment by gissoo** [comment]
Thanks for writing. I'm not sure how much I like the one with some highlighted lines and nothing else. Here it is: ![excerpt-icon-v3-original-grayscale.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/8e094769-a8c4-44b8-adb5-5770f6bdf073)

**Comment by mnaydan** [comment]
@gissoo yup, I like the first one. Let's go with that one! Thank you so much for mocking these up, they're incredibly helpful to see!!

**Comment by gissoo** [comment]
@mnaydan @mm4CDH @rlskoeser please view the excerpt and article icons [here](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60c2893d0f31bd8a7d37414e)

In the link above I'm using 4 pages to show you what it would look like to have the excerpt and the article icons on the search results page and on the work detail view.

**Comment by rlskoeser** [comment]
@gissoo these look great to me! Have you thought about where they will fit on mobile?

**Comment by mnaydan** [comment]
@gissoo they look great to me too! Do you think we need a little caption that says "Excerpt" and "Periodical" underneath so that users are clear on what the icons signify?

**Comment by gissoo** [comment]
@rlskoeser @mnaydan @mm4CDH [here are the revised designs](https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60c2893d0f31bd8a7d37414e) with the excerpt and article icons on desktop, tablet, and mobile 

@mnaydan on your question about captions, I would strongly suggest that we don't add captions – isn't this something that the user can learn as they use it? Can we have the caption only show on hover on desktop and be there for screen readers but be invisible to sighted users? @rlskoeser 


Let me know if there are any issues here – if you're ok with everything please close the issue

**Comment by mnaydan** [comment]
@gissoo that's fine! I only suggested because I showed them to my partner and he wasn't clear on what they were supposed to signify without me telling him. But maybe this is something Meredith and I can put on an About page to clarify for our users? That seems like a simpler solution with less dev work. 

I'm going to send this issue and #367 to MM for final approval before closing.

**Comment by mm4CDH** [comment]
THESE ARE FANTASTIC I LOVE THEM!!!! I agree with Gissoo that we should put some sort of "key" elsewhere (maybe in "a guide to our new designs or our new materials" or something) because having them on the page will be too crowded!

**Comment by rlskoeser** [comment]
These look great. Yes, we can (and should) have text on hover and for screen readers. Agree we don't want to display them every time, but some orientation/intro to them somewhere would be helpful.
