### ISSUE TITLE
As an admin, I want a bulk import of MARC metadata from Gale/ECCO so that I can view and search each record by its metadata

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#389]
We want to pull the following fields from the MARC records: title, subtitle, sort title, place of publication, publisher, and pub date

**Comment by mnaydan** [comment]
@rlskoeser how is author field formatted in the MARC records? I'm wondering if it's worth pulling author, too, if it's formatted "last name, first name" so that it matches the format of the HT records.

**Comment by rlskoeser** [comment]
@mnaydan yes, planning to pull author from the MARC metadata as well — it should get us a format closer to what we've got already.

**Comment by rlskoeser** [comment]
Here's the output from the most recent run of the gale import script.  (@mnaydan I think I'm still using an old version of your CSV without the most recently corrected IDs).

I'm surprised by how many MARC records we're missing — it didn't seem like that many when I was testing, but when I ran the full import again locally I got similar results. We may need to follow up with Gale to find out what could cause this (could it be a matter of _when_ PUL purchased the marc records?)

I think the character parse errors are because I switched back to using binary MARC records instead of JSON — @mnaydan if you can think of any records with special characters to test, that would be helpful. If anything is getting corrupted we can try switching back to the JSON version of the MARC records.

```
$ ./manage.py gale_import -c /tmp/ECCO_compiled_non-excerpts_fixed_IDs_6.10.21.csv -v 0
MARC record not found for CB0132859609
MARC record not found for CW0112106158
MARC record not found for CW0111720541
MARC record not found for CW0114229753
MARC record not found for CW0114728738
Unable to parse character 0xcc in g0=66 g1=69
MARC record not found for CW0114704032
MARC record not found for CW0110970244
MARC record not found for CW0110970663
MARC record not found for CW0111406390
MARC record not found for CW0109771665
MARC record not found for CW0113390248
MARC record not found for CW0110986375
MARC record not found for CW0110004195
MARC record not found for CW0110433388
MARC record not found for CW0114905944
MARC record not found for CW0115390412
MARC record not found for CW0113836889
MARC record not found for CW0113837303
MARC record not found for CW0114032230
MARC record not found for CW0114032713
MARC record not found for CW0115236604
MARC record not found for CW0115419546
MARC record not found for CW0115420029
MARC record not found for CW0115963418
MARC record not found for CW0119571809
MARC record not found for CW0119572297
MARC record not found for CW0120106050
MARC record not found for CW0120106500
MARC record not found for CW0120576252
MARC record not found for CW0121009324
MARC record not found for CW0120209174
MARC record not found for CW0116527799
MARC record not found for CW0116528246
MARC record not found for CW0117248465
MARC record not found for CW0117333680
MARC record not found for CW0112168756
MARC record not found for CW0112558307
MARC record not found for CW0112927708
MARC record not found for CW0113057109
MARC record not found for CW0113336035
MARC record not found for CW0113336519
MARC record not found for CW0113337031
MARC record not found for CW0113337536
MARC record not found for CW0110165242
MARC record not found for CW0117289150
MARC record not found for CW0114204864
MARC record not found for CW0110667966
Unable to parse character 0x80 in g0=66 g1=69
MARC record not found for CW0117022614
MARC record not found for CW0110636874
MARC record not found for CW0113694901
Unable to parse character 0xcc in g0=66 g1=69
MARC record not found for CW0113017309
MARC record not found for CW0112375148
MARC record not found for CW0112613319
MARC record not found for CW0114850590
MARC record not found for CW0115756532
MARC record not found for CW0114265763
MARC record not found for CW0113449473
MARC record not found for CW0114721722
MARC record not found for CW0110966909
MARC record not found for CW0111124308
MARC record not found for CW0111124419
MARC record not found for CW0115498273
MARC record not found for CW0115953052
MARC record not found for CW0114828122
MARC record not found for CW0112639507
MARC record not found for CB0129094722
MARC record not found for CW0114590198
MARC record not found for CW0115702497
MARC record not found for CW0115702857
Unable to parse character 0xcc in g0=66 g1=69
Unable to parse character 0x80 in g0=66 g1=69
MARC record not found for CW0112348310
MARC record not found for CW0112348834
MARC record not found for CW0113550692
Unable to parse character 0xcc in g0=66 g1=69
Unable to parse character 0x80 in g0=66 g1=69
Unable to parse character 0xcc in g0=66 g1=69
Unable to parse character 0x80 in g0=66 g1=69
MARC record not found for CW0113652049
MARC record not found for CW0115232948
MARC record not found for CW0110975037
MARC record not found for CW0124787241
MARC record not found for CW0111162361
MARC record not found for CW0111646406
MARC record not found for CW0114894389
MARC record not found for CW0115378212
MARC record not found for CW0111185737
MARC record not found for CW0116297776
MARC record not found for CW0100721039
MARC record not found for CW0115687820
MARC record not found for CW0113483218
Unable to parse character 0xcc in g0=66 g1=69
Unable to parse character 0x80 in g0=66 g1=69
MARC record not found for CW0124737709
MARC record not found for CW0119570768
MARC record not found for CW0103274182
MARC record not found for CW0114518411
MARC record not found for CW0115462979
MARC record not found for CW0114695017
MARC record not found for CB0129117138
MARC record not found for CB0128602753
MARC record not found for CB0131704013
MARC record not found for CW0120334675
MARC record not found for CW0124749360
MARC record not found for CW0124748989
MARC record not found for CW0115984903
MARC record not found for CW0124836956
Unable to parse character 0xcc in g0=66 g1=69
Unable to parse character 0x80 in g0=66 g1=69
MARC record not found for CW0114369233
MARC record not found for CW0116719554
MARC record not found for CB0130572662
MARC record not found for CW0110724021
MARC record not found for CB0128465842
MARC record not found for CW0116770337
MARC record not found for CW0111173803
MARC record not found for CW0113482794
MARC record not found for CW0117561907
MARC record not found for CB0128277182
MARC record not found for CW0125896591
MARC record not found for CW0125630970
Error getting item information for CB132045539
MARC record not found for CB0131407349
MARC record not found for CB0131712342
MARC record not found for CB0131407895
MARC record not found for CB0129117517
MARC record not found for CW0110986839
MARC record not found for CW0113825227
MARC record not found for CW0116119464
MARC record not found for CW0111974384
MARC record not found for CW0111974989
MARC record not found for CW0114888110
MARC record not found for CW0113923438
MARC record not found for CW0115683484
MARC record not found for CW0116702915
MARC record not found for CW0116299725
MARC record not found for CW0116298721
MARC record not found for CW0116815787
MARC record not found for CW0116296895
MARC record not found for CW0116296101
MARC record not found for CW0116293725
MARC record not found for CW0116295328
MARC record not found for CW0116702026
Error getting item information for CB128058273
MARC record not found for CW0115693865
MARC record not found for CW0114894562
MARC record not found for CW0118347262
MARC record not found for CW0113617765
MARC record not found for CW0113954378
MARC record not found for CW0100161757
MARC record not found for CW0100964250
MARC record not found for CW0103878094
MARC record not found for CW0101866153
MARC record not found for CW0101866791
MARC record not found for CW0100161262
MARC record not found for CW0100166317
Error getting item information for CB110589871
MARC record not found for CW0115179207
MARC record not found for CW0115953753
MARC record not found for CW0102862950
MARC record not found for CW0102747242
MARC record not found for CW0102803994
MARC record not found for CW0102804392
Unable to parse character 0xcc in g0=66 g1=69
Unable to parse character 0x80 in g0=66 g1=69
Unable to parse character 0xcc in g0=66 g1=69
Unable to parse character 0x80 in g0=66 g1=69
Error getting item information for CB129347115
MARC record not found for CW0115383022
MARC record not found for CW0115348005
MARC record not found for CW0102294848
MARC record not found for CW0113867877
MARC record not found for CW0114448536
MARC record not found for CW0115722544
MARC record not found for CW0113726727
MARC record not found for CW0113330715
MARC record not found for CB0128515985
MARC record not found for CB0128516952
MARC record not found for CB0128516493
MARC record not found for CW0110094668
MARC record not found for CW0110094982
MARC record not found for CW0111145472
MARC record not found for CW0110163815
MARC record not found for CW0110164224
MARC record not found for CW0115526337
MARC record not found for CW0113056418
MARC record not found for CW0113379207
MARC record not found for CW0112646748
MARC record not found for CW0114853467
Error getting item information for CB125450132
MARC record not found for CW0124563996

Processed 1,182 items for import.
Imported 1,177; skipped 0; 5 errors; imported 385,155 pages.
```

**Comment by mnaydan** [comment]
Some special characters are getting corrupted: accented e ("Dubos, abb©♭ (Jean-Baptiste), 1670-1742") and ash ("the fables of ©sop") are the most frequent culprits. Ampersand, parenthesis, asterisks are holding. It's only a handful (maybe 20?), so I feel badly having you switch again... @rlskoeser let me know what you think.

Other than that, searching by metadata in backend and frontend works great (for the items that have MARC records). I tried a bunch of fielded searches in keyword (source ID, subtitle, pub date, pub place, publisher), and a bunch of searches in author and title fields. 

I reached out to Ray today about the missing MARC records.

**Comment by rlskoeser** [comment]
Thanks for checking the special characters, I was afraid of that. It isn't a huge effort for me to switch to JSON and see if that resolves these problems. (I already wrote code that can do it, just have to get it back from the git history!)

**Comment by rlskoeser** [comment]
@mnaydan updated test with a fresh import of Gale content from your most recent spreadsheet (6.22.21).

I did get a few errors on missing MARC records; LMK if you want me to investigate these further:
MARC record not found for CB0126228345/N009409
MARC record not found for CB0132944166/T078405
MARC record not found for CB0131704013/T032596
MARC record not found for CB0131389492/T032596
MARC record not found for CB0132926890/N034700
MARC record not found for CB0130984232/N002639
MARC record not found for CB0132774697/T053828
MARC record not found for CB0132841903/N029902
MARC record not found for CB0132652546/T097528
MARC record not found for CB0126231877/T005538

**Comment by mnaydan** [comment]
@rlskoeser blarg. Thank you. Let me look real quick before you investigate.

**Comment by rlskoeser** [comment]
@mnaydan for testing, in addition to checking the character encoding problem, please also check that the ESTC id is set as the record id and volume # is set for items that are multivolume.

**Comment by mnaydan** [comment]
@rlskoeser all those IDs are correct and contained in both my and Ray's spreadsheet. (Only difference is that the title for CB0126231877 should be "The dunciad. An heroic poem. In three books" but I don't believe you're using title from the spreadsheet.) I'm not sure what would be causing them to error. Might be good for you to investigate.

**Comment by rlskoeser** [comment]
> @rlskoeser all those IDs are correct and contained in both my and Ray's spreadsheet. (Only difference is that the title for CB0126231877 should be "The dunciad. An heroic poem. In three books" but I don't believe you're using title from the spreadsheet.) I'm not sure what would be causing them to error. Might be good for you to investigate.

Thanks for checking — I meant to point out and forgot, I can tell from the error message that we _are_ getting an ESTC id number for each of those. The error is happening when I try to load the MARC record for that id. I also notice now that they are all CB numbers — so all ECCO2, right? Maybe I can generate a list of all 001 identifiers in the MARC records we were given so we can check and ask Ray if necessary.

**Comment by mnaydan** [comment]
@rlskoeser they are all CB / ECCO2, yes. I don't know what 001 identifiers are but that sounds good to me. Is it possible MARC records don't exist for those items?

**Comment by rlskoeser** [comment]
I'm wondering if somehow they were added to ECCO2 after Princeton purchased the MARC records that we're working from — I don't know how Gale operates enough to know if that's plausible or not!  (001 identifier is the primary id in MARC, and corresponds to the ESTC ids that Ray gave us to use)

**Comment by mnaydan** [comment]
Special characters fixed! 
ESTC is set as record ID in backend. Volume number appears for multivolume works on frontend and backend.
Re-tested search by metadata on frontend and backend (author, title, and fielded searches in keywords) and it works well! 

I'm going to keep open until we get answers from Ray about the 10 missing MARC records, though.
