### ISSUE TITLE
As an admin, I want item type and book excerpt/article metadata included in admin CSV exports so I can review all information in the system

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#394]
## testing notes
download CSV data and confirm that it includes the correct content for the new fields (as well as all previous fields): 
- [x] item type
- [x] book/journal title
- [x] original page range
- [x] digital page range

## dev notes
revise existing csv export to include item type, book/journal title, page range, image sequence range

**Comment by mnaydan** [comment]
All new fields are included, as well as old fields. Old subtitle is still showing up for excerpts, but if you fix this on #395 it should be fine.
