### ISSUE TITLE
As an admin, I want the option of importing two different sections from the same HathiTrust work so I can include multiple articles or chapters from a single journal issue or book.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#396]
## testing notes
You should be able to test this functionality by changing existing records and adding a new one. 
- Choose an existing non-excerpt digitized work to test with. Make a note of the public url for this work because you are going to need it for testing.
-  Edit the digitized work you chose to turn it into an excerpt (for the purposes of this test, the only field that really matters is the **page range (digital edition)**). For convenience, use "Save and continue editing."
- [x] Use the "view on site" button to view the public version of the item you modified. Check that the url is based on the source id *plus* the first page number of the excerpt.
- [x] Test the public url of this work that you saved before converting it to an excerpt: it should redirect to the new url with the page number.
- Manually add another excerpt from the same source. (For the purposes of this test, the fields that matter are **source id** and **page range (digital edition)**). Save the record.
- [x] Test the public url of this work that you saved before converting it to an excerpt: it should now return a 404 not found, since there is more than one excerpt from the original work.

## dev notes
- [x] Revise database unique requirements for `DigitizedWork`  — previously source id was required to be unique; will need to be  the combination of source id and page sequence that is required to be unique together.
- [x] Revise work identifier in index data so that different articles from the same source can be distinguished
- [x] revise url for public document detail page so it uses source id + start page for excerpts
- [x] implement see other redirect from old url to excerpt url

**Comment by mnaydan** [comment]
@rlskoeser I don't know if this messes you up but it is not always just 2. I did a quick check and I _think_ the most we have would be 3.

**Comment by rlskoeser** [comment]
@mnaydan question for you while I'm thinking about it (in relation to our recent conversation on #393, about converting existing records from full to excerpt or reimporting) — if we need to allow multiple excerpts from the same source, then I will need to change the URLs on the PPA site to make sure they are unique. (Right now they are based on source id.)  

I was thinking of using source id combined with starting page number for urls for excerpts. Can you think of any case where that would not be unique? Also, can you think of any reason the starting page number would change after you've added something (i.e., would this be a stable identifier)? If you have any ideas for something different, let me know.

**Comment by mnaydan** [comment]
@rlskoeser oh, good point. That makes sense to me. In one case, the end page of one excerpt is the same as the start page of the next excerpt (e.g., 459-466 and 466-479) - but the starting pages are different, so they'd still be unique. After looking over the cases I have, I think it should work.

Starting page _should_ be a stable identifier, but I suppose the starting page could change if we caught a mistake in the currently marked page range (I've been spot checking and hopefully there aren't any, but, human error means it's possible...)

I think that both of these things would be rare enough that using start page as a stable identifier should work.

**Comment by rlskoeser** [comment]
@mnaydan thanks for confirming — I agree, that's a rare enough case we can live with it.

I'd like to implement logic so that current records that get converted to excerpts will redirect to the new url. Does it sound reasonable to have it redirect to the excerpt with the lowest page number if there are multiple excerpts from one document? Or should it not redirect if there are multiple excerpts from one source?

**Comment by mnaydan** [comment]
@rlskoeser will there be only 1 record, even if there are multiple excerpts from a source? 

For us to have correct metadata that corresponds to each excerpt, we'd need to have multiple records, right, and each could have it's own URL with the starting page number?

Here's a screenshot of an example case:
<img width="1174" alt="Screen Shot 2021-06-23 at 4 30 37 PM" src="https://user-images.githubusercontent.com/22945600/123164090-7a502400-d440-11eb-99de-70b248737837.png">

**Comment by rlskoeser** [comment]
each excerpt needs to have its own record — so yes, multiple records and each needs a distinct url

(have we thought about linking them to each other? does that matter?)

**Comment by mnaydan** [comment]
@rlskoeser Ok so we are on the same page with that! I'm sorry, I think my brain is being slow, I'm not understanding the redirect/conversion logic :/

So using the screenshot above as an example, there's currently 1 "Transactions and proceedings" record in the PPA. That record would be converted to the lower page number of the two (so mdp.390150...p81) for the Shipley, and then a duplicate (but not really because unique URL) record would be created with mdp.390150...p145 for the Sturtevant?

I don't think we need to link them - wouldn't they be linked via record ID anyway? Thank you for your patience with me!

**Comment by rlskoeser** [comment]
@mnaydan sorry for being unclear! You said there are a lot of records in the system now that need to be converted to excerpts. If anyone has the detail page for that work bookmarked in PPA (or cited it in an article), my assumption is that we want them to automatically be redirected to the new url for the excerpt. I can send an http status a code that says "see other" rather than "moved permanently", since it isn't exactly the same resource. If there are two excerpts for the same source, we can either redirect to one of them or return a not found or gone message.

For the record id — I don't think we currently do anything with that on the public site. I don't know how important it is for a user to know if we have other excerpts from the same source (or other volumes of the same work, for that matter). Since we don't have a feature like that right now, we'd probably better not try to introduce it at this point (but could be something to think about for later).

**Comment by mnaydan** [comment]
@rlskoeser ohh! I didn't realize this was for bookmarking/citing. Thanks for explaining. I think redirecting is fine if there's only 1 excerpt per source, but if there are 2+ excerpts, I think it should return a not found or gone message. (Often the excerpts are wildly different from one another, totally different articles and authors, so we can't assume it's the lowest number one that the bookmarker intended.) 

For the record ID - I don't think we need to alert our user that we have other excerpts from the same source (and I agree with you about not introducing it at this point) but Meredith and I can think about it for later.

**Comment by mnaydan** [comment]
Tested with mdp.39015060429357, public URL https://test-ppa.cdh.princeton.edu/archive/mdp.39015060429357/.

After changing to an excerpt URL correctly changes to: https://test-ppa.cdh.princeton.edu/archive/mdp.39015060429357-p212/.

Problem 1: original URL does NOT redirect to the one with the page number. I just get the original record.

Problem 2: I couldn't add another record via the "Add from HathiTrust" button because it skips the record (this seems logical). However I also couldn't add another record via the "Save and add another" button from the record detail page. After filling out the form it returns an error: "Changing source ID for HathiTrust records is not supported." I put in the source ID mdp.39015060429357 and the page number 269 (page range for previous excerpt was 212-218). This problem blocks the rest of my testing.

**Comment by mnaydan** [comment]
@rlskoeser wisely (as always) suggested I add the record as "Other" and that works. I get a new URL with page number as expected: https://test-ppa.cdh.princeton.edu/archive/mdp.39015060429357-p269/.

However public URL still directs to the original record page. No 404.

**Comment by rlskoeser** [comment]
@mnaydan would you mind testing the redirect again? The redirect will only happen if there is a single excerpt for the source id that is no longer available as a full work. Right now there are two excerpts with source id `mdp.39015060429357` — from your notes it sounds like you added the second one after you tested the first thing, but I'm having trouble duplicating this and the logic in the code looks right to me.

FWIW, the query to look for excerpts with the same source id doesn't filter on status; should it only look for public / non-suppressed record?

**Comment by mnaydan** [comment]
URL for original full work: https://test-ppa.cdh.princeton.edu/archive/njp.32101023869397/

Changed to article: new URL https://test-ppa.cdh.princeton.edu/archive/njp.32101023869397-p220/. 

@rlskoeser I had to hard refresh to get the original URL to redirect. I'm working in Chrome. I figured it out by trying it in FF and Safari, which both redirected. Works in Chrome if you hard refresh.

**Comment by rlskoeser** [comment]
Ah, interesting that Chrome caches that without looking for a redirect. That makes sense, I guess, and isn't a real problem for us.

Does this pass testing then, or is there anything I need to address?

**Comment by mnaydan** [comment]
Passes testing. We can close. Having trouble thinking thru the logic of your status filter q at the moment. Whatever you think is best.
