### ISSUE TITLE
As a user, when I'm looking at the details for an item I want to see an indicator if it's an excerpt or article so I understand the content better.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#398]
## testing notes
**design links**
[excerpt + article icons](https://zpl.io/VQJdWpA)
- [x] article icon should display for articles
- [x] excerpt icon should display for excerpts
- [x] book or journal title should display when set, with appropriate title based on type
- [x] original page range should display when set
- [x] link to item in HathiTrust should go to the first page in range 

## dev notes
- [x] include excerpt/article icons on document detail page based on item type
- [x] include additional metadata on document detail page based on item type: book or journal title, original page range
- [x] link to view item in HathiTrust or Gale should link to the first page in sequence for the excerpt

**Comment by mnaydan** [comment]
Everything above looks good, love how journal/book title on detail view changes automatically depending on content type. Same icon problems as I noted on #397 but we can track them there.

FYI: The HT link to first page works on frontend, but on backend it doesn't. But it works "as a user," so I can track that as an admin issue elsewhere...
