### ISSUE TITLE
As an admin, I want a bulk import of HathiTrust materials so that previously identified and downloaded data can be added to the system.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#4]
## Notes for testing
* Imports basic metadata into the Django database for admin management and imports metadata and page full text into Solr for search.
* Update 12/7 - import now includes publisher and publication place from the MARC record.
* Note that currently the import does not strip any trailing punctuation from the author, publisher, or publication places.

**Comment by mm4CDH** [comment]
Rebecca, it might be helpful to know what is in the Marc record that we can choose from -- not that we'll want everything (I promise!) but I don't want to ask for a column that you can't easily import.

**Comment by rlskoeser** [comment]
@mm4CDH that is a great point.  I am definitely not a MARC expert; in fact, I've kind of avoided learning it to some extent because it is so messy and cumbersome. I also don't know how consistently fields are used across institutions, although if we stick with common fields we should be fine.

Here is a document on [commonly used MARC fields](http://www.loc.gov/marc/umb/um07to10.html)  which was referenced from [pymarc](https://github.com/edsu/pymarc), the python library I'm using.  If you scan the green headings on the commonly used fields document you should get some idea.  I am wondering if we should use volume and edition information from MARC rather than using the Hathi enumcron field.

We should also beware of adding too much at this point - let's try stick to "basic" metadata, however we want to decide to define that.  What fields do we need to generate a citation for a work?Does that give us a guideline for basic metadata?

**Comment by rlskoeser** [comment]
Cleared everything out (database and solr) and ran a fresh import with the latest code.  Here's the script summary output:
```
$ time ./manage.py hathi_import -v 0 --progress

100% (5007 of 5007) |###################################################################################################| Elapsed Time: 1:05:41 ETA:  0:00:00
Processed 5,007 items for import.
Added 5,007; updated 0; skipped 0; 0 errors; indexed 1,753,603 pages.

real	65m46.085s
user	9m55.823s
sys	0m21.631s
```

**Comment by mm4CDH** [comment]
I think these fields seem fine to me now. I'm slightly concerned, now that I see it, that enumeration chronology might confuse someone down the road but Meagan and I know what it means (since Hathi "volumes" are tattooed into our brains. Depending on what we decide to do about finding "earliest" or "certified" editions I think it's important to have this information visible to an admin even if we don't put all of it up on the site. Thank you for adding it.

**Comment by rlskoeser** [comment]
@mm4CDH thanks for the feedback. I have a similar concern about the enumcron field - it seems very Hathi-specific, and would be nice to figure out how to generalize to something that is more intelligible and will make sense for other content.  I looked briefly at the marc record to see if there was an obvious place to pull the same information, but it wasn't immediately obvious and I didn't think I should spend too much time on it at this point.

I agree we'll probably end up revisiting it later when we look at better edition information; by then maybe we'll have some ideas about how we want to change this.
