### ISSUE TITLE
Mockup: digitized work detail page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#40]
### zeplin views
_individual work_: [L](https://zpl.io/2Gz5L6Y) / [M](https://zpl.io/bAvMzPP) / [S](https://zpl.io/VQqwrzA)
### notes
- is the correct set of metadata for a work displayed in the table?
- is it responsive?

**Comment by thatbudakguy** [comment]
## testing notes
This is missing a few pieces because we don't have the data to feed them yet, but most of the metadata is there.

It should be responsive, if not exactly to spec. Search doesn't do anything yet.

**Comment by xinyil** [comment]
- universally, there are 100px spacing between the last item on the page and the footer on L and M. On S it's 50px.
- if we're adding lines between items, it should go all the way to the label title
- the line appear to be thicker on S

**Comment by thatbudakguy** [comment]
- made spacing uniform (note that if you resize the window while viewing it won't work - this is because I have to manually push the footer to the bottom of the page. it will work when you reload the page at a particular size though)
- removed lines between items

**Comment by jabauer** [comment]
I see the following metadata categories (aside from title)
* Secondary Title
* Year of Publication
* Author(s)
* Publisher
* City
* PPA Collections (as buttons)
* View HathiTrust Volumes

Lines are still present in iOS 11.3.1 on iPhone 6 and iPad Pro, but not on iOS 11.2.5 (iPad Air 2)
Lines double up temporarily when resizing window on laptop see following on 
* MacPro 15" Retina mid 2014 running OSX10.13.4 with following browsers
	* Chrome v66.0.3359.139
	* Safari v11.1

![image](https://user-images.githubusercontent.com/243947/40257283-a1c491e4-5abb-11e8-9104-45b90c06f5c9.png)


Lines don't double up while resizing with Firefox v57.0.4 on MacPro 15" Retina mid 2014 running OSX10.13.4

**Comment by thatbudakguy** [comment]
I wonder if this is built-in safari styling for tables?? Super weird. thanks for testing @jabauer

**Comment by thatbudakguy** [comment]
Safari table issue is now tracked on #87
