### ISSUE TITLE
As a user, I want to search within a book excerpt or article so that I can see more than two results for my search terms in context.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#401]
## testing notes
- [x] Test searching within a single document for an excerpt
- [x] Test at least one set of excerpts from the same work: you should only see results that are in range the particular excerpt you are searching, not any of the others

## dev notes
Existing single-document search should work on excerpt content, but we'll probably want to add a filter on the solr query to make sure we only pull back pages within range for the current excerpt.

**Comment by rlskoeser** [comment]
this was trivial based on the excerpt functionality that had already been done, revising from 1 point to 0

**Comment by mnaydan** [comment]
I tested about a dozen random records - article, excerpt, ark id, single page, discontinuous page, multi-excerpt from volume, shared page - everything looks good! Also tested changing page range in backend and reindexing worked - could search for content on new page, and newly out of range page didn't show up (as expected).
