### ISSUE TITLE
Mockup: collections list page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#41]
### zeplin links
collections list: [L](https://zpl.io/bW48p41) / [M](https://zpl.io/a3vLveW) / [S](https://zpl.io/a8Zg4kK)
### notes
- cards are a component style that will come in the next iteration, so they won't look much like the spec for now.
- is it responsive?
- do the card links work?
- is there anything that looks out of place?

**Comment by thatbudakguy** [comment]
## testing notes

some collections don't have descriptions yet (dictionary, pronunciation guides) and no items are associated right now so the counts will be zero. this might make the sizing of the cards a little weird temporarily.

a lot of the styles on this page will probably come together when I customize the semantic UI card component, which is what I'm using for the cards. for now, it should interact correctly, spacing should be more or less OK, and it should be responsive.

@xinyil do you like the "lift" hover for the cards? it's the default for semantic UI but of course we could change.

**Comment by xinyil** [comment]
@thatbudakguy we could make the transition more smooth and it's nice. we'll have to think how it works on the home page.

In Safari the text on card is experiencing some weird flashing. looks like something related to anti-alias setting? did not occur in Chrome.

**Comment by xinyil** [comment]
also I think dictionaries and pronunciation guide shouldn't be here - they're not curated collection. we'll check with the team in the meeting.

**Comment by rlskoeser** [comment]
Excluding dictionaries and pronunciation guide now being tracked under #76

**Comment by thatbudakguy** [comment]
@xinyil I noticed the flashing as well...I think I'll address it when I do the component styles for the card to prevent that default behavior.
