### ISSUE TITLE
test indexing on PUL infrastructure

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#420]
current index time is often a blocker for development. as part of the migration to PUL infrastructure, we want to see if we can improve the index time — maybe by increasing the number of available cores on the VM, or provisioning a separate VM to run the index process. It's possible that having a dedicated app VM will simply resolve the problem on its own, since we won't be sharing space with solr/the database/other QA apps.

**Comment by rlskoeser** [comment]
We did this as part of the PUL migration last iteration.
