### ISSUE TITLE
As an admin, I want the Source id link in list view to go to the first page of the excerpt for articles and excerpts

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#427]
RSK says we have template tags for generating urls for hathi and gale works that link to the first page, but we're not including this feature in this release. 

## testing notes
- [x] source link for full works continues to work as before
- [ ] source link for hathi excerpt links to first page
- [x] source link for gale excerpt links to first page
- [x] record with no source url has source id only and no source link

**Comment by rlskoeser** [comment]
@mnaydan I ended up fixing this because I thought it was broken (it was, sort of, although may have been more of a data error)

**Comment by mnaydan** [comment]
This looks good except for the Hathi IDs. The link goes to a [HathiTrust "Application Error" page](https://babel.hathitrust.org/cgi/pt?id=https://hdl.handle.net/2027/uc1.ax0002627784;view=1up;seq=26). It appears the issue is the URL syntax? This is what the URL looks like:

`https://babel.hathitrust.org/cgi/pt?id=https://hdl.handle.net/2027/uc1.ax0002627784;view=1up;seq=26`

If you take out the `https://hdl.handle.net/2027/` so that it becomes `https://babel.hathitrust.org/cgi/pt?id=uc1.ax0002627784&view=1up&seq=26`, it resolves and behaves as expected. 

Also, I don't know if it matters but the first URL I cite has a semicolon after the Hathi ID that transforms into an ampersand in the resolved URL. This doesn't appear to get in the way of functionality.

**Comment by mnaydan** [comment]
Fixed!
