### ISSUE TITLE
As a user, I want to see the actual rather than digital page number on keyword search results of Gale/ECCO items so that I can more accurately cite items.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#446]
## testing notes

Import a new record in #370 and then check on the public site how the page numbers display; if possible, test a record that you know has `folioNumbers` set in the Gale API (some of them don't have it set, others seem to just be set based on the digital image number)

## dev notes
update indexing to use new page number from updated api

- [x] update `gale_page_index_data` method to set `label` from new Gale API `folioNumber` field
- [x] update test for this method to match

**Comment by mnaydan** [comment]
This appears correct! I tested with CB0131069855 with keyword "salubrious," which appears on digital page range 118 but shows a physical page number of 4. On main search and search within volume pages the result correctly labels the thumbnail p. 4. Double checked with CW0101863745 and search "Sicily" (digital page 10, actual page 7) and the display was also correct.
