### ISSUE TITLE
Adding new items from HathiTrust broken for some items

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#447]
There are two separate issues. For some IDs, it is failing to sync data (uc1.b3514895; uc1.b3514895; FYI, other uc1 IDs worked). Others generated 500 error and then appear in database but without record ID and source URL (mdp.39015043572422; mdp.39015060430082; FYI, other mdp IDs worked).

## testing notes
- [x] test mdp.39015060430082 or others that were resulting in 500 error to see if import works now

## dev notes
- [x] handle type error on pubdate conversion to integer when it is not set 
- [ ] investigate rsync error 

--- 

pub date conversion error stack trace from logs in qa on attempted import of mdp.39015060430082:

``` File "/var/www/ppa-django/ppa/archive/models.py", line 665, in metadata_from_marc
    field_data["pub_date"] = int(pubdate)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by rlskoeser** [comment]
According to the logs, the 500 error on mdp.39015060430082 is because the publication date is not an integer and we're trying to treat it as one. Looking at the marc record for that one, I think it's coming back as `None`, which indeed can't be converted to an integer. I can add error handling for that case; kind of surprised it hasn't come up before! 

It looks like the bib api for this record has a publication date in the simple JSON record, I wonder why there isn't one in the MARC record?
https://catalog.hathitrust.org/api/volumes/full/htid/mdp.39015060430082.json

**Comment by mnaydan** [comment]
I suppressed and deleted mdp.39015043572422 and mdp.39015060430082 to get them out of the database, and then I was able to successfully reimport them. No 500 error, and the metadata imported successfully, so I guess these cases are fixed!

**Comment by mnaydan** [comment]
@rlskoeser I think these are fixed, too, right, so we can close this issue? I'm not sure if the rsync issue was the same as we had in #481, but uc1.b3514895 is successfully in the database.

**Comment by rlskoeser** [comment]
@mnaydan I know we fixed one of the problems before; maybe it was the same rsync error and I just didn't know. If you don't have any other records you need to import that are causing problems, seems like we can go ahead and close.

How nice to see that the migration resolved some of these problems!
