### ISSUE TITLE
upgrade to django 3.2

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#449]
## retest notes
- [x] test admin add work to a collection to confirm it works and does not result in a 500 error

## dev notes
- [x] upgrade django 3.2
- [x] upgrade wagtail 2.15
- [x] update staging server to python 3.6
- [x] update staging deploy to python 3.6
- [x] remove grappelli

after testing:
- [x] trying to add a work to a collection on the backend results in a 500 error

**Comment by mnaydan** [comment]
Looks good! I tested adding work(s) to one and multiple collections through the bulk add feature and through the individual edit form. All passed!
