### ISSUE TITLE
Styles: editorial post

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#45]
## testing notes
**designs**
[desktop](https://zpl.io/aXkRDrx) / [tablet](https://zpl.io/aXkRZkM) / [mobile](https://zpl.io/bA4397P)

**Comment by thatbudakguy** [comment]
waiting to discuss this at PPA meeting to see how much is in scope for it (footnote styles, image captions, etc).

**Comment by thatbudakguy** [comment]
"by" has been removed.

**Comment by mnaydan** [comment]
Looks good, thank you!
