### ISSUE TITLE
As an admin, I want to see work clusters on digitized work list view so that I can search for and see collapsed versions at a glance.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#455]
## testing notes
- [x] cluster should be included on digitized work admin list view
- [x] cluster should be included in digitized work admin filters on the right side

also test cluster admin:
- [x] can access cluster list view to browse clusters
- [x] can see count of works in each cluster
- [x] clicking count takes you to filtered digitized work list view
- [x] you can edit clusters, and cluster edit includes inline view of associated digitized works

**Comment by rlskoeser** [comment]
@mnaydan let me know if you have a preference for where this should go in the current order.

**Comment by mnaydan** [comment]
All of the functionality in the notes looks great! The placement of the cluster column in list view is perfect. I was able to edit and delete clusters from the change cluster form. I was able to filter by cluster from the digitized works page (so helpful!). I love that clicking on the count takes you to a filtered view of the digitized work screen.
