### ISSUE TITLE
As an admin, I want to see and edit work clusters so that I can collapse and uncollapse texts after developer-assisted import.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#456]
## testing
- [x] cluster should be listed and editable on digitized work edit form
- [x] should be able to use autocomplete to find and associate with existing clusters
- [x] should be able to create new clusters either from + button in digitized work or going to cluster list view
- [x] should be able to remove associated cluster (use the x button in the autocomplete)

**Comment by rlskoeser** [comment]
@mnaydan same question: preference for where on the edit form this should be listed?

**Comment by mnaydan** [comment]
The editing/adding functionality works great on the "Cluster" form and on the record detail form. The autocomplete is great. The placement on the record seems good to me - makes sense to put it by collections. The "Cluster with this Cluster ID already exists" validation when creating a new cluster is super helpful, thanks for thinking of that. 

I'm not sure how the records are sorted on the cluster page by default (seems random?), but trying to sort them A-Z/Z-A works when you click on "Cluster ID" header. Trying to sort by count by clicking "Number of works in this cluster" generated a 500 error.

**Comment by rlskoeser** [comment]
@mnaydan ordering should be fixed in admin now for clusters (default sort by name, sort by count should work properly)

**Comment by mnaydan** [comment]
Yes - default sort is now by name, and both sorting buttons are working as expected. Thanks!
