### ISSUE TITLE
Snippet: search result pagination controls

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#46]
### zeplin links
components [All](https://zpl.io/adMGzER)
search page [L](https://zpl.io/adM1x65)
### notes
- check behavior with small and large sets of search results
- check behavior when you are on a page at the beginning, middle, and end of search results

**Comment by rlskoeser** [comment]
@xinyil preliminary pagination is on the test site. Would you take a look and check that the logic is implemented the way you wanted?

**Comment by xinyil** [comment]
just took a look - it works well!

**Comment by thatbudakguy** [comment]
now with responsiveness and an items-per-page display! ✨

**Comment by jabauer** [comment]
Buttons work and move you to a new set of results. Buttons in the middle show first and last page.

**Comment by jabauer** [comment]
Shows that you are displaying 50 results per page. No option to switch to other units of results

**Comment by thatbudakguy** [comment]
@jabauer we haven't implemented other results-per-page sizes; I should've made a note - sorry about that

**Comment by rlskoeser** [comment]
@xinyil I'm going to switch the buttons to use `compact`, but I think this is ok for the current phase of work, since we're just using stock semantic ui styles at this point.  I'm wondering if (hopeful that) we'll be able to style it so we can keep it to one line for mobile.

**Comment by xinyil** [comment]
in the mock-up they are one line on screen with 320px width. they should fit in one line on most devices.
