### ISSUE TITLE
Keyword search is failing to show more than one term in context

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#463]
Regression, not a bug, because it is working properly in production. Some examples:

Test 1: https://test-ppa.cdh.princeton.edu/archive/?query=%22cadence%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance&page=2

Production 1: https://prosody.princeton.edu/archive/?query=%22cadence%22&collections=9&collections=10&collections=11&collections=3&collections=4&collections=0&sort=relevance

Test 2: https://test-ppa.cdh.princeton.edu/archive/?query=%22anapest%22%20AND%20%22Poe%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance

Production 2: https://prosody.princeton.edu/archive/?query=%22anapest%22%20AND%20%22Poe%22&collections=9&collections=10&collections=11&collections=3&collections=4&collections=0&sort=relevance

**Comment by mnaydan** [comment]
@rlskoeser this is better (it's now showing at least three snippets), but the text snippets still work better in current production. In production the snippet starts at the beginning of a sentence and the spacing is natural (which is better if we want users to stay on our site rather than going out to HT/Gale). On the test site the snippets are chunked out with added spaces and often start mid-sentence. If we don't have the capacity to fix it right now it's definitely usable for the release as is, just a shame to lose functionality that was working so well! See the screenshots for comparison:
Test: <img width="805" alt="Screen Shot 2022-08-29 at 10 57 51 AM" src="https://user-images.githubusercontent.com/22945600/187232381-3d080ce0-0780-457e-961a-6c38dd3f43c9.png">
Production:<img width="852" alt="Screen Shot 2022-08-29 at 10 57 59 AM" src="https://user-images.githubusercontent.com/22945600/187232412-1bec8245-a17f-4185-b966-ddba0ff62079.png">
Test: 
<img width="892" alt="Screen Shot 2022-08-29 at 11 00 23 AM" src="https://user-images.githubusercontent.com/22945600/187232639-a81bc115-8807-4682-9e42-42f9250a80ca.png">
Production:
<img width="860" alt="Screen Shot 2022-08-29 at 11 00 32 AM" src="https://user-images.githubusercontent.com/22945600/187232660-1a1509ee-e5c6-4625-8be2-774a14d1c062.png">

**Comment by rlskoeser** [comment]
@mary I compared the solr queries and responses on the test and production Solr instances: the queries and responses seem to me like they are exactly the same. I can't explain in the difference in display that you're seeing.  

In my opinion, this isn't worth holding the release up. I propose we move forward with releasing the updated Gale/ECCO functionality and if this continues to be a problem in production, we can open an issue to look into it again the next time we're in active development.

**Comment by mnaydan** [comment]
@rlskoeser thanks for taking the time to look into it! That sounds good to me. I'll close and we can do the release.
