### ISSUE TITLE
Migrate to PUL infrastructure, postgres, and solr 8

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#473]
- [x] #474
- [x] #475
- [x] #476
- [x] test migrating database and media to qa
- [x] #486
- [x] #477
- [x] #478

**Comment by rlskoeser** [comment]
Ryan finally got access and ran pgloader on the new test server — data is showing up in admin, but looks like we didn't get the timezone configured correctly: 
![Screen Shot 2022-11-07 at 5 33 08 PM](https://user-images.githubusercontent.com/691231/200429706-a760b410-1939-45b2-9df0-c2cecfd7e99c.png)

**Comment by mnaydan** [comment]
Testing notes:
User testing:
- [ ] Basic site navigation (links, interactive styles, images)
- [ ] Basic keyword search (Boolean)
- [ ] Advanced search (author, title, Solr search, filters)
- [ ] Sort and pagination
- [ ] Search within volume
Backend testing:
- [ ] Search and filter
- [ ] Export metadata
- [ ] Edit record (change metadata, convert to excerpt, add to collection)
- [ ] Add new record (HT, Gale, log)
- [ ] Suppress record
- [ ] Add/delete user
- [ ] Add/delete collection
CMS testing:
- [ ] Edit existing content
- [ ] Add new editorial post

**Comment by mnaydan** [comment]
Still testing but I found that trying to convert an existing item to an excerpt in the backend generated a 500 error. The item I tried to convert is mdp.39015041158448.

**Comment by mnaydan** [comment]
There are also issues with adding new items. 
- For the HT items I attempted, it "Failed to sync data": hvd.32044087453239; wu.89043739457. This was also happening in production though with a different item, so I don't know whether it's a migration issue or a bug. 
- Trying to add a Gale item (CW0108840159) generated a 500 error. 

Trying to suppress an item also generated a 500 error. 

Good news is that the frontend search and navigation all looks and feels wonderful, same as production as far as I can tell.

**Comment by mnaydan** [comment]
@rlskoeser looks like the second permissions fix worked! I retested the above situations and they're all working as expected now. Thank you for the testing support! Is there any functionality you can think of that is missing in my testing list?

**Comment by rlskoeser** [comment]
@mnaydan thank you for all the testing! I'm having trouble thinking of anything not on your list! I see you have cases to test adding content from both Hathi and Gale, and converting to excerpts, which were two of the things that came to mind. 

You've tested keyword searching, page thumbnails, and keywords in context on individual documents? Did you test the links out to Hathi and Gale too?

When you tested editing content, did you try uploading and embedding any images?

**Comment by mnaydan** [comment]
@rlskoeser Yes, keyword search, page thumbnails (including links), and keywords in context appear normal on both main search and item detail search. The only weird thing I noticed when double checking this time is that our page number is sometimes placing a 1000 before the arabic conversion of the roman numeral page numbers for Gale content; this appears different from production (see the first hit on this page https://cdh-test-prosody.princeton.edu/archive/?query=rhyme&author=bysshe&collections=9&collections=10&collections=11&collections=3&collections=12&collections=4&collections=0&sort=relevance) 

For editing content, I did upload and embed images and tested using a caption, and floating left and right (all good). I tested uploading a video too and it was very small (https://cdh-test-prosody.princeton.edu/editorial/2022/11/how-we-test-our-site/) but I don't know if that's different from how it behaves in production.

**Comment by rlskoeser** [comment]
Migration to PUL complete!

@mnaydan if you want to follow up on any of those oddities you noticed, we can create new issues to track them. I don't remember ever implementing styles for video (I don't think we had any before?), so it may well not display ideally.
