### ISSUE TITLE
test content & urls with caliper scrapy script

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#477]
## dev notes
- [x] install dev version of caliper https://github.com/Princeton-CDH/caliper-scrapy/tree/develop
- [x] run against production site prosody.princeton.edu
- [x] save the output with name similar to others and upload a copy to [drive](https://drive.google.com/drive/folders/1prOfG7wPfRZhbXJ4kvXqluFNLpMMwxxL)
- [ ] when test site is ready, crawl test site
- [ ] compare csvs to see if we missed anything

**Comment by quadrismegistus** [comment]
Status:
* Working, prosody.princeton.edu craweld
* On pause for now until test site is ready
* Investigating discrepancy in # of URLs between 2019 and 2022 versions of prosody website

**Comment by quadrismegistus** [comment]
Coming back to this now that we have cdh-test-prosody1

**Comment by quadrismegistus** [comment]
URLs are matching, barring some discrepancies in the crawler for the test site not following some urls hardlinked to production.
