### ISSUE TITLE
Snippets: base template, header and footer

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#48]
### zeplin links
nav [L](https://zpl.io/aMmJJPo) / [M](https://zpl.io/a3v5Bl1) / [M expanded](https://zpl.io/anmggyl) / [S](https://zpl.io/am6AAdK) / [S expanded](https://zpl.io/bJKmKYr)
footer [L](https://zpl.io/bWRoRDM) / [M](https://zpl.io/bAvJDkP) / [S](https://zpl.io/bzMEj5z)

### notes
- main navigation should have the correct "pitbar" behavior borrowed from cdh-web (it hides itself when you scroll down quickly and reappears when you scroll up quickly)
- main navigation links should all work, except for editorial which isn't in this milestone
- main navigation should be responsive
- if the hamburger menu is clicked on mobile, it should make the main navigation *not* do the "pitbar" (it should always stay until the menu is dismissed)
- footer should have the correct items with more or less correct alignment (e.g. the version number is floated right on large screens but stacked on mobile)

## dev notes

- add all the basic `meta` information to the `base.html` template
- add blocks for css and js, including compress tags
- add header and footer snippets that are rendered on every page

**Comment by xinyil** [comment]
@thatbudakguy can we just move the position of the whole navigation bar, not skew its shape? 

how to handle animation and transition is a big question mark for me. usually we don't have time to design and demo. we should discuss more in our next dev team meeting!

**Comment by thatbudakguy** [comment]
so, just sort of move it up off screen like on cdh-web? I agree that would probably look cleaner. I'll see if I can get it to do that

agreed about animations. there's a lot of options out there but I think many of them are goofy so it will be good to get your advice on it.

**Comment by thatbudakguy** [comment]
ok, it's using a simple margin to push off screen like cdh-web now.

**Comment by xinyil** [comment]
- Large view will display all the menu items, only M and S use the hamburger menu button.
- the copyright statement and dev version in footer should not have rollover state
- same rollover state for all items in the footer. maybe white for normal, #light-grey on hover.

**Comment by thatbudakguy** [comment]
@xinyil when you say e.g. "M and S use the hamburger menu", does that mean M _and lower_ only? I tried to fit all the menu items in on screens e.g. 1000px wide or so (between M and L) and there was some crowding going on, so I sorta assumed that "M and S" meant "anything lower than 1440px", but I realize that might not make much sense.

**Comment by thatbudakguy** [comment]
rollover stuff will come in the next iteration I think; even though hover states are technically "interaction" I think they're component-specific styles so I've just been using the semantic UI defaults

**Comment by xinyil** [comment]
ah I see. I didn't have the L navigation bard so I thought it wasn't there. I saw it after resizing the viewport. Could we have a different breakpoint for the menu? we can display the text menu as long as they can fit.

**Comment by thatbudakguy** [comment]
ok, I've moved the nav breakpoint to its own variable so we can control it separately, and lowered it to 1000px instead of 1440px.

**Comment by jabauer** [comment]
Still needs images in the footer and live links for Contributors, Contact, and How to Site

**Comment by xinyil** [comment]
- iPad Air running iOS 10.3.3, Safari
- portrait M,  "PPA" in the navigation is not centered
- landscape M, menu items overlap
![img_0051](https://user-images.githubusercontent.com/17734456/40257745-55e0bb70-5abd-11e8-8863-d366e2a50e01.PNG)
![img_0050](https://user-images.githubusercontent.com/17734456/40257747-56761684-5abd-11e8-90f4-beffbc512f37.PNG)

**Comment by thatbudakguy** [comment]
footer is displaying "flashing" behavior right now because it gets moved around using js. need a better solution to fix it to the bottom of the viewport while still being responsive and allowing some space above it

**Comment by rlskoeser** [comment]
@thatbudakguy could we use one of these solutions? https://css-tricks.com/couple-takes-sticky-footer/ Feels like something that shouldn't need javascript.

**Comment by thatbudakguy** [comment]
@rlskoeser agree 100% it should be a CSS solution ideally. we have a weird combination of things going on in that there's already a wrapper div needed for the mobile menu's behavior, but it doesn't include the footer - plus the footer is flexible width. I'll see if I can make the flexbox or grid solutions work.

**Comment by thatbudakguy** [comment]
footer issue is now tracked on #86
