### ISSUE TITLE
trying to add new work from Hathi yields rysnc error

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#481]
Attempted to add uc1.c006043204, @rlskoeser investigated and found there was an rsync protocol error

**Comment by rlskoeser** [comment]
Error from the log file on the server:
> ERROR:ppa.archive.import_util:HathiTrust rsync failed \xe2\x80\x94\xc2\xa0Protocol incompatibility / command: rsync -rLt  --delete --ignore-errors  --files-from=/tmp/ppa_hathi_pathlist-549kqtxc.txt datasets.hathitrust.org::ht_text_pd /srv/ht_text_pd/

**Comment by rlskoeser** [comment]
@mnaydan I think this was resolved by the PUL migration — do you want to do any further testing, or should we close?

**Comment by mnaydan** [comment]
Yes, good call. This was resolved by the PUL migration. Thanks!
