### ISSUE TITLE
figure out and test pgloader timezone syntax

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/ppa-django#486]

**Comment by rlskoeser** [comment]
Ok, did some testing with this on staging postgres — couldn't find a syntax that worked for specifying the timezone, but then I had a thought and tried the pgloader without setting the timezone at all, and it looks to me like the dates came through properly. (The thought that occurred to me: maybe setting the timezone the way we did was what caused the discrepancy.)

It looks to me like we don't need to do anything to get the dates to come through properly, but we should confirm when we test — maybe when we run the migration in production.

**Comment by rlskoeser** [comment]
Confirmed when we ran pgloader on the new production system: omitting the timezone resulted in the correct behavior — log entries in the new production database and old production database have the same time.
