### ISSUE TITLE
Upgrade python from 3.6

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/ppa-django#490]

**Comment by rlskoeser** [comment]
@quadrismegistus forgot to ask, did you update the python version in ansible and test this upgrade to confirm everything works properly in qa?

**Comment by quadrismegistus** [comment]
Yes— today we did. It meant addressing this issue (https://github.com/Princeton-CDH/cdh-ansible/issues/128) by developing this PR (https://github.com/Princeton-CDH/cdh-ansible/pull/131).
