### ISSUE TITLE
Upgrade to newer versions of wagtail/django/python

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/ppa-django#496]
Some notes here on wagtail/django version conflicts I ran into which we might want to solve later.

* wagtail [2.16 adds support for django 4](https://docs.wagtail.org/en/stable/releases/2.16.html)
* wagtail 3.x changes its [wagtail.core api](https://docs.wagtail.org/en/stable/releases/3.0.html#changes-to-module-paths), breaking our code
* wagtail is now up to [4.1.1](https://docs.wagtail.org/en/stable/releases/4.1.1.html)

## testing notes

- [x] edit and create some pages with wagtail and check that things work as expected
- [x] wagtail "chooser" has changed; check that you can add a person to the contributor page
- [x] autocomplete requires configuring search; check that you can search people on the person snippet list, and that adding a person to contributor page works with partial names

test collection choices on archive search page:
- [x] confirm all collections are present and default deselected collections display as expected
- [x] confirm toggling collection filters works as expected
- [x] add a new collection in the database with no works; confirm it shows up on on the archive list but is disabled (dimmed and can't be selected)

**Comment by mnaydan** [comment]
I poked around on Django and Wagtail and I think things look good! Two issues:

1. Partial search for snippets works, but _only_ for names that I just created. Search is not working for old/existing snippets. 
2. I'm not sure if this is related to the upgrade or I discovered a different bug but "True" is showing up as a collection after I added a new collection:
![Screenshot 2024-02-12 at 12 57 28 PM](https://github.com/Princeton-CDH/ppa-django/assets/22945600/22fb348a-dbe7-4da9-a3d0-90295a8d792f)

FYI, the new option to "Show counts" in Django is very handy.

**Comment by mnaydan** [comment]
@rlskoeser thanks! the partial search is working now for snippets and images. Let me know whether the "True" collection is related to the upgrade or a separate bug.

**Comment by rlskoeser** [comment]
@mnaydan I think the "True" collection must be related to the upgrade - not sure what's causing it yet, but I remember making some changes to the relevant part of the code when I worked on the upgrade. I'm glad you spotted it!

**Comment by mnaydan** [comment]
Good news: "True" collection is no longer showing up, and selecting/deselecting yields results now as expected (no more collections=label in the URL for the case I describe above).

A couple problems: 
- When I change the default deselected collections on admin, they're not appearing auto-deselected on the frontend.
- The new collection I added ('Second Test') did not show up at all until I added a work to it.

**Comment by rlskoeser** [comment]
@mnaydan just to check: could you / did you try the checks that didn't work with a hard refresh? The last modified time is based on the solr index, which the collection changes you made wouldn't affect so the browser cache could be obscuring this.

**Comment by mnaydan** [comment]
@rlskoeser ooh good call, I did not -- thank you for suggesting, I'll do that now.

**Comment by mnaydan** [comment]
@rlskoeser aha! That's exactly what it was. Sorry I didn't think of that! Those two checks are now working.

**Comment by rlskoeser** [comment]
@mnaydan oh good! Thanks for confirming.  I do think it's ok for the last-modified to ignore these kinds of db changes, since it's not too likely to happen often.
