### ISSUE TITLE
django-webpack-loader and webpack-bundle-tracker version issues

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/ppa-django#497]
Right now we have in requirements.txt `django-webpack-loader<1` and in package.json `webpack-bundle-tracker<1`. The reqs file points to this issue https://github.com/Princeton-CDH/ppa-django/issues/366 as the reason. But we've upgraded python to 3.9 and with it several of the other required packages, so at some point it may be worth looking into whether we can upgrade these as well.

**Comment by mnaydan** [comment]
We're going to handle this as part of the django upgrades tracked on #496
