### ISSUE TITLE
Mockup: single volume search

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#50]
### zeplin links
_results within work_: [L](https://zpl.io/aXWqeEx) / [M](https://zpl.io/25y4G3Q) / [S](https://zpl.io/adMgRYl)
### notes
- does searching for a term within the work function as you expect it to?
- do the search controls (e.g. pagination) function the same way they do on the archive search?
- is it responsive?

**Comment by xinyil** [comment]
<img width="1426" alt="screen shot 2018-05-18 at 4 36 49 pm" src="https://user-images.githubusercontent.com/17734456/40256817-c439c11a-5ab9-11e8-838f-123c95ae625f.png">

- text snippets are displayed at a wrong width now at L

- reproducible on:
- Safari Version 11.0.3
- Chrome Version 66.0.3359.181

**Comment by thatbudakguy** [comment]
@xinyil think I _just_ now fixed this - saw it as well
