### ISSUE TITLE
Scanning hathi pairtree data is fragile: breaks on .DS_Store, additional or missing files

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/ppa-django#534]
Setting up an issue here to track this PR: https://github.com/Princeton-CDH/ppa-django/pull/529

I've run into a few errors when scanning through the `HATHI_DATA` folder. If there's a .DS_Store in there, as happens on macs if that folder is ever opened via Finder, or if a single work has a missing .zip file, then the entire indexing or other process (often parallel processes, which break even more messily) will break.

**Comment by quadrismegistus** [comment]
This issue also occasioned this closed PR: https://github.com/Princeton-CDH/ppa-django/pull/515

**Comment by mnaydan** [comment]
Fixed by PR #515
