### ISSUE TITLE
As a content editor, I want a separate field to display project years of involvement on project contributor page, so I can make it clear when different people were involved.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#540]
In order for years to display next to name on [contributors and board members page](https://prosody.princeton.edu/contributors/) as we want it to, year range must be added to persons name as a snippet, which shows up strangely on the Editorial page metadata when a person is on both pages. 

## testing notes
Added a new optional project years field to profile/person records. 
- [x] Confirm you can add
- [x] Confirm it is optional
- [x] Confirm that when you add it, it's displayed under project role on the contributor page

**Comment by rlskoeser** [comment]
@mnaydan does it make sense to you to consider this a new feature rather than a bug, since displaying years on the contributor page wasn't something we initially planned for?

**Comment by mnaydan** [comment]
@rlskoeser yes!

**Comment by mnaydan** [comment]
@rlskoeser thank you for the testing notes! Looks good. Minor thing: in Chrome, the padding is less than in Safari & FF -- still readable & minor enough that we can close if you're OK with it. 
<img width="274" alt="Screenshot 2023-09-01 at 2 15 12 PM" src="https://github.com/Princeton-CDH/ppa-dja
![Screenshot 2023-09-01 at 2 15 26 PM](https://github.com/Princeton-CDH/ppa-django/assets/22945600/f0d7cb4a-33b5-4b29-9f6b-3ac404caf19a)
ngo/assets/22945600/cb4b9016-4b70-4887-9979-2fdb77d7636f">

**Comment by rlskoeser** [comment]
@mnaydan is this difference on mobile or desktop? I expect padding to be a little bit off for Chrome desktop until it supports subgrid (and hopefully those new versions will be pushed out soon enough).  I'm inclined to leave this as is.

**Comment by mnaydan** [comment]
@rlskoeser difference is on desktop! Sounds good to me.
