### ISSUE TITLE
Preserving all parameters/filters when moving from main search to cluster search is inadvertently hiding cluster items

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#545]
Right now, all search parameters persist. After doing some testing, however, having the rest of the search parameters active can hide works from the cluster (especially publication date). Title and author generally shouldn't be a huge issue, but they might be - that's why we generated the clusterID, because titles & authors weren't always exact matches within a cluster. So I could imagine a scenario where that hides a work.

I think if the user clicks "search and browse within a cluster," they will want to see ALL works within a cluster and then want the ability to narrow parameters from there freshly.

Only keyword (if entered) should persist.

dev revisions after first round of testing:
- [x] do not persist keyword when clicking search and browse within a cluster
- [x] update total results language when searching within a cluster

## re-testing notes
- [x] confirm that keyword does not persist when going from main search to searching within a cluster
- [x] confirm that total results language changes when searching within a cluster

**Comment by mnaydan** [comment]
@rlskoeser this seems fixed with one exception: within a cluster now, when I select and deselect collections, it will cause null results when it shouldn't. For instance, I yielded this null result when I selected Typographically Unique to be active. But since the other collections were ALSO still active, I should have still yielded 3 results. I confirmed this behavior is different from current production, which behaves as expected. 

[https://test-prosody.cdh.princeton.edu/archive/?cluster=byssheartpoems&query=rhyme&collections=9&collections=10&collections=3&collections=4&collections=label](https://test-prosody.cdh.princeton.edu/archive/?cluster=byssheartpoems&query=rhyme&collections=9&collections=10&collections=3&collections=4&collections=label) 

Playing with the URL, it appears the "collections=label" may be the issue? 

Otherwise, I tested title, author, pub date, collections, and keywords fields and it behaves as described above.

**Comment by rlskoeser** [comment]
@mnaydan I just noticed this as well - I think it's related to the upgrade problem and the "true" collection. Good catch on that collections=label, something wonky there! 

I don't think it's related to this issue, but it's fine with me to keep it open until the collection filtering is resolved so you can confirm.

**Comment by mnaydan** [comment]
Testing #554 , I ran into a case where keyword search persistence DOES hide a search result (which seems surprising to me, but maybe it shouldn't be surprising, given the varied quality of the OCR). I just wanted to make a note here to confirm that keyword search should persist for "search within the cluster." Here's an example of the case: [https://test-prosody.cdh.princeton.edu/archive/?cluster=lamyart&query=%22alien%22](https://test-prosody.cdh.princeton.edu/archive/?cluster=lamyart&query=%22alien%22)

**Comment by mnaydan** [comment]
@rlskoeser sorry to change this again, but Meredith and I talked and decided that, given this case showing keyword ALSO yields hidden results, it might make sense to prevent keyword from carrying over as well. What do you think?

**Comment by rlskoeser** [comment]
@mnaydan it's not very hard for me to change, so don't worry about that part. In terms of functionality, I defer to you and Meredith on what users would expect or would want to do when they go from the main search to searching within a cluster. I agree it's potentially quite confusing to hide cluster results when there are filters or terms already applied.

We can drop the keyword (pretty easy) or we could modify the total so that it says something like "X results out of Y total works" (it would be a little more work to figure out how to get the total, but not that hard - and seems kind of useful).  I glanced at the text, and I think we should update the wording either way. It currently reads "Displaying 1 digitized work or clusters of works" - but when you've already restricted search to a single cluster it really shouldn't say that last part.

**Comment by mnaydan** [comment]
@rlskoeser thanks -- Meredith said we should develop for the "dumbest possible user," so I think just changing the language would still be too subtle? If I'm correct, then, there are two adjustments:

1. Drop keyword
2. Update the wording so that when you search within a cluster only, it says "Displaying 1 digitized work" or "Displaying [2+] digitized works" (i.e., drop "or clusters of works")

**Comment by rlskoeser** [comment]
@mnaydan makes sense! Should be straightforward to change.

**Comment by mnaydan** [comment]
Re-tested and confirmed!
