### ISSUE TITLE
load partial html for page of search results via ajax

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#55]
If we do, template needs to be broken into components so that the view can specify the full page template or just the reloaded portion if the request is made via AJAX.

Also note from the Zotero documentation on [exposing metadata](https://www.zotero.org/support/dev/exposing_metadata)

> Websites for which metadata changes without a page reload should fire a ZoteroItemUpdated event to tell Zotero to re-detect metadata on the page. This is supported in Zotero 3.0 and later.
```
var ev = document.createEvent('HTMLEvents');
ev.initEvent('ZoteroItemUpdated', true, true);
document.dispatchEvent(ev);
```

**Comment by thatbudakguy** [comment]
I think the version of this using modern DOM API is:
```js
let ev = new Event('ZoteroItemUpdated', {
  bubbles: true,
  cancelable: true
})
document.dispatchEvent(ev)
```

**Comment by thatbudakguy** [comment]
this has become part of #65 and will now be tracked there.
