### ISSUE TITLE
changing clusters doesn't reindex pages, which results in blank records in keyword search results

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#554]
Discovered when searching "grasshopper": the first result is blank. [https://prosody.princeton.edu/archive/?query=grasshopper&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance](https://prosody.princeton.edu/archive/?query=grasshopper&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance) 

## testing notes

This change should reindex pages in solr when cluster information changes. Test keyword searching to check that pages have been  reindexed in the following scenarios:
- [x] rename a cluster
- [x] delete a cluster
- [x] edit a digitized work and add it to a cluster
- [x] edit a digitized work and remove it from a cluster

Note that renaming and deleting clusters will now trigger page index for all associated works, so for larger clusters it could be a bit slow (hopefully not so slow as to time out).

## dev notes
- [x] add signal handler for cluster update/delete: reindex all works and their pages
- [x] adjust signal handler for work: if cluster changed, reindex all pages

**Comment by rlskoeser** [comment]
Re-indexing at the work level for CW0116003677-p4 didn't resolve the blank result problem; re-indexing the pages did.

This is undoubtedly related to how we're grouping works for clusters / non-clusters; we use the work id to aggregate metadata and page content for non-clustered content, and a cluster-id for clustered works. 

As discussed with @mnaydan , this probably is related to cluster edits and reindexing; when we implemented the clusters we must have missed a signal we need to listen to reindex when cluster assignment changes. Possible what happened is that we're reindexing the work and not the pages, which left them "orphaned" in terms of group id, resulting in the blank result in the archive search.

**Comment by mnaydan** [comment]
@rlskoeser that makes sense because a lot of the blanks I'm yielding are related to clustered _excerpts_ or to multiple excerpts from a single work that also belong to a cluster, and all of these were clusters I somehow modified after import.

A couple IDs to test include CW0115867364-p10, which generates a blank CW0115867364 record that leads to a 404 page and CW0115867364-p165, which generates a second blank CW0115867364 record that leads to a 404. 

Also CW0111645585-p30, which generates a blank CW0111645585 leading to a 404. Also in this search for "on the tragic ballad" is a blank CW0111174561 (404 page), a blank leading to a CW0106653651-p12 detail page, and a blank leading to a CW0115716484-p13 detail page. For the ones with detail pages, the keyword search does not appear in the URL.

**Comment by rlskoeser** [comment]
@mnaydan I ran the `index_pages` commands on these source ids, and from what I can tell that seems to fix the weird behavior we're seeing.

**Comment by rlskoeser** [comment]
We have signal handlers for collection save/delete that reindexes all the works in the collection but I don't see any for clusters. We should have something similar for clusters, but I'll have to think through specifics... something like, cluster rename/delete should probably trigger reindex on all the works _and_ all the pages; cluster change on a work should trigger reindex pages for that work.

**Comment by mnaydan** [comment]
I think this is fixed! I completed all the testing scenarios(as well as added a new test cluster and added works to that cluster). I tested a variety of HathiTrust, ECCO, full work, excerpts, change existing cluster, no existing cluster... all are keywords searchable after modification and I'm not seeing any blanks (though hard to systematically test the absence of those...)
