### ISSUE TITLE
Investigate duplicating calls to Solr (as seen in the logs for generate_textcorpus.py)

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/ppa-django#568]
As seen in debug, it seems that code is calling twice to solr. Likely a parasolr issue. 

See if that duplication can be removed and if that speeds up the generate_textcorpus.py run time for pages

**Comment by rlskoeser** [comment]
The apparent duplicated call was actually a logging configuration problem; I was able to confirm this by adjusting my logging config locally, and I've updated the example config to match the updated syntax to hopefully avoid confusion in future.
