### ISSUE TITLE
As a user, I want different styles for the main title and subtitle on search results so that I can visually distinguish titles. 

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#57]
## testing notes
- works with subtitles should display both title and subtitle
- main titles should be **bold**; subtitles should be _italic_
- you can see this on the main archive search page in [this design](https://zpl.io/boBqGGk)
- you can also see it on the search within work page in [this design](https://zpl.io/aXWqeEx)

**Comment by rlskoeser** [comment]
@thatbudakguy latest develop code should display subtitles on results page after you reindex works in Solr.

**Comment by mnaydan** [comment]
For works that have a title and a subtitle, the formatting is correct across devices on the results and item detail pages: title appears bold and subtitle appears in italics.
