### ISSUE TITLE
upgrade to Solr 9

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#572]
## testing notes
- [x] confirm that site search works as expected with solr 9
   - [x] metadata search
   - [x] keyword search
   - [x] filtering
   - [x] sorting
 - [x] confirm that you can search for words hyphenated across line breaks as single words

## dev notes
- [x] update solr config files to work with solr 9
   - [x] add any customized fields or field types needed (unicode folding?)
   - [x] incorporate custom stemming list
   - [x] handle copy fields https://github.com/Princeton-CDH/ppa-django/blob/main/solr_conf/conf/managed-schema#L529-L530
- [x] update index fields to use dynamic fields
- [x] update solr queryset to use the new dynamic fields and alias to the old names
- [x] figure out why unit tests are hanging
- [x] add support for searching on hyphenated words across line ends

note: use `[skip ci]` on commits until we get the hanging unit test issue resolved, so we don't have tests hanging on github actions

**Comment by rlskoeser** [comment]
refer to commits on https://github.com/Princeton-CDH/geniza/issues/1359

**Comment by rlskoeser** [comment]
@laurejt I pulled your branch and uploaded the config files to a new configset in my existing docker solr 9.2 instance. I was able to create a new collection with that configset, and had no problem indexing works (`python manage.py index -i work`).

When I tried to index page content (`python manage.py index_pages`) I saw an error that sounds like what you described - it looks like the `label` field is defined as an integer in solr, but not all of our page labels are integers. When I switched the page indexing to index it as a string, it looked like indexing was working ok.

Not sure if we want to commit index field changes yet, so here's what I did:
- in ppa.archive.models line 1190 I changed "label" to "label_s"
- in ppa.archive.solr line 194 I changed the key "label" to "label_s" (although I didn't really test this change yet)

**Comment by laurejt** [comment]
Potential Issue: [deprecation of Trie fields](https://solr.apache.org/guide/solr/latest/indexing-guide/field-types-included-with-solr.html#deprecated-field-types)

Is it okay to just convert these instances to their corresponding Point fields? It looks like the "equivalent" declarations do not set the `positionIncrementGap` nor the `precisionStep` field properties (when they're set to 0).

**Comment by rlskoeser** [comment]
I found another thing we need to handle, just added to our checklist: we have a couple of copy fields defined in the old version of the schema https://github.com/Princeton-CDH/ppa-django/blob/main/solr_conf/conf/managed-schema#L529-L530

This is so we can index things two different ways: in this case, one version for tokenized text-based search and one for facet/sort.

**Comment by laurejt** [comment]
Is there a reason that [managed-schema#L135](https://github.com/Princeton-CDH/ppa-django/blob/44bd84d64448fef666a0eb49531e17aa316dfdef/solr_conf/conf/managed-schema#L135), doesn't set `positionIncrementGap` to 100?

**Comment by rlskoeser** [comment]
> Is there a reason that [managed-schema#L135](https://github.com/Princeton-CDH/ppa-django/blob/44bd84d64448fef666a0eb49531e17aa316dfdef/solr_conf/conf/managed-schema#L135), doesn't set `positionIncrementGap` to 100?

Probably because I didn't know about this setting! It looks useful for non-contiguous text blocks; I can't think of anywhere this wouldn't be helpful.

**Comment by laurejt** [comment]
Oddly, additional `TrieDateField`-based fields were defined (`tdate`, `tdates`), however they don't appear to be used by anything. They only appear to be used to create dynamic fields (`_tdt`, `_tdts`) that don't appear to be used anywhere within the codebase.

I'm going to go ahead and ignore / drop these, since the type is deprecated as it is.

**Comment by laurejt** [comment]
> > Is it okay to just convert these instances to their corresponding Point fields? It looks like the "equivalent" declarations do not set the `positionIncrementGap` nor the `precisionStep` field properties (when they're set to 0).
> 
> Thanks for flagging. I think the only date field we have is the last modified timestamp, which we aren't faceting on; we only use it for last-modified header checks. We use an integer field for the pubdate, which we do facet on. So I think this is ok, but we'll want to check the last-modified header behavior. (Could be formatting issues, maybe)

One thing to note is that this holds true for all other basic numeric types (e.g., `int`, `double`, `long`), but maybe this doesn't really matter since it could just be an indexing thing?

**Comment by laurejt** [comment]
For `text_string` is there a reason lowercase filtering is being invoked given that ICU folding [effectively incorporates this behavior](https://solr.apache.org/guide/solr/latest/indexing-guide/filters.html#icu-folding-filter)?

**Comment by laurejt** [comment]
Worth highlighting that the field type `text_gen_sort` (dyanamic field: `_t_sort`) behaves differently than`text_string` which is used for `sort_title`

**Comment by laurejt** [comment]
For `work_type` is it worth doing the text transformations within Solr rather than within Python (e.g., [models.py#L939-41](https://github.com/Princeton-CDH/ppa-django/blob/9954fcc9f5b3c7e330325e10f0ec0816bfc3bdf2/ppa/archive/models.py#L939))?

**Comment by laurejt** [comment]
Should dynamic fields of the form `*_t` be multiValued? I'm guessing this is a mistake but right now this property is set to true because that's the "default" inherited from `text_general`.

**Comment by rlskoeser** [comment]
> For `text_string` is there a reason lowercase filtering is being invoked given that ICU folding [effectively incorporates this behavior](https://solr.apache.org/guide/solr/latest/indexing-guide/filters.html#icu-folding-filter)?

Sounds like an oversight and/or leftover; let's remove the redundant filter.

**Comment by rlskoeser** [comment]
> For `work_type` is it worth doing the text transformations within Solr rather than within Python (e.g., [models.py#L939-41](https://github.com/Princeton-CDH/ppa-django/blob/9954fcc9f5b3c7e330325e10f0ec0816bfc3bdf2/ppa/archive/models.py#L939))?

`get_item_type_display` is a django method you get automatically for a field that has choices defined - see https://docs.djangoproject.com/en/5.0/ref/models/instances/#django.db.models.Model.get_FOO_display . It makes more sense to me to keep with the python code than to put in a solr config, because if we change it in python it will automatically propagate without an additional step.

**Comment by rlskoeser** [comment]
> Should dynamic fields of the form `*_t` be multiValued? I'm guessing this is a mistake but right now this property is set to true because that's the "default" inherited from `text_general`.

I like the idea of making them consistent with the other fields! The inheritance makes that more complicated, doesn't it? So then would `*_t` be explicitly not multivalued and `*_ts` (if we need one) would be multi-valued?

**Comment by laurejt** [comment]
> > Should dynamic fields of the form `*_t` be multiValued? I'm guessing this is a mistake but right now this property is set to true because that's the "default" inherited from `text_general`.
> 
> I like the idea of making them consistent with the other fields! The inheritance makes that more complicated, doesn't it? So then would `*_t` be explicitly not multivalued and `*_ts` (if we need one) would be multi-valued?

The multi-valued version is `*_txt`

**Comment by rlskoeser** [comment]
> To clarify, I don't meant to replace that part; just the lowercasing and removal of hyphens that occurs after.

Oh! Thank you for clarifying, I didn't read it properly with the code wrapping on GitHub. That sounds smart, although may or may not be worth the overhead! Do we have an existing field that would handle this, or would need to customize (I don't even remember now why we did it this way...)

**Comment by laurejt** [comment]
> > To clarify, I don't meant to replace that part; just the lowercasing and removal of hyphens that occurs after.
> 
> Oh! Thank you for clarifying, I didn't read it properly with the code wrapping on GitHub. That sounds smart, although may or may not be worth the overhead! Do we have an existing field that would handle this, or would need to customize (I don't even remember now why we did it this way...)

We might have to create one. I'm guessing `text_en_splitting` is too aggressive, although it does something with hyphens. The minimum thing we could do is use the `*s_lower` which treats the text as a keyword and lowercases it, which would let us eliminate the lowercasing.

**Comment by mnaydan** [comment]
Tested functionality described in testing notes as well as some advanced Solr syntax and fielded keyword searches. Everything looks good as far as I can tell. @rlskoeser kicking back to you.

**Comment by rlskoeser** [comment]
@mnaydan hyphenation filter is ready for you test now. Do you need help finding examples? 

Here's a phrase I just found that works on the test site now but not in production: "ability to pass from one register"

**Comment by mnaydan** [comment]
This is cool! Thanks for the example. Here are some more examples of it working: "slight alterations of manuscript readings" working [on test](https://test-prosody.cdh.princeton.edu/archive/?query=%22slight%20alterations%20of%20manuscript%20readings%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance) but not [on production](https://prosody.princeton.edu/archive/?query=%22slight%20alterations%20of%20manuscript%20readings%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance); "conflicting phenomena" working [on test](https://test-prosody.cdh.princeton.edu/archive/?query=%22conflicting%20phenomena%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance) but not [on production](https://prosody.princeton.edu/archive/?query=%22conflicting%20phenomena%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance).

One strange case I found didn't highlight the whole phrase because - I figured out - there's a white space either at the end of the line or at the beginning of the next line. Here is the [search without the white space](https://test-prosody.cdh.princeton.edu/archive/?query=%22how%20little%20he%20knew%20of%20right-thinking%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance), and [the search with the white space](https://test-prosody.cdh.princeton.edu/archive/?query=%22how%20little%20he%20knew%20of%20right-think%20ing%22&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance).

Since this was a cool bonus feature anyway, I think I'm in agreement with your original impulse to keep it as is and close this issue. We can always revisit later and make a new issue if we want to add "hypen-whitespace" search functionality, after we have more information about the kinds of instances from our NLP work. @rlskoeser what do you think?

**Comment by rlskoeser** [comment]
@mnaydan thanks for the testing and the cool examples! I noticed, and see in your highlighting for the last example, that in a lot of cases the stemming is giving us matches for these hyphenated words, although not always.

I'm inclined to close this and get a release out with the Solr upgrade, and then keep it in mind when we decide how to handle hyphenations for the NLP work.
