### ISSUE TITLE
Snippet: single search result

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#59]
### zeplin links
list with results: [L](https://zpl.io/adM1x65) / [M](https://zpl.io/V0E1J3E) / [S](https://zpl.io/29DQDky)
### notes
- is it responsive?
- is the important metadata there (e.g. publisher)?
- do long titles or weird metadata distort it significantly?

**Comment by jabauer** [comment]
Single search result is responsive. Handles long and strange metadata in rational ways. All important metadata is there.

**Comment by xinyil** [comment]
![img_1a8ded544903-1](https://user-images.githubusercontent.com/17734456/40313764-800e5a6e-5ce4-11e8-908c-c20322bc2b64.jpeg)
![screen shot 2018-05-21 at 10 48 20 am](https://user-images.githubusercontent.com/17734456/40313772-85630d34-5ce4-11e8-8934-9ff66984f023.png)
on mobile, stack page thumbnail and text snippets. there's not enough width for text block to get good readability.

**Comment by rlskoeser** [comment]
Updated the test site so that highlighted text flows below image on mobile.
