### ISSUE TITLE
Newly added excerpts not indexing when there are multiple excerpts from a single source

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#591]
Right now, to add a new excerpt, I am importing a volume and converting that volume to an excerpt, which seems to work and be indexed. To add another excerpt from the same source, I need to "Add digitized work" and manually copy all the information (which is not ideal but doable) and set the page range. However, even after setting the page range and saving the record, it does not index the work. When I try to search in the front end, it says no matching pages. See [https://prosody.princeton.edu/admin/archive/digitizedwork/?q=uc1.b3627389](https://prosody.princeton.edu/admin/archive/digitizedwork/?q=uc1.b3627389) for instance, only one is indexed out of the four.

A slightly different case: For inu.30000099860599 (a text that had been in there since 2021), I tried to convert it to an excerpt and then add a second excerpt from it, and now neither of them are indexing. This seems to be an outlier but I'm not sure if it's indicative of a larger issue.

## dev notes
- [x] enable "save as new" django option to easily copy a record to create a new excerpt
- [x] customize fields when saving as a new record
- [x] revise suppression logic - only suppress if this is the last public work for that volume
- [x] add help text for page count in admin to clarify that it is calculated automatically on save (and note when it happens)
- [x] adjust DigitizedWork save method for digital page range logic when saving new records

## testing notes
- [x] try "save as new" function to create a new excerpt from the same volume and report back whether you think this direction looks helpful (I haven't figured out yet how to customize what fields are copied over)
- [x] check that page count has help text in admin that explains when it gets saved; does the help text make sense?
- [x] test that suppressing an excerpt only deletes pairtree data when you suppress the last public work related to that source id (maybe this would work: find or create a case where two excerpts are present from the same volume; suppress one but keep the other public; then add a second one back and see if you can index it?)
- [x] test revised 'save as new' functionality for hathitrust excerpt/articles and confirm desired behavior (follows list of fields preserved / cleared specified in the comment below)
- [x] test adding a new excerpt: page count should be calculated on save and pages should be indexed

**Comment by mnaydan** [comment]
Here is the spreadsheet of specific cases we will need to fix due to them not being indexed and/or my human error forgetting to input certain fields that are now not editable after creating the stub: https://docs.google.com/spreadsheets/d/1gMBDXcLBvrnwAIbu8bo9fwr9SDe78XkF8f9G1l-4hdw/edit?usp=sharing[https://docs.google.com/spreadsheets/d/1gMBDXcLBvrnwAIbu8bo9fwr9SDe78XkF8f9G1l-4hdw/edit?usp=sharing](url)

**Comment by rlskoeser** [comment]
@mnaydan I tried to index page content for inu.30000099860599 and got an error that the pairtree data was not present. I used the hathi rsync command to restore the pairtree data and then indexed it, and that seemed to succeed.  I only see one result for inu.30000099860599 when I search the admin, so I'm not sure the status of the second excerpt.

I'm not sure how the files would have disappeared, but I did have one thought about an edge case we may not be handling correctly - if you suppress an excerpt, I think the code might remove the pairtree data from disk even if there is another excerpt from the same volume. We should add a check for excerpts to make sure it's the last excerpt from that work before removing it.

I want to turn on the "save as new" django option for you (this is a one line config), so you can easily copy an existing record. Which of the fields that are currently read-only would you like to be able to edit? In the original workflow (import from hathi, no excerpts) we didn't expect or want them to be editable, but we can easilny change that. (This is also a trivial change in the code.)

**Comment by rlskoeser** [comment]
I wanted to try the new 'expedited' option for the page index script, since that went into production with the other upgrades and fixes, but it's choking on a work that has an empty page count. Not sure what's going on with that, I can calculate the page count but when I save it seems to get cleared out. I'll investigate that as part of #567

**Comment by mnaydan** [comment]
@rlskoeser your comment made be remember that I suppressed and deleted the second excerpt from inu.30000099860599 after I realized it hadn't indexed. So you're right, I think we must be removing the pairtree data even if there's another excerpt from the same volume. To fix it, I agree to add logic: if excerpt, confirm no other excerpts from same volume before removing pairtree. 

The empty page count issue I'm guessing is one of the new adds I made -- page count for "Add digitized work" is a manual field but not editable after save, and I forgot to input the page count. Let me think more about the read-only/editable fields and I'll comment again.

**Comment by rlskoeser** [comment]
@mnaydan page count should be calculated automatically when the record is saved, you should never have to enter it. However, this may be another place where the logic is only correct for saved records and not for new ones.... (and I think there's also something else weird going on with page count & save logic, because I tried setting it and it still got cleared out when I saved it).

I'll update the description for this task with some specifics based on our conversation.

**Comment by mnaydan** [comment]
@rlskoeser To answer the read-only/editable field question: We shouldn't have to make any changes to read-only versus editable field status if 1) certain fields* are automatically copied over from a record after "saving as new" and 2) page count is automatically calculated upon saving after inputting page range info. 

*I would expect the following fields to be copied upon "saving as new":
- source
- source ID
- source URL
- item type
- volume
- book/journal title
- place of pub
- pub
- pub date
- record ID
- status set as Public

I would expect the following fields to be cleared upon "saving as new"
- title
- sort title
- author
- page range og
- page range digital
- page count (should be automatically calculated upon saving after entering range?)
- public notes
- notes
- cluster
- collections

Does that make sense to you too? Though, if it's easier to just make certain fields editable, it would need to be Source, Source ID, Source URL, Record ID, and page count because if I forget to enter one of those I would need to be able to fix it.

**Comment by rlskoeser** [comment]
@mnaydan that sounds like a great list! Let's see how far the save as new functionality gets us (I'll have to figure out how we control which fields are preserved and which are cleared, but there must be a way). We can make more fields editable if needed once we've tested this.

**Comment by rlskoeser** [comment]
@mnaydan I figured out the right way to customize the 'save as new' functionality, so I was able to implement the fields you requested be preserved/cleared in your comment above https://github.com/Princeton-CDH/ppa-django/issues/591#issuecomment-1973349147

I've also made changes to address the problems you identified about calculating page count and indexing pages when creating _new_ excerpts.

**Comment by mnaydan** [comment]
@rlskoeser thank you! This appears to be working! I made two excerpts from uc1.31210021525173 (uc1.31210021525173-p239 and uc1.31210021525173-p281). Both appear to be indexed, and both calculated page count upon save. Fields were copied over/cleared as expected. 

One minor issue I noticed: upon saving as new, fields in the second excerpt are not listed as protected (even those I "edited" such as title). This is maybe tricky logic because pub_date, for instance, was only edited in the _first_ excerpt, and then copied over, but would still need to be protected... not quite sure how to handle.

**Comment by rlskoeser** [comment]
@mnaydan interesting! That field is set to read-only, so I have to copy it in like the others (source id, url, etc) - I can easily add it to that list if that's the behavior we want. But the other problem - not sure if there's a way to tell if the field has "changed" when it's new, or if in that context there's any way for me to compare with the record it was copied from.

Do we update excerpts from the biblographic metadata? should we?

**Comment by rlskoeser** [comment]
@mnaydan should we start with including the protected fields in the ones I copy over, and you can test and see if that's sufficient?

**Comment by mnaydan** [comment]
@rlskoeser I'm trying to think through the logic & I think that would cover us in most cases and that sounds like the easiest solution. 

I don't know whether we update excerpts from the HT bibliographic metadata.... would the rsync updates impact those records? The excerpt metadata is highly curated by us.

**Comment by rlskoeser** [comment]
I looked at the code. We typically only set metadata from MARC records on import; we have a mechanism to update data for existing records, and that checks the protected fields to make sure an update doesn't overwrite local customizations. The only place I can see where this would happen is if someone runs the `hathi_import` script with the `--update` flag set (by default it won't do anything if the record is already in the database).  Ideally we should exempt excerpts from metadata updates completely, since it doesn't match the source record anymore, but I don't think we're using that code much anymore and would prefer to avoid digging into it too much.

I'll add protected fields to the copy list for saving as new. Hopefully that will be sufficient.

**Comment by rlskoeser** [comment]
@mnaydan took me two tries because `protected_fields` is a custom field; I had to make it not read-only when you're using the 'save as new' function, and the format is slightly different than what we use when it is read only.

You should be able to test now.

Also, occurred to me that I should check assumptions here: is this functionality needed for non-hathi records, and does it work the way you need it to? I ask because the list of read-only fields we're working around are only applied for hathi records. I think the "save as new" functionality should work for any source but I don't know how much the behavior depends on the read-only fields.

**Comment by mnaydan** [comment]
I re-tested for HathiTrust works and protected fields is copied over. However it does interfere with save-as-new functionality for Gale works -- it won't let me Save as new for a Gale work because Protected fields is a required field. 

I don't have any Gale excerpts to add currently, but it's possible we would need save-as-new functionality for Gale works, but they would probably be very small in number compared to the HathiTrust ones.

**Comment by rlskoeser** [comment]
@mnaydan updated to make it optional when editing, can you test yet again?

**Comment by mnaydan** [comment]
@rlskoeser I tried to re-add the record and I got a 500 error.

**Comment by rlskoeser** [comment]
@mnaydan I updated the code so that the protected field flags should handle empty string as a zero (no flags set / no fields protected). Could you test again ?

**Comment by mnaydan** [comment]
@rlskoeser I was able to add the second Gale excerpt (CB0126877711) & confirm both were indexed! Yay!
