### ISSUE TITLE
As a user viewing an item from EEBO-TCP in keyword search results, I want to see text snippets that match my search terms so I can see how many and what kind of pages match my search terms.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#605]
Equivalent to #375 for Gale

**Comment by rlskoeser** [comment]
Dropping page images from this user story since we don't have them for EEBO-TCP content currently

**Comment by mnaydan** [comment]
Not sure if this is functionally different from #603 now that it's revised? But number of matching pages appears as expected, which maybe is captured by this issue and not the other.
