### ISSUE TITLE
As a user, when I'm viewing an item from EEBO-TCP, I want to see the source identifier and link to view the item on EEBO-TCP so that I can get to the EEBO-TCP version of the document

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#606]
Equivalent for #376 for Gale

We'll need to decide whether to link to EEBO-TCP, or to ProQuest, or to both. We're also unsure how easy it will be to construct the URL we should link to from the ID we will have in the metadata: it looks like the ProQuest MARC records have a ProQuest URL, so we may need to use Paul's updated mapping to generate the links.

**Comment by mnaydan** [comment]
@rlskoeser volume ID is not appearing next to "View on EEBO-TCP" for excerpts only ([see example detail page here](https://test-prosody.cdh.princeton.edu/archive/A01514-pnp/?query=verse)). Full works function as expected.

**Comment by rlskoeser** [comment]
Ah, this must be why I thought I had failed to import source urls!

We have custom logic in the code for HathiTrust and Gale when we need to link to the first page, but we've handled that differently for EEBO-TCP by setting the source URL to link directly to the excerpt. I'll update the template code.

**Comment by rlskoeser** [comment]
@mnaydan I updated the template to handle this case. Because of the way I changed it, in addition to retesting EEBO excerpts, please also test one excerpt and one full work each for HT and Gale.

**Comment by mnaydan** [comment]
Thank you! This looks fixed. I tested a couple excerpts and full works from EEBO-TCP, and one excerpt and one full work each for HT and Gale.
