### ISSUE TITLE
Error page styles and content

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#61]
## dev notes
- [x] 404 page
- [x] 500 page
## testing notes
**designs**
[404 page](https://zpl.io/2j8D8zq)

I didn't make the "error 400/500" text all caps because it seemed arbitrary (and loud)...happy to change it though.

To test the 400, just go to a random nonexistent url, like: https://test-ppa.cdh.princeton.edu/foo/
To test the 500, go to https://test-ppa.cdh.princeton.edu/500/ to cause an error.

**Comment by thatbudakguy** [comment]
this seems fine until @xinyil makes some styles for these pages (or we could just let them look like regular pages).

**Comment by xinyil** [comment]
@thatbudakguy we have styles for error pages! see zeplin

**Comment by thatbudakguy** [comment]
@xinyil man, I legitimately looked for awhile and couldn't find it 😅 I'll try to implement this style

side note: could we make the editorial pages/content pages more like this style? I think they need to keep the navigation/footer/etc. but they can still have the "page-like" feel

**Comment by mnaydan** [comment]
Looks fine to me across devices.
