### ISSUE TITLE
As a user, I want to see the actual rather than digital page number on keyword search results of EEBO-TCP items so that I can more accurately cite items.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#610]
Equivalent to #446 for Gale

## testing notes
- [x] when original page numbers are available in EEBO-TCP, they should also show up in PPA page search results
- [x] when original page numbers are unavailable, digital page index should be displayed with brackets
- [x] page preview link - should use source url
- [x] page preview links for HathiTrust and Gale still work

**Comment by rlskoeser** [comment]
FYI, current logic is to use digital page index as fallback when no page number is present. That looks like it may be confusing for some EEBO-TCP works where they have unnumbered pages at the beginning and then real numbering begins, maybe we could do a small tweak to add brackets when we use the digital page number.

**Comment by mnaydan** [comment]
@rlskoeser ooh, yes you're right. This is confusing, as in this result: [https://test-prosody.cdh.princeton.edu/archive/A54773/?query=poesy](https://test-prosody.cdh.princeton.edu/archive/A54773/?query=poesy.) How tough would tweaking to add brackets be? 

The other minor issue I noticed is that the page number is a hyperlink, but the link target blanks to the same PPA volume search, rather than linking to EEBO-TCP. Page numbers for Gale and HT works on test site target blank to respective source as expected.

**Comment by rlskoeser** [comment]
ooh, good catch on the link. Let me see what I can do about both of these

**Comment by rlskoeser** [comment]
@mnaydan updated to add the brackets for the placeholder pages - I've only reindexed the EEBO-TCP items with this change, LMK if you want me to reindex all or selected HT & Gale page content.

For the second item: do we have a way to generate a link to the page level of the work, or even the section? Is it worth emailing the person we contacted before about EEBO-TCP?  I was tried and failed to find the image viewer you were looking at today. IDK if we can generate those URLs _or_ how stable they are.

**Comment by mnaydan** [comment]
@rlskoeser the brackets are fixed for the example I linked above, but I checked another np excerpt and the numbers aren't appearing in brackets as I would expect: [https://test-prosody.cdh.princeton.edu/archive/A04254-pnp/?query=scottis](https://test-prosody.cdh.princeton.edu/archive/A04254-pnp/?query=scottis). Perhaps there are page numbers in the XML that aren't appearing on the viewer? 

Regarding the links, the links to the viewer appear relatively standard _within_ a work, but not _across_ works. The general structure is
https://quod.lib.umich.edu/
e/
eebo/ OR eebo2/
AXXXXX.0001.001/ (full volume ID with decimals)
DigitalPageNumber:number OR DigitalPageNumber:number.number

I don't know what the numbers following the colon (and decimal, when present) are. The ONLY part of the URL that appears to change as you toggle through the viewer is the digital page number. 

Here are a few links to the viewer showing these variations, which I grabbed from the URL bar:

- https://quod.lib.umich.edu/e/eebo/A04254.0001.001/92:16.6
- https://quod.lib.umich.edu/e/eebo2/A01514.0001.001/528:46
- https://quod.lib.umich.edu/e/eebo/A16208.0001.001/94:10.1

I'm skeptical of the stability of these URLs, however, because the "Link To This Scan" URL beneath the viewer is structured differently and doesn't resolve: [https://quod.lib.umich.edu/e/eebo2/A01514.0001.001:46/528](https://quod.lib.umich.edu/e/eebo2/A01514.0001.001:46/528). My guess was this was a change that happened in the recent updates. 

Given this additional information, what are your thoughts?

**Comment by rlskoeser** [comment]
@mnaydan I think I only reindexed a subset EEBO pages, sorry - I re-ran the command to index pages for the EEBO-TCP full works but didn't reindex the excerpts! I will check on that and get back to you.

Thanks for your research on the page-level links. I'm also skeptical, and think we should reach out to the EEBO-TCP person we talked to before to ask if there's a reliable way to generate links to sections or pages.

**Comment by rlskoeser** [comment]
@mnaydan updated - I've reindexed pages for all EEBO-TCP content, and I've set the page preview link to use the source url for all works by default.  When a specific page url can be set, i.e. item is Hathi or Gale, that will override the default link.

Please spot check a few HathiTrust and Gale page result links to confirm the way I changed the template code doesn't break anything.

**Comment by mnaydan** [comment]
@rlskoeser this all looks good now! Reindexing seems to have fixed the bracket display problem, page labels are displaying as expected on the items I spot checked. 

For EEBO works the page label links now resolve using the behavior we discussed (to main page or main section for excerpts). I spot checked a few HT & Gale works (excerpts & full) and page images & labels still link as expected, nothing seems to be broken.

I think this is good enough for now to close, and if we decide to add functionality to have the labels link to specific pages once we hear back from Paul we can track that in another issue.
