### ISSUE TITLE
Investigate scraping version labels from HathiTrust excerpts to determine frequency of rescanning/range changes

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#620]

**Comment by rlskoeser** [comment]
I wanted to compare the version labels Laure scraped with the timestamps on the recently rsynced data on the staging server.  Here are a few that were recently changed:

- uiug.30112106245936: 2024-02-28 ; METS last modified 2024-02-28, zip file 2024-03-02
- coo.31924065856167: 2024-02-18 ; METS last modified 2024-02-18, zip file 2024-02-21
- nyp.33433081676979:  2024-03-01 ; METS last modified 2024-03-01, zip file 2024-03-04
- njp.32101076201159: 2024-03-19 ; for some reason, it seems this one was _not_ updated in my bulk hathi rsync, when I first checked it had modification dates in 2022-05; when I ran the rsync script on that id specifically, I now have METS last modified 2024-03-19 and zip file 2022-05-19

I could check more, but it seems pretty clear to me that the public site last modification date corresponds to the METS last modification date, which could be before OR after the zip file last modification
