### ISSUE TITLE
Snippet: sorting controls

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#64]
### zeplin links
list with results: [L](https://zpl.io/adM1x65) / [M](https://zpl.io/V0E1J3E) / [S](https://zpl.io/29DQDky)
### notes
- this issue is just to track the sort controls (the headings next to "SORT BY").
- does choosing a new sort type re-submit the form?
- is the "relevance" sort option disabled if you haven't submitted a text query?
- does the selected sort option clearly show that it's active?
- does the sort stay selected independent of other parts of the form?
- are the sort controls responsive?

**Comment by thatbudakguy** [comment]
## testing notes
- should highlight the active sort correctly
- should disable relevance sorting if no query is made
- should trigger a form submit when clicked

**Comment by thatbudakguy** [comment]
@xinyil this is minor but I noticed that in the spec the active sort item doesn't have a strong underline; just bold text. what do you think about keeping the bold underline also? I feel like it's a stronger visual cue but could go either way

**Comment by xinyil** [comment]
@thatbudakguy I've wondered how to differentiate it better since the color change is also a bit subtle. I like how you turned the divider line into a tab with the line! we could use the green for the highlight bar?

**Comment by thatbudakguy** [comment]
I like the idea of using green! I put the green on highlighted terms in search results as per the spec, but I feel like I probably shouldn't have done that yet since color changes will come in the next iteration of the frontend.

**Comment by jabauer** [comment]
Active sort is highlighted
Relevance sort is disabled if no text query as been entered. 
Changing query does not change active sort
Changing sort reloads form, and puts the user back at the top of the page (obscuring all results on mobile -- responsive design should help with this, but it's a large sort form at the top, even on a laptop).

Tested on following systems:
* MacPro 15" Retina mid 2014 running OSX10.13.4 with following browsers
	* Chrome v66.0.3359.139
	* Safari v11.1
	* Firefox v57.0.4
* iPad Pro running iOS 11.3.1
	* Safari
* iPhone 6 running iOS 11.3.1
	* Safari
* iPad Air 2 running iOS 11.2.5
	* Safari

**Comment by rlskoeser** [comment]
Created a new issue for sort controls on mobile #84, I think everything else here has been addressed.
