### ISSUE TITLE
revise Gale image URLs handling (use image urls from Gale API)

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/ppa-django#661]
Previously our Gale image display template code used a hard-coded image server base url in combination with the image id. With Gale's shift to encrypted image urls, we need to index the full image url and use that instead. The syntax for image format and sizing should still work.

## testing notes
- [x] ECCO thumbnail images display as expected in archive search
- [x] ECCO thumbnail images display as expected in single-volume search

There shouldn't really be any visible change with this, but you can confirm that we're pulling images from the new image server based on the urls. The image server hostname is luna.gale.com (previously callisto.ggsrv.com) and there's now a very long alphanumeric encrypted identifier instead of the shorter numeric ids we had before.

**Comment by mnaydan** [comment]
@rlskoeser unfortunately the Gale images are not displaying. Here are some screenshots of how it appears on the main search and detail pages respectively. This is happening for CB and CW works, and both clustered and unique works. HathiTrust images display as expected. 

![Screenshot 2024-08-14 at 9 03 40 AM](https://github.com/user-attachments/assets/bbb55bca-a280-4db1-9f09-ff643d005a58)
![Screenshot 2024-08-14 at 9 03 56 AM](https://github.com/user-attachments/assets/9ea0b754-5799-4c43-9b5c-b7fdc900a2c9)

**Comment by rlskoeser** [comment]
@mnaydan I suspect that this is because it's been a while since I indexed the pages - maybe they've started using the encryption and rotation. I'll reindex the Gale pages and see if it resolves this.

**Comment by rlskoeser** [comment]
@mnaydan completed reindexing Gale pages in staging, would you check and see if this resolves what you were seeing? (I checked one or two volumes individually but having trouble finding missing page images in the search)

**Comment by mnaydan** [comment]
@rlskoeser they're still broken on the main search page but are now appearing on the volume detail search page! Here's a sample search if you scroll down a couple: [https://test-prosody.cdh.princeton.edu/archive/?query=rhythmic&pub_date_0=1700&pub_date_1=1758&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance](https://test-prosody.cdh.princeton.edu/archive/?query=rhythmic&pub_date_0=1700&pub_date_1=1758&collections=9&collections=10&collections=3&collections=4&collections=0&sort=relevance)

**Comment by rlskoeser** [comment]
Ah! wow, ok, that's helpful - obviously some kind of code issue if it works in one place and not the other. Thanks!

**Comment by rlskoeser** [comment]
🤦‍♀️ I was passing the wrong variable to the page preview template (a non-existent `item.image_url` instead of `page.image_url`). It should be fixed now.

**Comment by mnaydan** [comment]
@rlskoeser it looks fixed now!
