### ISSUE TITLE
PPA page indexing enhancement - index all records from one source (e.g. Hathi only); handle control-c

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#662]

**Comment by rlskoeser** [comment]
I've been testing this pretty thoroughly as I'm using it in staging for both EEBO and Gale changes. Found and fixed a couple of problems with the revisions to the multiprocessing logic.  I think it's working well, but will keep open in case I find other problems as I use it for testing the other issues.

**Comment by rlskoeser** [comment]
Have been using the new version for staging successfully, considering testing complete
