### ISSUE TITLE
Modify web app code to pull Gale OCR locally instead of API

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#668]
## Testing notes
- [x] should raise a configuration error if you try to index Gale content without setting the new local ocr path
- [x] should warn when local ocr text is not found
- [x] page content indexed in Solr should use locally generated OCR instead of Gale OCR
- [x] should fall back to Gale OCR if local ocr is not available (not sure how we test this or if we need to; possible covered by the second test above)
- [x] page tag should indicate when local ocr is used (maybe test this by generating a page corpus?)

## Implementation notes
- ~Restructure OCR output (e.g. jsonl)~
- [x] Pull in API OCR if local not found
- [x] Add tag to know it's local OCR

**Comment by rlskoeser** [comment]
The first time we deployed to staging we forgot to add the new configuration for the Gale OCR path, so we went ahead and confirmed that the index pages command raises a configuration error when it is not present.

**Comment by rlskoeser** [comment]
An idea that came out of discussion about how to test this: there's no user-facing way to know when you're searching local OCR vs Gale OCR. It might be nice to add some kind of indicator on the site to let people know we're provided enhanced text content for these volumes, maybe on the volume detail page.

**Comment by laurejt** [comment]
Some useful `jq` sequences:

**Filter to Gale pages**
 `zcat ppa_pages.jsonl.gz | jq -c 'select ( (.id|startswith("CW")) or (.id|startswith("CB")) )`

**Filter to Gale pages with "local" OCR content** 
 `zcat ppa_pages.jsonl.gz | jq -c 'select ( .tags | index("local_ocr") )'`

**Comment by mnaydan** [comment]
I tested an array of Gale works (full works, excerpts, articles, CB & CW prefixes) by comparing the OCR for specific searches on the test site to the OCR in TigerData and to production site/the OCR viewer on Gale's site, and this appears to be working. For reference, these are the IDs I checked (all match the new OCR in TigerData):
- CW0111956033 (excerpt)
- CB0130649164 (full work)
- CB0128774422 (full work)
- CB0129112818 (article)
- CB0131343042 (excerpt)
- CW0116236696 (article)
- CW0116296895 (full work)

CW0114873189 uses the old Gale OCR as expected:
- page 14 on test site: £ 14 ^be English'■,•’‘�'Grammar, with Notes. r Whin (e) ends Wards, it has no Sound at all, Except in Words which we do proper call
- on Gale: £,14 ^be English'■,•’‘�'Grammar, with Notes. r,Whin (e) ends Wards, it has no Sound at all, Except in Words which we do proper call
- in TigerData: The English Grammar, with Notes.
When (e) ends Words, it has no Scund at all,
Except in Words which we do proper call;

However [the images for this volume appear broken](https://test-prosody.cdh.princeton.edu/archive/CW0114873189/?query=swift). Browsing through other volumes, it looks like this issue might be isolated to this work. Is this related to whatever you had to do to it to force it to use the old OCR? @laurejt once you confirm I'll close the issue.

I don't know how to test the page tag - maybe someone can generate corpus and I can look at the output?

**Comment by rlskoeser** [comment]
@mnaydan thanks for the detailed testing notes. I expect you would have commented if they didn't, but did your testing confirm the text content is matched up correctly with the pages?

@laurejt the fact that the images are broken and the local OCR is missing for the same volume makes me suspect that it didn't get reindexed - maybe whatever cut off your tmux session stopped before this one was indexed.  Would you index just this volume on the test server and report back if you get any warnings about missing local ocr files?

**Comment by laurejt** [comment]
(Re)Indexing CW0114873189 ran without incident (321 pages were indexed without no warnings of any sort)

**Comment by mnaydan** [comment]
@laurejt thank you! I can confirm that reindexing fixed the broken thumbnail issue, and also made it pull from local (rather than old Gale) OCR. @rlskoeser yes, my testing confirmed that text content is matched up correctly with pages. I also checked and made sure that search within excerpts/articles were limited to the selected page ranges. Closing!

**Comment by laurejt** [comment]
Exporting the text corpus after reindexing CW0114873189, all Gale pages have the `local_ocr` tag.

**Comment by laurejt** [comment]
Estimating time difference in indexing Gale volumes with current fix:

Test case: index 10 Gale volumes
- Volumes: CB0127060085 CB0126086107 CB0127060264 CB0128005380 CB0128002412 CW0115524470 CW0111606033 CW0114828122 CW0125924161 CW0110904426
- Pages: 1,762 pages

Timing:
- Production (original): 11 seconds
- Test (new): 1 minutes 14 seconds

The new indexing is *substantially* slower and should be optimized in the future.
