### ISSUE TITLE
uploading new image to CMS causes 500 server error

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#683]
I was trying to upload a PNG, which helptext says is supported, and it was only 49 KB. Tried with a different PNG and got the same error.

**Comment by rlskoeser** [comment]
I'm pretty sure this was caused by an NFS permissions error. I've made some updates that I think will correct this, please try again when you are back and get the chance.

**Comment by mnaydan** [comment]
Happy to report this is fixed! Thank you, @rlskoeser! Uploading the three images for my essay now works: [https://prosody.princeton.edu/editorial/2024/10/undergraduates-in-the-ppa-a-project-managers-guide-to-mentorship/](https://prosody.princeton.edu/editorial/2024/10/undergraduates-in-the-ppa-a-project-managers-guide-to-mentorship/)
