### ISSUE TITLE
As a content editor, I want to create and edit content pages on the site so that I can update text on the site when information changes.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#70]
## Notes for testing
- On the admin site, select the 'pages' section.  
- You should be able to add a new 'rich text page' or edit an existing one (I created a preliminary one for testing purposes, feel free to edit).
- Use the 'view on site' link at the top right to see the live version of the content page.  Formatting is provisional and the page is not completely styled, but do check that you can add and edit content and use the basic formatting you expect to use (bold, italic, add links, etc).

**Comment by meagan1019** [comment]
Edited the "What is Prosody?" text. Bold and italics work great!
