### ISSUE TITLE
Suppress dictionary & pronunciation guide from collections list page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#76]
in the future we might have a "is curated" flag on collections to differentiate these

**Comment by rlskoeser** [comment]
Or maybe `featured`?  Should discuss the different categories of collections and figure out how to describe and manage them properly.

**Comment by mnaydan** [comment]
"Dictionary" and "Pronunciation Guide" currently appear in the admin interface but not on the "About the collections" page on the frontend--so, successfully suppressed! Agreed that we should decide post 5/22 about how to manage featured/suppressed collections on the backend.
