### ISSUE TITLE
Spurious markup tags appear in result snippets

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#79]
Some OCR'd text has "tags" (e.g. `<s>` for strikethrough) that are marking up result snippets when we don't want them to. Likely need to write a filter to restrict allowed snippet text tags to `<em>` only, since solr uses that to indicate a hit.

**Comment by rlskoeser** [comment]
Not sure how to test this one since I failed to make note of the queries that I tried where I was seeing strikethrough and italics in the results.   I guess we should just all keep an eye out and see if we come across weird formatting in the search snippets...

**Comment by meagan1019** [comment]
I tried several searches and didn't see this...Closing for now!
