### ISSUE TITLE
As an admin, I want to see when an item was added to the archive and when it was last modified so that I can see which materials were added and changed and when.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#8]
---
- [x] modify import script to only update db/solr records when they have changed

**Comment by mm4CDH** [comment]
Not properly ready for testing because only when added works but updated is in progress.

**Comment by rlskoeser** [comment]
I've modified the script so it will now only update previously imported/indexed content if the hathi materials have changed since the local record was last modified (based on the `lastUpdate` field in the bibliographic API data for that specific copy of the work) _or_ when the person running the script explicitly requests an update (`--update`).  I've been puzzling over how to make this testable for you, and here's what I've come up with.

Here's some output from running the script.  This is after a previous import, and I'm not requesting updates, so records should only be updated if the hathi record has changed:
```
 python manage.py hathi_import --progress -v 0

100% (5007 of 5007) |###################################################################################################| Elapsed Time: 0:22:16 ETA:  0:00:00
Processed 5,007 items for import.
Added 0; updated 0; skipped 5,007; indexed 0 pages.
```

For convenience (mine), I've also added an option to index specific records by htid, so I also ran the script on a few records with the update option requested:
```python manage.py hathi_import yale.39002004065844 yale.39002004911344 wu.89000721803 chi.79279237 chi.79213384 --update``` 
You should be able to see them in the admin list view 

What you can't directly test is whether my logic for honoring hathi's lastUpdate date is working correctly - so please

**Comment by meagan1019** [comment]
This logic makes sense to me, and I can sort when an item was added vs. when it was modified which is why I would want this admin capability in the first place (scenario: we did a bulk import on Dec. 7, but we corrected the metadata for a view items on Dec. 11 but we made a mistake and need to go back into those files). My own question is what if a file was updated multiple times. Is there a way to track not just the most recent updates, but all? That seems to be outside the parameters of this story's wording and I don't think it's something we need to absolutely have, I'm just wondering whether that is already being tracked as you've built this and if there is a way for us to see it.

**Comment by rlskoeser** [comment]
@meagan1019 good question! Django admin has a built in log / history function.  If you click in to an individual record, you should see a "history" button on the top right (make sure you have clicked "Ok" on the test banner).  By default, this will only track edits made through the admin site - try changing a record and then look at the history again.

We can add logic to generate those log entries from the import script - it sounds like that might be valuable and something we should add now, so that we will have a full record of when and how things were added.  What do you think?

**Comment by meagan1019** [comment]
Yes, I think if it's an easy thing to do and is already being tracked in Django let's add it. One issue: I did try to edit yale.39002004065844. I was just going to correct the comma in the publisher. BUT: I get an error when I try to save: It won't let me save without adding "Enumeration/Chronology." It says "This field is required." Most books don't have this field so it shouldn't be required to add on editing. 
<img width="694" alt="screen shot 2017-12-12 at 10 38 37 am" src="https://user-images.githubusercontent.com/4306343/33893167-c800c6f2-df28-11e7-9b67-4758bc65080f.png">

**Comment by rlskoeser** [comment]
@meagan1019 good catch! agreed, that field should be optional.  I'll correct that.

**Comment by rlskoeser** [comment]
@meagan1019 enumcron field is now optional.  I see now you marked this as "tested needs attention", but I'm not clear on what is needed for you to be able to accept it.

**Comment by meagan1019** [comment]
Sorry - I put that because of the enumeration thing. Changed to accepted! Amazing work!
