### ISSUE TITLE
Adjust breakpoints to min width 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/ppa-django#85]

**Comment by thatbudakguy** [comment]
@xinyil I adjusted the semantic-UI breakpoints to the ones that we use when I implemented most of the component styles, so this is sort of done now. There are definitely some components that aren't correctly respecting the breakpoints right now, but the breakpoints themselves should be correct -  I think we can track issues with things not responding to breakpoints on individual issues for that component. Does that sound OK?
