### ISSUE TITLE
Safari adding lines to table display for digitized work detail page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#87]
This is an unsolved problem from #40 . Per @jabauer :

I see the following metadata categories (aside from title)
* Secondary Title
* Year of Publication
* Author(s)
* Publisher
* City
* PPA Collections (as buttons)
* View HathiTrust Volumes

Lines are still present in iOS 11.3.1 on iPhone 6 and iPad Pro, but not on iOS 11.2.5 (iPad Air 2)
Lines double up temporarily when resizing window on laptop see following on 
* MacPro 15" Retina mid 2014 running OSX10.13.4 with following browsers
	* Chrome v66.0.3359.139
	* Safari v11.1

![image](https://user-images.githubusercontent.com/243947/40257283-a1c491e4-5abb-11e8-9104-45b90c06f5c9.png)

Lines don't double up while resizing with Firefox v57.0.4 on MacPro 15" Retina mid 2014 running OSX10.13.4

**Comment by thatbudakguy** [comment]
looks like this is resolved now that component styles have been applied.

**Comment by thatbudakguy** [comment]
could someone other than me confirm this is fixed? @xinyil ?

**Comment by xinyil** [comment]
i can't reproduce the extra line
