### ISSUE TITLE
On-click style for buttons

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/ppa-django#88]
### on a touch device (smartphone or iPad)
- links, like the "advanced search" link on the search page, should turn gold when you touch them (but not *stay* gold).
- the collection buttons on the search page should change state when you touch them, but not stay in the pressed down/inverted state.
- collection cards on the collections page/homepage should have the pink highlight color when you touch them, but not stay that way.
- the "aside" cards on the homepage should have the pink highlight color when you touch them, but not stay that way.
### on a non touch device
everything above should work exactly the way it used to.

## dev notes
this is related to @mnaydan comment on #115 - I think both links and buttons that are links need to not have the "visited" style be the same as "onclick". That way you can see where you clicked but the style doesn't persist after the click and cause confusion.

ultimately I ended up using the experimental `@media (hover:none)` to handle this; it's supposed to detect when you have a touch device. In those situations, you want the :hover style to revert to the normal style, since touch devices keep the :hover style after you "click", which you don't want. Instead, you can use :active as the "pressed down" style.

**Comment by thatbudakguy** [comment]
if I understand this correctly, I think this might be done now because the green shadow will stay once you click them, as @mnaydan mentioned on #65 - @xinyil can you confirm it works as expected?

**Comment by xinyil** [comment]
@thatbudakguy the collection on-click looks rights on mobile, but I'm having problem unselect them. not sure if it's bc of my bad vpn connection.

the on click state of pagination buttons should also be the same as the active state.

**Comment by xinyil** [comment]
also the site doesn't scroll smoothly on iphone 7 iOS 11.1.2 Safari

**Comment by mnaydan** [comment]
On tablet and mobile the clickable object stays "clicked" until you touch something else on the screen; it doesn't "un-click" when you lift your finger. Since this is not deal-breaker behavior I'm closing out the issue.
