### ISSUE TITLE
Search within volume text snippet width

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/ppa-django#89]
<img width="701" alt="screen shot 2018-05-22 at 3 48 11 pm" src="https://user-images.githubusercontent.com/17734456/40386868-ec8344c6-5dd8-11e8-9c20-eb898e22c404.png">
shorten the text box width

**Comment by thatbudakguy** [comment]
OK, requesting a larger image preview now so that we can use it on this page (and at 2x) but still restrict it to smaller size on the main search page. Spacing should be basically correct now.

**Comment by xinyil** [comment]
@thatbudakguy can you make the text one column less that the current width? I adjusted them in the mock up but missed the first one! so the text boxes below should have the right width.

**Comment by thatbudakguy** [comment]
will be resolved by #116
