### ISSUE TITLE
As an admin, I want to see the history of all edits to a digitized work, including import and updates via script, so that I can track the full history of contributions and changes to the record.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#9]
## Notes for testing
- view history for any record using the "history" button on the top right of the individual digitized work edit page
- import script now creates a log entry when a record created via import script
- import script now creates a log entry when records are updated via import script; message should indicate if update was forced by person running the script or triggered by a hathi last modified date

--- 
- [x] update import script to create admin log entries on create and update
- [x] make author and pub date optional in admin edit
- [x] unit tests

**Comment by rlskoeser** [comment]
@meagan1019 drafted this story based on our conversation about record history - let me know if it makes sense to you and sounds sufficient!

**Comment by meagan1019** [comment]
Sounds perfect! Thanks!

**Comment by rlskoeser** [comment]
I ran the import script with an `--update` flag on a few records so you can see what the change message looks like.  Here's the script output, which includes the ids I updated:

```
 time ./manage.py hathi_import umn.31951000742933f umn.31951002169893g  umn.31951002792969k umn.31951002792970z -u

umn.31951000742933f
umn.31951002169893g
umn.31951002792969k
umn.31951002792970z

Processed 4 items for import.
Added 0; updated 4; skipped 0; 0 errors; indexed 2,506 pages.

real	0m7.870s
user	0m2.299s
sys	0m0.199s
```

@meagan1019 I noticed when I looked at the history to check after I ran the script that you had updated the publisher on a couple of these.  Your change will have been overwritten by the script because we haven't yet implemented logic to persist local overrides.  Sorry about that!

**Comment by meagan1019** [comment]
Author field is blank for some of these, such as magazines or joint-edited volume. We'll need to aslo make the author field not mandatory (as with enumeration so we can save edits. (See umn.31951000742933f for an example.

**Comment by meagan1019** [comment]
I think we'll definitely want to make sure local changes aren't overwritten by the script before accepting this one. I can see that becoming a big issue if we standardize names and then those edits get lost.

**Comment by rlskoeser** [comment]
@meagan1019 agreed -  that's a feature we planned to implement later.

**Comment by meagan1019** [comment]
This is so wonderful and exactly the info I would want to see!
<img width="999" alt="screen shot 2017-12-15 at 3 22 53 pm" src="https://user-images.githubusercontent.com/4306343/34059174-e3f692ee-e1ab-11e7-9d63-7b87929ce9b0.png">

**Comment by rlskoeser** [comment]
@meagan1019 is the only thing needed for this one making the author optional on the edit form?

**Comment by meagan1019** [comment]
Yes, and looking through the materials, the only fields that should be mandatory right now are "source id," "title," and "page count." The other fields all have entries with blanks.

**Comment by rlskoeser** [comment]
@meagan1019 I've updated the code so that the only editable field that's required is title.

**Comment by mm4CDH** [comment]
So I think I understand everything correctly piecing through what Meagan tested before and RK's responses. It looks like publication date, Publisher, Place of Publication, Author, Enumeration/Chronology, Title are all editable. I'm not quite sure about RK's last note above that says the only editable field that's required is title, but I think this one is done? I'll be sure to ask Meagan to double-check but I think we can close it for now.
