### ISSUE TITLE
Style updates: top navigation menu

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#96]
## testing notes
this behaves differently based on the section of the site you're in:
[about pages](https://zpl.io/aREeA9K)
[collections page / archive page / detail page](https://zpl.io/a8PLdvw)
[homepage](https://zpl.io/amyZ6mr)
[editorial page / list page](https://zpl.io/aXkRDrx)

the area of the site you're in should be indicated by the colored triangle.

the dropdown under "about" should be hover-activated on desktop, but touch-activated (and stay open) on tablet/mobile.

the PPA logotype (in the center of the menu) should gracefully appear/disappear on tablet & mobile when the menu is pulled open so that it's not in the way of the menu items.

## dev notes
the wagtail user bar was causing issues because its included CSS redeclared the same font we use but at a different weight, which came after our CSS and changed the look of the page. I edited out the font declaration from the user bar CSS file and things are working again (the effect of this is that the fonts in the wagtail user bar are slightly bolder, which I think is an acceptable solution).

**Comment by mnaydan** [comment]
1. The pink triangle for "About" cuts across the arrow symbol awkwardly in a way that it doesn't on GD's design (which I've put here):
<img width="225" alt="screen shot 2018-11-30 at 1 35 42 pm" src="https://user-images.githubusercontent.com/22945600/49308841-6d950a80-f4a7-11e8-88bd-c0da9fd99bc1.png">

2. GD's design also has the titles in the headers turn bold when you are on a page.
3. PPA logotype disappears on mobile but not on tablet.
4. On tablet and mobile the dropdown under About is blank (but functional! If you click on the blank space it takes you to a landing page.)
![img_263e5332aa99-1](https://user-images.githubusercontent.com/22945600/49309009-dd0afa00-f4a7-11e8-8211-c8c8810ce0be.jpg)

**Comment by thatbudakguy** [comment]
@mnaydan an update on this since I'm moving it back to QA:
1. updated right-padding of the element to correct this
2. should now be bold
3. this was just my bad writing the test; the logotype doesn't need to hide on tablet because there's enough space for it (unless you want it to). works as intended.
4. tested fix on an android and iPhone but would appreciate confirmation as this is a tricky one

**Comment by mnaydan** [comment]
Style elements look good now! I don't care about hiding the logotype on tablet (agreed it's big enough) and the dropdowns are visible on iPad and iPhone now.
