### ISSUE TITLE
Replace mezzanine with wagtail for content management

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#97]
## dev notes
- [x] uninstall mezzanine
- [x] undo grappelli/mezzanine stuff
- [x] install wagtail
- [x] update collection description to use wagtail richtextfield
- [x] enable wysiwyg editor for collections richtextfield
- [x] revisit content editor group permissions for shift from mezzanine -> wagtail
- [x] investigate 400/500 pages: is there a wagtail equivalent for what mezzanine does?

**Comment by rlskoeser** [comment]
Working in QA, going to call this one done.
